### ISSUE TITLE
When *does* the historical data really start?

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#100]
A colleague came into my office and asked if I knew how to get precipitation data from late July of last year for Waquoit Bay.  

 I said "Let's see if the Portal has it!".    

So when I hovered over a station in Waquoit Bay (station:"Carraige House"), I got a popup showing precip data starting from 7/18/2014:
![8-27-2015 1-38-26 pm](https://cloud.githubusercontent.com/assets/1872600/9529395/043b720c-4cc8-11e5-9883-9e13cc1e3d19.jpg)

Awesome!

But then when I clicked the station, I only saw data since 05/08/2015:
![8-27-2015 1-39-58 pm](https://cloud.githubusercontent.com/assets/1872600/9529481/8489f7da-4cc8-11e5-9d1d-5b9042ce587b.jpg)
and when I click on "parameter info", I see two more start dates displayed:  2015-07-01 at the top and 2015-03-10T16:00:00 further down:
![8-27-2015 1-39-58 pm](https://cloud.githubusercontent.com/assets/1872600/9529513/bda422c0-4cc8-11e5-952b-444caf596d89.jpg)

I couldn't figure out how to get the data from late July (if it's actually there).

It's also strange to have so many different start dates displayed.

It's also strange to have the dates displayed so many different ways (05/08/2015 on plot, and 2015-07-01 and 2015-03-10T16:00:00 in the parameter info.

**Comment by rsignell-usgs** [comment]
We just got bit by this today again.   My boss wanted to find winds from Jan 2005 for offshore of New York.  It looked like the data was available from the date range that appeared when we hovered over the station, but then the data displayed on the plot was from May 2005, and when we brought it up in ERDDAP, the default time was set to some time in August, and we couldn't figure out what the actual start time was.   This all sucks!!!

**Comment by rsignell-usgs** [comment]
I see that Dan raised the different formatting of dates issue here #104, but the issue here is different.  How can we figure out what data is truly available for the historical sensors?

**Comment by rsignell-usgs** [comment]
Tried this again today, just to make sure something hadn't fixed this, and the exact same problem still exists.

**Comment by kwilcox** [comment]
@rsignell-usgs Lance is running a script that is fixing this issue. Individual stations will be fixed as they are processed. It's about 40% done and has been running for two days. They should be all fixed by Monday.

**Comment by rsignell-usgs** [comment]
@kwilcox , is this script fixing the issue for good, or are we going to have to run this script periodically?

**Comment by kwilcox** [comment]
For good

**Comment by emontgomery-usgs** [comment]
@rsignell-usgs FYI the earliest data should be May, 1975, from GB_SED experiment mooring #101

**Comment by rsignell-usgs** [comment]
@emontgomery-usgs this is a different issue -- that there was no alignment between different views of the start-stop times for each dataset.   But I did some spot checking and indeed this problem seems solved, so I'm closing it.
