### ISSUE TITLE
New Content/Layout for CMG Entry/Home Page

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#101]
heading(title): "USGS CMG" =>" USGS Oceanographic Model and Data Explorer"
subtitle: Explore ocean and related data from USGS and other freely available sources using dynamically generated maps and graphs.  

three panels:
left panel:
"Spotlight on Hurricane Sandy"    
 show only datasets containing the words "Hurricane Sandy". 

middle panel:  Sensor Data

right panel:  Model Data

**Comment by kwilcox** [comment]
Text updated, waiting for purdy pictures

**Comment by rsignell-usgs** [comment]
@ngangu-usgs & @jwcarner-usgs,  on entry page at http://cmgdata.usgsportals.net/ we currently have title as "USGS Oceanographic Model and Data Explorer" and then we have "Hurricane Sandy Data", "Sensor Data" and "Model Data".     

Do you think we should call this "USGS Ocean Sensor and Model Data Explorer" to match the categories a bit better?

**Comment by nganju-usgs** [comment]
I like the title as is

On Mon, Sep 14, 2015 at 4:29 PM, Rich Signell <notifications@github.com>
wrote:

> @nganju-usgs <https://github.com/nganju-usgs> & @jcwarner-usgs
> <https://github.com/jcwarner-usgs>, on the entry page at
> http://cmgdata.usgsportals.net/ we currently have the title as "USGS
> Oceanographic Model and Data Explorer" and then we have links to "Hurricane
> Sandy Data", "Sensor Data" and "Model Data" just below.
>
> Do you think we should call this "USGS Ocean Sensor and Model Data
> Explorer" to match the categories a bit better?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/101#issuecomment-140196807>
> .
>



-- 
Neil K. Ganju
U.S. Geological Survey | Coastal and Marine Geology
384 Woods Hole Road | Woods Hole, MA 02543-1598
nganju@usgs.gov | (508) 457 2252 | (916) 207 2206
http://water.usgs.gov/fluxes

**Comment by rsignell-usgs** [comment]
So we like the title, but after talking with @nganju-usgs , can we (meaning @kwilcox) change the categories to "Hurricane Sandy", "Model Output" and "Sensor Data"  (in that order)?

**Comment by jcwarner-usgs** [comment]
we use more than just oceanographic models, we also have wave models,
atmosphere models, sediment models (which is not implied by the term
‘oceanographic’).  So i would be akin to a title change.



Also, the data is more than just ocean data,  we do have met data,
vegetation data?



But i think the emphasis should be on the model, not the data.

So i am not sure. does that help?



-j




John C. Warner, Ph.D.
U.S. Geological Survey
384 Woods Hole Road
Woods Hole, MA 02543
508-457-2237 ph. 508-457-2310 fax
jcwarner@usgs.gov
http://woodshole.er.usgs.gov/staffpages/jwarner/



*From:* Rich Signell [mailto:notifications@github.com]
*Sent:* Monday, September 14, 2015 4:30 PM
*To:* USGS-CMG/usgs-cmg-portal
*Cc:* jcwarner-usgs
*Subject:* Re: [usgs-cmg-portal] New Content/Layout for CMG Entry/Home Page
(#101)



@nganju-usgs <https://github.com/nganju-usgs> & @jcwarner-usgs
<https://github.com/jcwarner-usgs>, on the entry page at
http://cmgdata.usgsportals.net/ we currently have the title as "USGS
Oceanographic Model and Data Explorer" and then we have links to "Hurricane
Sandy Data", "Sensor Data" and "Model Data" just below.

Do you think we should call this "USGS Ocean Sensor and Model Data
Explorer" to match the categories a bit better?

—
Reply to this email directly or view it on GitHub
<https://github.com/USGS-CMG/usgs-cmg-portal/issues/101#issuecomment-140196807>
.[image: Image removed by sender.]

**Comment by rsignell-usgs** [comment]
How about just "USGS Model and Data Explorer" then?

**Comment by rsignell-usgs** [comment]
Or "Coastal and Marine Model and Data Explorer"

**Comment by jcwarner-usgs** [comment]
if we say coastal and marine, then it is more direct to what we do.  if it
just says usgs, then people might look for stream gages.

maybe we should write this out at lunch?

-j




John C. Warner, Ph.D.
U.S. Geological Survey
384 Woods Hole Road
Woods Hole, MA 02543
508-457-2237 ph. 508-457-2310 fax
jcwarner@usgs.gov
http://woodshole.er.usgs.gov/staffpages/jwarner/



*From:* Rich Signell [mailto:notifications@github.com]
*Sent:* Tuesday, September 15, 2015 4:09 PM
*To:* USGS-CMG/usgs-cmg-portal
*Cc:* jcwarner-usgs
*Subject:* Re: [usgs-cmg-portal] New Content/Layout for CMG Entry/Home Page
(#101)



Or "Coastal and Marine Model and Data Explorer"

—
Reply to this email directly or view it on GitHub
<https://github.com/USGS-CMG/usgs-cmg-portal/issues/101#issuecomment-140523024>
.[image: Image removed by sender.]
