### ISSUE TITLE
Grey-shaded timeseries plot at bottom of portal is unclear and/or unnecessary

### ISSUE THREAD

**Issue by dnowacki-usgs** [USGS-CMG/usgs-cmg-portal#102]
The grey-shaded timeseries plot at the bottom of the portal viewer is unclear to me. What do the different grey areas represent? Max/min/std/something else? I also don't see clear utility in what the graph is plotting. For example, I'm not particularly interested in how the temperature of a single sensor compares to that of the entire U.S. East Coast. 

(I know that there is help text when you click on the "?" that explains the ranges, but I don't think it should be necessary to read two paragraphs of text to understand what the grey shades mean)

Given the ambiguity of what this graph represents, and the valuable real estate it occupies, particularly on lower-resolution displays, I suggest this plot be removed, or minimized/turned off by default.

If it remains as an optional feature, I'd suggest a legend or mouseover text that shows what the grey ranges mean, and that this not remain hidden in the help text.

**Comment by rsignell-usgs** [comment]
It was pretty much unanimous when we did the demo that the sensor streaming statistical overview plot at the bottom is not helpful. 
![9-1-2015 4-33-33 pm](https://cloud.githubusercontent.com/assets/1872600/9615666/aa51fa82-50c7-11e5-9191-461facd9efca.jpg)

**Comment by kwilcox** [comment]
Panel is now hidden
