### ISSUE TITLE
content of platform and crs variables correct?

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#105]
@kwilcox @rsignell-usgs 
For the 'platform' and 'crs' variables in the CF-1.6 files, does the -2147483647 indicate missing or unknown?  I don't see the equivalent of a fill_value for these variables, so how is a client supposed to understand this content?

Can we fabricate better answers for these variables?  If they are not mandatory for the data model, can we get rid of them?  Below are examples of both variables from /MVCO_11/9102sc-a.nc.

```
Dataset {
    Int32 platform;
} usgs/data2/emontgomery/stellwagen/CF-1.6/MVCO_11/9102sc-a.nc
---------------------------------------------
platform, -2147483647

Dataset {
    Int32 crs;
} usgs/data2/emontgomery/stellwagen/CF-1.6/MVCO_11/9102sc-a.nc
---------------------------------------------
crs, -2147483647
```

**Comment by rsignell-usgs** [comment]
I'm not seeing this here:
http://geoport-dev.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/MVCO_11/9102sc-a.nc.html

Is this dataset different?

**Comment by rsignell-usgs** [comment]
@emontgomery-usgs , oh, I see what you mean.  You mean the actual values.   For `crs`, the value is irrelevant, as `crs` is a `grid_mapping` container variable and only the attributes are used.   I don't know what `platform` is used for.  

@kwilcox, ss that an Axiom thing?   It's probably also used as a container variable.

**Comment by kwilcox** [comment]
`platform` is part of the NCEI templates/recommendations

**Comment by rsignell-usgs** [comment]
After some poking around there seems to be some conflicts between the NODC NetCDF Template and the ACDD convention recommended approach for `platform`.  

On the NODC/NCEI NetCDF Templates v1.1](http://www.nodc.noaa.gov/data/formats/netcdf/v1.1/), it says `platform` is an NODC attribute, and can be either a global or variable attribute.  This attribute is supposed to contain the name of a platform container variable, and the platform container variable is supposed to contain the attributes `call_sign`, `ices_code`, `wmo_code` and `imo_code`. 

In the [NODC-provided CDL example for time series](http://data.nodc.noaa.gov/testdata/netCDFTemplateExamples/timeSeries/BodegaMarineLabBuoy.cdl) there is indeed a global attribute `platform="platform1"` and the `platform1` variable is an integer container variable:
```
int platform1 ;
		platform1:long_name = "Station 46095. Cordell Bank Buoy" ;
		platform1:nodc_name = "FIXED PLATFORM, MOORINGS" ;
		platform1:call_sign = "" ;
		platform1:ices_code = "" ;
		platform1:imo_code = "" ;
		platform1:wmo_code = "46095" ;
		platform1:comment = "" ;
```

On the [ACDD 1.3 page](http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery_1-3), we find `platform` listed a "suggested" attribute, and the description says: "Name of the platform(s) that supported the sensor data used to create this data set or product. Platforms can be of any type, including satellite, ship, station, aircraft or other. Indicate controlled vocabulary used in `platform_vocabulary`."   `platform_vocabulary` is also a "suggested" attribute.

When I googled to try to find an example, I found this IOOS vocabularies page:
https://github.com/ioos/vocabularies/blob/master/Platform%20README.md
which links to this MMI page:
http://mmisw.org/orr/#http://mmisw.org/ont/ioos/platform
on which we find terms like "airplane", "automated_underwater_vehicle", etc.   

If we were following ACDD and the IOOS controlled vocabulary for `platform`, seems like our data would be either "lander" (tripod and other platforms resting or attached to the bottom), "mooring" or "moored_buoy".

**Comment by kwilcox** [comment]
@rsignell-usgs I'm using `platform` as the NCEI templates suggest and adding the `ioos_code` attribute to describe the platform name.

```
int platform1 ;
		platform1:long_name = "Station 46095. Cordell Bank Buoy" ;
		platform1:nodc_name = "FIXED PLATFORM, MOORINGS" ;
		platform1:call_sign = "" ;
		platform1:ices_code = "" ;
		platform1:imo_code = "" ;
		platform1:wmo_code = "46095" ;
```

I agree there should be a global attribute `platform: platform` so its accessible programmatically.

**Comment by kwilcox** [comment]
Fixed in pyaxiom: https://github.com/axiom-data-science/pyaxiom/commit/afe6c65325db3eade6669fbe707ea618b57eb43b

**Comment by emontgomery-usgs** [comment]
Does this mean we now need a way of differentiating between our platforms
that are "moorings" and our platforms that are "tripods", "quadpods", etc?

Newer data files (~2010+) have a 'platform_type' attribute that says what
it was, older data won't be as easy to figure out.

FIXED_PLATFORM is always appropriate for what we've done so far.  Let me
know if you want me to think about a way to identify which type older files
are.

Thanks! Ellyn

On Mon, Sep 21, 2015 at 11:32 AM, Kyle Wilcox <notifications@github.com>
wrote:

> Fixed in pyaxiom: axiom-data-science/pyaxiom@afe6c65
> <https://github.com/axiom-data-science/pyaxiom/commit/afe6c65325db3eade6669fbe707ea618b57eb43b>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/105#issuecomment-142016486>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
`fixed` is the default, and I believe it covers the obs database.  For refernce, the IOOS vocabulary for platform types is here: http://mmisw.org/orr/#http://mmisw.org/ont/ioos/platform

**Comment by emontgomery-usgs** [comment]
@kwilcox I looked at the most recent implementation of platform and have suggestions-
Here's what is displayed as attributes for the platform variable inhttp://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/MVCO_11/9111aqd-a.nc.html now:
ioos_code: 9111aqd-a
short_name: MVCO_11 - 9111aqd-a.nc
long_name: 9111aqd-a
definition: http://mmisw.org/ont/ioos/definition/stationID

Seems to me that the long and short names should be swapped, and somewhere there should be "fixed".  The platform is a fixed bottom lander or mooring; platform_type could be tripod, quadpod, grate, swip, or mooring (we probably don't want to go there except for newer files where it's specified as a global att), the number is the instance of the use of the platform.

Not as high a priority as some of the other tickets.

**Comment by kwilcox** [comment]
@emontgomery-usgs So you would like another attribute on the `platform` variable called `type` that is carried over from the global attribute `PLATFORM_TYPE` if it exists, and if it doesn't exist, use `fixed`?

**Comment by emontgomery-usgs** [comment]
@kwilcox ,  I think the right thing to do is add a 'fixed' attribute to all platform variables, following  the style from an email earlier in the string-
nodc_name = "FIXED PLATFORM"  (if nodc_name is something in the IOOS or ACDD vocabularies)

In addition, there could be a 'type' attribute, populated from existing global attributes 'platform' or 'platform_type'.  If neither is available, use 'unknown' (unitl I can provide a list of what was what).  

The more tricky part might be getting it right for everything on a platform.  For instance, for http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/FI12/catalog.html, look at 920*; there are 11 files, all of which came from the same tripod.  I suspect that 1 or more files are missing a platform_type or platform attribute, but the information could be obtained from one of the other 920* files.  Maybe this is better accomplished in a separate step later on- Make sure all "platform" variables from the same platform have the same 'type'.

**Comment by kwilcox** [comment]
@emontgomery-usgs You would like an attribute called `platform` on every data variable in the file?  The purpose of the `platform` variable is to avoid doing things like that. I think we are safe just including the `type` attribute on the `platform` variable which describes the entire file.  @rsignell-usgs any comments?

**Comment by emontgomery-usgs** [comment]
@kwilcox  Sorry, I was confusing.  I only want these attributes in the "platform" variable.  I also want the attributes in the platform variable to be consistent for all the instruments (files) on 1 platform (920 in previous example).  Some platforms only support one instrument, others like 920 support many.

I think "fixed" may be important for the NODC/ACDD vocabularies, and is a step more abstract as a concept.  More specific information that could go in a "type" attribute; as I see it, "tripod", "quadpod" are more specific descriptions for a "fixed" platform.

**Comment by kwilcox** [comment]
@emontgomery-usgs Gotcha!  For now I will add the two attributes:

`nodc_name: "FIXED PLATFORM, MOORINGS"`
`type: [global attribute platform_type or 'fixed' if not present]`

We can revisit the `type` attribute in the future. I would need a mapping between `MOORING` and the specific type of platform.

**Comment by emontgomery-usgs** [comment]
@kwilcox thanks, sounds good.  We'll work on consistence in a later rev.  You'll swap the long ans short names too?

**Comment by kwilcox** [comment]
Yup, swapping!
