### ISSUE TITLE
"feneric_name" should be "generic_name"

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#106]
@emontgomery-usgs , in the test dataset we were using here:
http://nbviewer.ipython.org/gist/ocefpaf/1633cb2f61b61db35ad0
@ocefpaf noticed that in the dataset
http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/RCNWR/9541aqd-cal.nc.html
the variables have `feneric_name` instead of `generic_name`.   Do we use `generic_name` for anything?  Perhaps we could just remove it, but if not, certainly rename it!

**Comment by emontgomery-usgs** [comment]
@rsignell-usgs

The instance of "feneric_name" is a typo in u, v, w only, in aqd files of a
certain vintage.  It has been corrected, so newer files are all
'generic_name'.  It is an EPIC thing that is in our files (most spelled
correctly).  I don't know of a reason not to remove it in the CF version if
you want.


On Thu, Sep 10, 2015 at 1:04 PM, Rich Signell <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs> , in the test
> dataset we were using here:
> http://nbviewer.ipython.org/gist/ocefpaf/1633cb2f61b61db35ad0
> @ocefpaf <https://github.com/ocefpaf> noticed that in the dataset
>
> http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/RCNWR/9541aqd-cal.nc.html
> the variables have feneric_name instead of generic_name. Do we use
> generic_name for anything? Perhaps we could just remove it, but if not,
> certainly rename it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/106>.
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
I would vote for removal of this `generic_name` attribute.  I think this could cause confusion for folks who wonder if they can rely on this for plotting, etc.   We don't want folks doing that.

**Comment by emontgomery-usgs** [comment]
The typos of "feneric"_name in the raw data were fixed in Sept., and were used in the most recent conversion to CF-1.6, so there shouldn't be any there any more, but the portal's ncml could also remove both, just to be sure.
