### ISSUE TITLE
FillValue (1e35) not handled correctly in new portal view of historical timeseries data

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#110]
Kyle correctly identified a data issue with BW2011/904.

I looked at it and found the spike is to 1e35, which is our usual FillValue.  It appears for this file, the portal didn't grock that 1e35 indicates data that shouldn't be plotted.  I downloaded 9041ysi-a.nc, and the plots made by software that knows how to deal with 1e35 look good (see below)
![unnamed](https://cloud.githubusercontent.com/assets/1771422/10616582/c8464ef2-7733-11e5-80c2-9df3e32baeba.png)

I know there was missing data in RCNWR #953 due to icing, so looked at that station too.  This is another "special" case that doesn't seem to be handled well- there are 3 temporal sections (A,B,C) , and there should also be an aggregated product (with "-all" in the name).  I should have remembered this so that the regex did the right thing.  The portal seems to randomly plot the variables from A, B or C, although it seems to get the entire A-C duration. The gaps in June and Sept are places with gaps in time when all the instruments were out of the water for refurbishment. The missing data in Dec. is filled with 1e35, and should be interpreted as missing.  Not sure how the portal got to displaying the values it does...
![unnamed](https://cloud.githubusercontent.com/assets/1771422/10616561/b0037cac-7733-11e5-88e9-fbbaebf078db.png)

**Comment by emontgomery-usgs** [comment]
@kwilcox , We need to re-open this- not all 1e35's are handled correctly.

Because of the spike in turbidity at 939, I have been scrutinizing the data from this platform.  In the attached please note that it's trying to include 1e35, instead of ignoring it.  The only depth for which a timeseries is plotted is .875, but from the other plot, you can see that there should be 2 nearly complete time series before the tide interferes with the upper bins.  I think the .45m bin would look fine, if the 1e35s were not displayed.  

Thanks~

![image](https://cloud.githubusercontent.com/assets/1771422/12848910/9f18ab22-cbea-11e5-9d47-dae2aec8e264.png)
![image](https://cloud.githubusercontent.com/assets/1771422/12849082/b279bc0a-cbeb-11e5-9605-c861c65abbeb.png)

**Comment by kwilcox** [comment]
Fixed, please review!

**Comment by kwilcox** [comment]
Looking at this now, it seems to be an issue for the current/vector data for many stations

**Comment by emontgomery-usgs** [comment]
true

**Comment by kwilcox** [comment]
@emontgomery-usgs Deployed a fix, give this a shot again... working here now.

![selection_155](https://cloud.githubusercontent.com/assets/13939/15120321/206630fe-15e3-11e6-89fe-8af03b7520fc.png)

**Comment by emontgomery-usgs** [comment]
I think you fixed the problem with up and down, and 1e35 for Fillvalue.  Bravo!  Took me awhile to find the curtain plot tab, but it seems to work well.

However, the plot you show has an odd discontinuity at about .5m, so I went back and looked at the original file (below)
![image](https://cloud.githubusercontent.com/assets/1771422/15122982/88668c38-15ef-11e6-9d7d-51cfd5454d96.png)

Was the data filtered to make this plot?  The bin size is .4m, so I think the code has done something to smooth it.  I don't think this is appropriate, although it's a prettier picture.  The data has points centered ..875, .475, .075,-.0325, +/-.2m.  I think the graph implies much better resolution than we had, and should accurately reflect what was collected.  @rsignell-usgs @nganju-usgs what do you think?

**Comment by emontgomery-usgs** [comment]
Handling of 1e35 and direction of plot displayed are fixed.
The questions bout velocity smoothing and the discontinuity continue in ticket 208
