### ISSUE TITLE
profile display data upside down, and averaging includes 1e35

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#111]
Another point to ponder, re display of ADCP data.  I like the general concept, but I don't think the implementation is right.  I used MVCO_11/9111aqd-a.nc to check and verify.
* Somewhere in the math, excluding bins/points with FillValue (1e35) in them isn't happening correctly
* If the data is being averaged (depth and time?) to fit the initial timeseries display, the averaging is treating the FillValues as "real" numbers instead of skipping them
* if the plot of the individual profiles is supposed to be up is at the top, the altitude is being interpreted upside down.  The data in the original CF-1.6 file has 25 things in 'Z', the deepest being -12m and the shallowest being -.1m.  In the plots, Altitude is positive, so it looks like there was a sign change along the way.
* the usual way ADCP data is displayed is shown below- I suspect this would be very difficult to implement in the portal...  The places where data was removed are shown in grey below (a lot was removed near the surface beneath the word Velocity in the title)

![unnamed](https://cloud.githubusercontent.com/assets/1771422/10616680/5710d42c-7734-11e5-9df2-24bbc38248f8.png)

**Comment by kwilcox** [comment]
The FillValue issues was resolved in https://github.com/USGS-CMG/usgs-cmg-portal/issues/110 (I was converting float32 to float64 and losing the FillValue in the process).

I also fixed another bug regarding the "flipped" Z axis. Will leave this open until the new file are in the portal.

**Comment by emontgomery-usgs** [comment]
Glad the issue didn't take too long to find!  Thanks!

On Mon, Oct 26, 2015 at 11:18 AM, Kyle Wilcox <notifications@github.com>
wrote:

> The FillValue issues was resolved in #110
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/110> (I was
> converting float32 to float64 and losing the FillValue in the process).
>
> I also fixed another bug regarding the "flipped" Z axis. Will leave this
> open until the new file are in the portal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/111#issuecomment-151170694>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356
