### ISSUE TITLE
Does the Axiom infrastructure support WFS and ESRI Rest services?

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#113]
Just want to be able to answer these questions when people ask...

**Comment by shane-axiom** [comment]
Standard OGC WFS is supported for GIS style data. ESRI rest is a definite no.

**Comment by bochenek137** [comment]
We do hijack data from ESRI Rest endpoints and then load it into
Geoserver.  Johnmarc has been doing that for MBON data in Florida.

http://axiomdatascience.com/maps/ioos/mbon/?v=rand&portal_id=46#module-metadata/e72eea94-7059-11e5-99ec-00265529168c/f782cdd4-7059-11e5-99f2-00265529168c


On Thu, Oct 22, 2015 at 10:34 AM, Shane StClair <notifications@github.com>
wrote:

> Standard OGC WFS is supported for GIS style data. ESRI rest is a definite
> no.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/113#issuecomment-150315975>
> .
>



-- 
Rob Bochenek
Information Architect, CEO
Axiom Data Science, LLC
(907)230-0304 - Cell
www.axiomdatascience.com <http://www.axiomalaska.com/>
rob@axiomdatascience.com <rob@axiomalaska.com>

**Comment by shane-axiom** [comment]
Right, depends on if you're asking if we serve data via ESRI rest (no) or if we support ingesting data via ESRI rest (yes).

**Comment by rsignell-usgs** [comment]
Okay, cool.  Thanks guys!
