### ISSUE TITLE
Make the USGS Oceanographic Time Series Database show up under Sensor Data

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#114]
@shane-axiom, here's an easy one to fix:

When users go to: http://cmgdata.usgsportals.net/  they see Sandy, Model and Sensor Data as the three main categories.  

But if you click on the "Sensor Data", you don't find the [USGS Oceanographic Time Series Database](http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c) that @kwilcox put so much effort into.   

Can you make this dataset appears on the [sensor page](http://cmgdata.usgsportals.net/#module-search?p=proj3857&b=google_hybrid&page=1&tagId=&q=sensor)

It would be great if this would be the 1st thing the appears!

**Comment by rsignell-usgs** [comment]
Oops, probably @lance-axiom, not @shane-axiom, right?

**Comment by kwilcox** [comment]
done

**Comment by rsignell-usgs** [comment]
confirmed.
