### ISSUE TITLE
The East Coast Historical Time Series time slider has max value of 2262AD. 

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#115]
The East Coast Historical Time Series time slider has max value of 2262AD. 
http://cmgdata.usgsportals.net/#module-metadata/29d46c8e-565c-11e4-8982-00265529168c/8ccf971e-565c-11e4-9915-00265529168c

Can we get rid of that one bad station?   
It makes the time slider look ridiculous.

It returns "error retrieving data" anyway:

![2015-10-22_17-11-15](https://cloud.githubusercontent.com/assets/1872600/10678393/0650b6c6-78e0-11e5-9722-828da0c89c2a.jpg)

**Comment by rsignell-usgs** [comment]
@wckoeppen, is there anything you can do about this one?  
If there was one last thing to fix before tomorrow, this would be it.

**Comment by kwilcox** [comment]
I'm fixing it

**Comment by rsignell-usgs** [comment]
:horse_racing:

**Comment by rsignell-usgs** [comment]
The demo got moved to 10:00AM ET.    I'll be testing stuff at 9:00AM to see what is or isn't working and  modify the demo accordingly.

**Comment by kwilcox** [comment]
@rsignell-usgs all set

**Comment by rsignell-usgs** [comment]
@kwilcox , awesome!
