### ISSUE TITLE
Can't change the color scale for the COAWST Forecast

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#116]
Did setting the default range on elevation have bad effects on the rest of the data?

When I go to the COAWST forecast, I select wave height for 2015-10-03 20:00 EDT
http://cmgdata.usgsportals.net/#map?p=proj3857&b=google_hybrid&page=1&tagId=&q=&lg=8ccf971e-565c-11e4-9915-00265529168c%2Cefcabc2e-eeb3-47b2-8b68-c7cbacf666a2&z=8&ll=42.73667%2C-68.33496
I get dropouts because the waves are above the max value of the color scale. 
Yet clicking "auto-set" or trying to change the max value  (by typing in "5") don't seem to work. 

These used to work!  Help!
![2015-10-22_17-23-01](https://cloud.githubusercontent.com/assets/1872600/10678808/a6ea3b14-78e2-11e5-97d3-d22ba01739ab.jpg)

**Comment by wckoeppen** [comment]
Hey @rsignell-usgs, sorry, I was working on updating the default height and shot a little low. I re-set the defaults from 0 to 12 meters, which should re-enable the scale autoset for now. We have another process to set "Sanity min/max values", which allow users to set values outside the default range (0-12) but within some global extremes. But I'm having trouble getting that process to work with ncWMS right now. I'll keep working on it.

FYI, there are also some issues with the legend not respecting English units. I'm also seeing if there's anything we can do about that.

![screen_59](https://cloud.githubusercontent.com/assets/5704500/10681661/2e029390-78d8-11e5-8259-2ed4c4504bdc.jpeg)

**Comment by wckoeppen** [comment]
I lied. Make that 0 to 14 meters. Apparently a hurricane is big.

**Comment by wckoeppen** [comment]
OK, fixed the legend as well. Silly ncWMS.

**Comment by kwilcox** [comment]
@rsignell-usgs OK to close?
