### ISSUE TITLE
Select altitude does not show the altitude, only the units (m)

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#118]
![2015-10-23_0646](https://cloud.githubusercontent.com/assets/1872600/10690815/677a3798-7952-11e5-913e-6d46254b02c2.png)

**Comment by kwilcox** [comment]
This is related to https://github.com/USGS-CMG/usgs-cmg-portal/issues/111, some of the Z values are not correctly reporting positive up.  Closing in favor of that one.

**Comment by kwilcox** [comment]
@rsignell-usgs The select box will always give the actual depth value now, but they are sometimes going in the wrong direction (see #111)
