### ISSUE TITLE
MBAY_WEST - 316 in wrong position

### ISSUE THREAD

**Issue by kwilcox** [USGS-CMG/usgs-cmg-portal#121]
@emontgomery-usgs I think it should be `-70.75, 42.25` (as it is in `3131A-A1H.cdf`) not `-71.75, 42.25` (as it is in `3161A-A.cdf`)

* http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MBAY_WEST/3161A-A.cdf.ascii?lat[0:1:0],lon[0:1:0]
* http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MBAY_WEST/3161A-A1H.cdf.ascii?lat[0:1:0],lon[0:1:0]

**Comment by emontgomery-usgs** [comment]
@kwilcox You are correct- should be -70 not -71 to match the other 316*.  Again, it's corrected on stellwagen, but didn't make it to geoport.  I'll get a corrected version over there.

**Comment by emontgomery-usgs** [comment]
@kwilcox this data is fixed and updated on CF-1.6: ready for you to re-harvest

**Comment by kwilcox** [comment]
![selection_099](https://cloud.githubusercontent.com/assets/13939/12929622/bee68d52-cf41-11e5-9de0-c9f8ba082588.png)

Looks better!
