### ISSUE TITLE
ECOHAD_I - 418 in wrong location

### ISSUE THREAD

**Issue by kwilcox** [USGS-CMG/usgs-cmg-portal#122]
@emontgomery-usgs  Reported as `0, 0` in the raw datafile [here](http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/ECOHAB_I/4181p-a.cdf.ascii?lon[0:1:0],lat[0:1:0]).

**Comment by emontgomery-usgs** [comment]
@kwilcox You win a prize!  This is one we hadn't found yet and is really NG.  The correct position is 43.8436, -69.6422.  I'll get this one corrected too

**Comment by emontgomery-usgs** [comment]
@kwilcox this data is fixed and updated on CF-1.6: ready for you to re-harvest

**Comment by kwilcox** [comment]
![selection_100](https://cloud.githubusercontent.com/assets/13939/12929787/a54809ce-cf42-11e5-9d69-7f18f08cdeaa.png)

Looks better!
