### ISSUE TITLE
Default time should be UTC, not EST

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#123]
The USGS Coastal and Marine Geology program is a national program, and this portal should reflect that.  Can we switch the time from EST to UTC?

**Comment by kwilcox** [comment]
closed in favor of https://github.com/USGS-CMG/usgs-cmg-portal/issues/125.

The timezone is dependent on where you are looking at the website from. You are EST so you get EST!
