### ISSUE TITLE
Time series plotting from USGS models 6x slower than NCSS

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#127]
The time series plotting from USGS models seemed very slow, so I compared it to extracting point data via NetCDF Subset Service (NCSS) accessing the same THREDDS services available to the CMG portal.   

For the 14 day time series I tried:
* CMG portal: 90 s
* NCSS: 15 s

Specifically, here's what I tried:  I added [potential temperature from COAWST to the portal](http://cmgdata.usgsportals.net/#map?p=proj3857&b=google_hybrid&page=1&tagId=&q=&lg=561ab05d-e399-4764-a46a-ff6790cb5e56&z=8&ll=42.70438%2C-70.53223), selected the bottom layer and clicked on a spot, which generated a two-week (14 day) time series.     This took 90 seconds to produce this plot:
![2015-11-12_16-37-59](https://cloud.githubusercontent.com/assets/1872600/11132392/bad97bc2-895d-11e5-976b-57058b4dc2c3.png)

I then used the NCSS to extract time series data from the same location:
http://geoport-dev.whoi.edu/thredds/ncss/coawst_4/use/fmrc/coawst_4_use_best.ncd?var=temp&latitude=42.34&longitude=-70.5899&time_start=2015-10-29T01%3A00%3A00Z&time_end=2015-11-13T00%3A00%3A00Z&vertCoord=+-0.96875&accept=csv

This took 15 seconds to return the CSV data,  6 times faster that the current method, and perhaps more importantly slow, but acceptable.   I don't think 90 seconds is acceptable. 

What do you think?   Can we use NCSS if it's available?

@lance-axiom mentioned here https://github.com/USGS-CMG/usgs-cmg-portal/issues/86#issuecomment-150357345 that the portal is using opendap because we can't necessarily count on NCSS being available. 

But it's so much faster that I think we need to check and use NCSS if it is available.

**Comment by kwilcox** [comment]
I agree, we should be using NCSS when it is available.  The NCSS endpoints are already in your CSW, it's just a matter of us making the changes on our end. We can fallback to DAP when NCSS isn't available.

**Comment by kwilcox** [comment]
@rsignell-usgs We are now using NCSS if its available, please check and close if all looks good!

**Comment by rsignell-usgs** [comment]
@kwilcox , oh, man!    This time series plot below just took about 5 seconds! (used to take 60+ seconds)   Way to go guys!
![2016-02-22_17-05-23](https://cloud.githubusercontent.com/assets/1872600/13234496/d9fbba82-d986-11e5-834c-7c6af455ac34.jpg)

**Comment by rsignell-usgs** [comment]
Can we change "Selected *launch* point" to just "Selected point" or "Selected location"?

**Comment by rsignell-usgs** [comment]
Hmmm, it's working for COAWST forecast, as shown above, but doesn't seem to work for this COAWST sandy dataset

http://cmgdata.usgsportals.net/#module-metadata/0d0bc16b-90f0-3976-ae4a-9906a750497e/d6be53c0-9e4c-419e-8d81-77b463822e44

**Comment by rsignell-usgs** [comment]
Wow, I wonder if this PR from the SOCIB guys would make the THREDDS ncWMS `getFeatureInfo` time series response comparable to NCSS? 
https://github.com/Unidata/thredds/pull/439
  This PR reads all the time series points at once instead of one by one.
