### ISSUE TITLE
Don't subsample time series data

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#130]
It appears that sensor time series data is being subsampled, which we should *not* be doing.   

Just as an example, if you subsample hourly water levels in a tidal region, you get crap.  

There should be tides here in Boston, but they are *no tides* in our plots:
http://cmgdata.usgsportals.net/#module-metadata/29d46c8e-565c-11e4-8982-00265529168c/8ccf971e-565c-11e4-9915-00265529168c
![2015-12-11_17-08-10](https://cloud.githubusercontent.com/assets/1872600/11756710/f7d4d520-a029-11e5-9c98-d296632c5737.jpg)

![2015-12-11_17-11-41](https://cloud.githubusercontent.com/assets/1872600/11756764/503e593e-a02a-11e5-9200-6bb3967fb741.jpg)

Feel free to change the title of this issue if this isn't the problem, but somehow we have to fix these bogus time series plots!

**Comment by nganju-usgs** [comment]
same thing with model output. Barnegat Bay model has some kind of subsampling when you zoom in on time-series. It's also super slow when you pop out the time-series plot.

**Comment by kwilcox** [comment]
I'm going to combine this with https://github.com/USGS-CMG/usgs-cmg-portal/issues/129, lets continue discussion there.
