### ISSUE TITLE
Discontinued RAWS "Error retrieving data"

### ISSUE THREAD

**Issue by dnowacki-usgs** [USGS-CMG/usgs-cmg-portal#131]
When trying to access data from a discontinued RAWS site, the portal gives an error. Date ranges are given on mouseover, but clicking gives "Error retrieving data".

This is for a RAWS station that appears to have been discontinued in October 2014: http://www.raws.dri.edu/cgi-bin/rawMAIN.pl?ncVCHI

Mouseover:
<img width="441" alt="screen shot 2015-12-16 at 10 53 01" src="https://cloud.githubusercontent.com/assets/13837821/11845748/4b69f168-a3e3-11e5-83bf-d313d035f838.png">

After clicking:
<img width="468" alt="screen shot 2015-12-16 at 10 53 15" src="https://cloud.githubusercontent.com/assets/13837821/11845761/5720c3c4-a3e3-11e5-912a-af0a0a48beb2.png">

**Comment by kwilcox** [comment]
We had data at one point in time for this station but up until the middle of 2015 we threw away old data after two weeks if the station wasn't flagged as being needed for a particular project or study.  

We no longer throw away any sensor data and the client has been updated to only show stations for which data is available.
