### ISSUE TITLE
Real-time sensor streaming claims no recent data

### ISSUE THREAD

**Issue by dnowacki-usgs** [USGS-CMG/usgs-cmg-portal#132]
Default view for real-time data is water temperature, and one gets a real-time map of color coded temperatures:

<img width="1185" alt="screen shot 2015-12-16 at 11 02 56" src="https://cloud.githubusercontent.com/assets/13837821/11846006/9240ec1c-a3e4-11e5-9050-5db3b9a5d482.png">

Switch parameter to, say, wave height/direction, and portal claims no recent data for wave height and direction: 

<img width="1185" alt="screen shot 2015-12-16 at 11 01 15" src="https://cloud.githubusercontent.com/assets/13837821/11846022/a52a84c8-a3e4-11e5-8dc2-925289fcada6.png">

It's clear in the popup that at least one station has "recent" (less than 4 hours old). Similarly the timeseries at the bottom shows recent data.

Just a guess: does this have to do with this being a "dual" sensor (both height and direction) and the real-time display can't decide which to show?

**Comment by kwilcox** [comment]
@dnowacki-usgs looks like a bug, I'll investigate!

**Comment by kwilcox** [comment]
@dnowacki-usgs We have deployed a fix, can you test this please?

**Comment by dnowacki-usgs** [comment]
Looks like that bug is indeed fixed, thanks. I'm noticing a few more things potentially related to this issue; happy to open new issues for them if you'd like:

* The statistics streaming timeseries at the bottom is a big blank box now (it's not minimized to the bottom). 
* The popup for all wave buoys claims wave direction is "Wave To Direction" although in reality it's "Wave **From** Direction" (you can see this in screenshot earlier in this thread)
* Something is funky with NDBC buoy 44014 popup. Some of the timestamps in the timeseries popup mouseover (see screenshot above) don't agree with those on the [NDBC website](http://www.ndbc.noaa.gov/station_page.php?station=44014). For the non-agreeing timestamps, which are on the hour instead of :50, wave direction is shown, while at the actual times (:50) no wave direction data is shown, even though there are valid directions at those times, at least on the NDBC website.

**Comment by kwilcox** [comment]
@dnowacki-usgs can you open a separate issue regarding the NDBC 44014 buoy?

* Streaming statistics will be hidden again soon... was an error in the CSS preventing the JS from eventually hiding that dialog box.  Check back in a little bit.
* We should be converting appropriately for this graphic but, I'll be honest, I've never double checked the data.  See: https://github.com/USGS-CMG/usgs-cmg-portal/issues/150 for more information on graphic improvements coming that will get rid of this confusion!
