### ISSUE TITLE
Date labels confusingly placed in Sensor Streaming Statistical Overview

### ISSUE THREAD

**Issue by dnowacki-usgs** [USGS-CMG/usgs-cmg-portal#133]
This issue might be moot if issue #102 results in the streaming timeseries plot being removed. However, it if stays, the date indicators need to be fixed. Right now the dates are not plotted at midnight (which they should be) or even at noon... they instead are somewhat arbitrarily placed, and sometimes there are multiple labels for the same date (e.g. 12/14/2015 below). Screenshots below show the popup when you hover mouse over the date labels on the timeseries plot. Note how times vary.

<img width="207" alt="screen shot 2015-12-16 at 11 09 19" src="https://cloud.githubusercontent.com/assets/13837821/11846202/8aea9b10-a3e5-11e5-99a7-e00c0be5f816.png">

<img width="339" alt="screen shot 2015-12-16 at 11 09 28" src="https://cloud.githubusercontent.com/assets/13837821/11846216/9f7a0ab6-a3e5-11e5-9721-849e7a1a0331.png">

<img width="311" alt="screen shot 2015-12-16 at 11 09 44" src="https://cloud.githubusercontent.com/assets/13837821/11846217/a2cbdff0-a3e5-11e5-895e-96778ecd2243.png">

**Comment by kwilcox** [comment]
Closing in favor of #102 which is slotted for milestone 1
