### ISSUE TITLE
Test the ability of CMG modelers to add model datasets

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#134]
We have [instructions to add model datasets to the portal](
https://github.com/USGS-CMG/usgs-cmg-portal/wiki/Procedure-to-contribute-model-output-to-the-portal#add-datasets-to-an-existing-thredds-data-server) but are they good enough?  
Do we better documentation, videos or hands on training?

Let's see our gang can actually follow these directions and get something added.

@nganju-usgs, should we see if Zafer can test them out?

**Comment by nganju-usgs** [comment]
good idea. let's have Zafer work with the model dataset he published in ESCO. I'll alert him today.

**Comment by rsignell-usgs** [comment]
@zdefne-usgs,  please try adding a dataset and report back with issues or success!

**Comment by zdefne-usgs** [comment]
Will do.

**Comment by rsignell-usgs** [comment]
@zdefne-usgs , looks like your dataset has made it into the catalog service:
http://nbviewer.ipython.org/gist/rsignell-usgs/0fc4f5cd1f85ec411458

**Comment by rsignell-usgs** [comment]
@kwilcox, how often does the portal query our CSW service to pick up new datasets?

I searched for "Sandy" and didn't find anything:
http://cmgdata.usgsportals.net/#module-search?p=proj3857&b=google_hybrid&page=1&tagId=&q=Sandy

Yet I can see the [ISO metadata](http://geoport-dev.whoi.edu/thredds/iso/clay/usgs/users/zdefne/run076/his/00_dir_roms.ncml?catalog=http%3A%2F%2Fgeoport-dev.whoi.edu%2Fthredds%2Fcatalog%2Fclay%2Fusgs%2Fusers%2Fzdefne%2Frun076%2Fhis%2Fcatalog.html&dataset=clay%2Fusgs%2Fusers%2Fzdefne%2Frun076%2Fhis%2F00_dir_roms.ncml) contains "Sandy" in the "abstract", which is what appears in the portal dataset description below the title, right?

**Comment by kwilcox** [comment]
I believe I'm following UDDC and using `title` and `summary`. I will confirm tomorrow.

**Comment by rsignell-usgs** [comment]
@kwilcox, does the portal check our catalog for new datasets every day?  every hour?

In either case, something must have gone wrong, because I just checked and don't see the new dataset.

**Comment by kwilcox** [comment]
I'm checking every 3 hours. I saw it come through at 9pm last night. There is still a manual step of selecting the variables to include in the portal due to lack of response here: https://github.com/USGS-CMG/usgs-cmg-portal/issues/6

**Comment by kwilcox** [comment]
Dataset is now available here: http://cmgdata.usgsportals.net/#module-metadata/0d0bc16b-90f0-3976-ae4a-9906a750497e/d6be53c0-9e4c-419e-8d81-77b463822e44

**Comment by kwilcox** [comment]
I see one other issue with this dataset... the units for "temperature" are `Celsius`.  Can you change those to `degree_Celsius`?

It does seem silly since `cf_units` accepts `Celsius` as a parameter name, but our back-end is assuming the actual standard name at this point (`degree_Celsius`). This will fix the "auto-scale" button with the Temperature layer.

```python
>>> cel = cf_units.Unit("Celsius")
>>> cel.name
'degree_Celsius'
```

**Comment by rsignell-usgs** [comment]
@zdefne-usgs I changed the units of the variable `temp` in  clay:/usgs/users/zdefne/run076/his/00_dir_roms_display.ncml
and also added a fake `Nbed` vertical coordinate for variables with `Nbed` vertical layers.   

I'll add these both to the `yaml2roms` code, but for now I edited the ncml just to see if it fixed these issues.

**Comment by rsignell-usgs** [comment]
I made the change to `degree_Celcius`, as can be seen here:
http://geoport-dev.whoi.edu/thredds/dodsC/clay/usgs/users/zdefne/run076/his/00_dir_roms_display.ncml.html

The "metric" view seems okay, but @kwilcox, what the heck is going on with the "english" units?
![2016-02-09_15-24-26](https://cloud.githubusercontent.com/assets/1872600/12929834/e68aa824-cf42-11e5-82c7-70208ae85c9b.png)

![2016-02-09_15-25-00](https://cloud.githubusercontent.com/assets/1872600/12929839/f3963b28-cf42-11e5-991c-1ff6348679a6.png)

**Comment by rsignell-usgs** [comment]
Both @zdefne-usgs and @alexisbeudin have successfully contributed simulations, so closing this.
