### ISSUE TITLE
default time range for measurements go up to year 2100

### ISSUE THREAD

**Issue by zdefne-usgs** [USGS-CMG/usgs-cmg-portal#136]
When I add the East Coast Historical Sensor Catalog to the portal the default date range is from 1975 to 2100.

**Comment by kwilcox** [comment]
We had some climatology prediction points that were screwing the range. Fixed! Thanks!

http://cmgdata.usgsportals.net/#module-metadata/07595270-5632-11e4-a256-00265529168c/10203ea8-562f-11e4-aa21-00265529168c
