### ISSUE TITLE
Salinity units are screwy with this dataset

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#138]
The salinity units are goofy here:
http://cmgdata.usgsportals.net/#map?p=proj3857&b=google_hybrid&page=1&tagId=&q=hurricane%2Bsandy&lg=a0142836-0a04-49c0-a054-6b70ff5893a9&z=10&ll=39.75128%2C-74.27307

![2016-01-07_12-12-59](https://cloud.githubusercontent.com/assets/1872600/12177173/dfc2a538-b538-11e5-9ad2-141f31f64566.jpg)

**Comment by kwilcox** [comment]
What were you expecting?  You can switch between PSS and pot in the Manage Units section.

**Comment by rsignell-usgs** [comment]
PSS has the same range as ppt (e.g. 0-35).

**Comment by kwilcox** [comment]
What are you expecting? The units of PSS to go from 0-35?

**Comment by rsignell-usgs** [comment]
Yes, exactly.

**Comment by wckoeppen** [comment]
Those are definitely screwy, and not in PSS or ppt.

Re: unit conversions, we're currently under the impression that PSS ≈ ppt in practice, an equivalence that seems to be in wide use. For example: https://www.researchgate.net/post/Does_anyone_have_experience_with_practical_salinity_scale_and_Practical_Salinity_Unit

Let us know if that's an incorrect assumption?

**Comment by rsignell-usgs** [comment]
That is correct. Same.

On Thursday, January 14, 2016, Will Koeppen <notifications@github.com>
wrote:

> Those are definitely screwy, and not in PSS or ppt.
>
> Re: unit conversions, we're currently under the impression that PSS ≈ ppt
> in practice, an equivalence that seems to be in wide use. For example:
> https://www.researchgate.net/post/Does_anyone_have_experience_with_practical_salinity_scale_and_Practical_Salinity_Unit
>
> Let us know if that's an incorrect assumption?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/138#issuecomment-171824292>
> .
>


-- 
Dr. Richard P. Signell   (508) 457-2229
USGS, 384 Woods Hole Rd.
Woods Hole, MA 02543-1598

**Comment by kwilcox** [comment]
@rsignell-usgs you need a `units` attribute on the `salt` variable for us to know how to convert correctly.  `1e-3` or `0.001` both work for us.

http://geoport-dev.whoi.edu/thredds/dodsC/clay/usgs/users/zdefne/run076/his/00_dir_roms_display.ncml.html

**Comment by kwilcox** [comment]
You have since set `disply: False` on the `salt` variable for this dataset. OK to close?

**Comment by rsignell-usgs** [comment]
Yes.
