### ISSUE TITLE
Metadata text on East Coast Historical Sensor Catalog

### ISSUE THREAD

**Issue by bbutman-usgs** [USGS-CMG/usgs-cmg-portal#139]
The metadata URL text at the top of East Coast Historical Sensor Catalog (http://cmgdata.usgsportals.net/#module-metadata/29d46c8e-565c-11e4-8982-00265529168c/8ccf971e-565c-11e4-9915-00265529168c) discusses that the data are from 'real time' sensors.  

However, some of the data are not from real time sensors.  

Also can the paragraph be more specific about the 'from the recent past'?  
'some date' would be preferable so users know what to expect.  

Let's change to this description:

**The East Coast Historical Sensor Catalog displays data produced from a variety of sensors including real-time weather stations, stream gauges, and buoys; as well as data from other fixed platforms, such as moorings.  For real-time data, this data set can be used to find and download data (from the recent past) that is not available on the source website, which often only displays data from the past week. However, it does not represent all of the available historical data that may be available by contacting the source directly (e.g., NOAA, USGS). For some historical data sets, this portal provides all historical data (for example the USGS Oceanographic Time-Series Data).**

**Comment by kwilcox** [comment]
Fixed: http://cmgdata.usgsportals.net/#module-metadata/29d46c8e-565c-11e4-8982-00265529168c/8ccf971e-565c-11e4-9915-00265529168c
