### ISSUE TITLE
Altitudes have the wrong sign in USGS CMG time series data

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#144]
The altitudes have the wrong sign in USGS CMG time series data.   Data below the sea surface has positive altitudes, when it should be negative.   This was raised in https://github.com/USGS-CMG/usgs-cmg-portal/issues/142 by @bbutman-usgs , and I verified in https://github.com/USGS-CMG/usgs-cmg-portal/issues/124#issuecomment-178516790 that the altitude of this west falmouth sensor should be -1.2, not 1.2:
![2016-02-02_6-06-36](https://cloud.githubusercontent.com/assets/1872600/12747846/7c8d9e82-c974-11e5-9f27-cc4d47e2a03a.png)

**Comment by kwilcox** [comment]
These are now "Depths", so the positive number works. This should be fixed dataset-wide, except for variables measured at a profiling station that were not part of the profile (usually temp/pressure at transducer). I will fix those here: https://github.com/USGS-CMG/usgs-cmg-portal/issues/155.

Please review

**Comment by rsignell-usgs** [comment]
I would rather have everything be altitude with z positive upward rather than depth -- is that harder?

**Comment by kwilcox** [comment]
As of today, the client normalizes all depths to Depth (positive down). Let's close this and track the addition of a user setting here: https://github.com/USGS-CMG/usgs-cmg-portal/issues/171
