### ISSUE TITLE
display of currents data confusing in historical data collection

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#147]
How would one get help finding out what is actually displayed in the plot below?  More labels or mouse-over help windows may clarify.

1) why is the x-y plot empty to start with?  This is timeseries data and something should be displayed- the behavior appear to be biased towards making profiles
2) When the mouse-over happens,a vertical profile plot is displayed, but is it east, north, direction or speed?  "Currents" doens't give enough information.
3) the polar graph probably provides a lot of information, but what?  One interpretation is that "most of the currents are e-w", but what are the % circles telling the user?
4) I find the selection of altitudes a bit mis-leading, since you don't seem to be able to display the time series of an individual or range of depths.
![image](https://cloud.githubusercontent.com/assets/1771422/12786034/3f14c550-ca5d-11e5-8cfd-101f90ff5fe5.png)

**Comment by kwilcox** [comment]
closing in favor of https://github.com/USGS-CMG/usgs-cmg-portal/issues/150
