### ISSUE TITLE
Navigation to the "U.S. Geological Survey Oceanographic Time-Series Measurement Database" page unclear

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#152]
I didn't even realize there was a separate location for just the time series data base.

I usually enter the portal here http://cmgdata.usgsportals.net/, then select "sensor data".  When you get there you see "East coast Historical Sensor data".  This includes much of the timeseries data in that region, so I thought that was all there was.

Rich told me that if you put "USGS" in the search pane, you get to the page just for the entire timeseries database.  Is it hidden for a reason, or could it be put on the landing page for "sensor data"?

Thanks!

**Comment by rsignell-usgs** [comment]
When I tried clicked on "Sensor Data" today from the home screen, the USGS Oceanographic Time Series Collection is not one of the 3 Collections shown.   Yet if you search for "usgs" you can see that the Collection exists.    Sometimes it shows up, sometimes it doesn't.    This needs to be fixed for v1.0.

![2016-02-05_10-29-21](https://cloud.githubusercontent.com/assets/1872600/12850749/5279230a-cbf4-11e5-8ad7-b561896afc06.png)
![2016-02-05_10-29-57](https://cloud.githubusercontent.com/assets/1872600/12850753/548a4228-cbf4-11e5-909a-e2c8f25d1faf.png)
![2016-02-05_10-30-32](https://cloud.githubusercontent.com/assets/1872600/12850755/5853d446-cbf4-11e5-8a4c-480e5fd63cfd.png)

**Comment by kwilcox** [comment]
That is very strange... when I slick Sensor Data, I get five results:

![selection_001](https://cloud.githubusercontent.com/assets/13939/12851346/5d1ba244-cbf7-11e5-8970-19a03253ebcc.png)

**Comment by rsignell-usgs** [comment]
Forcing a refresh (cntrl+f5 in Chrome) of the cached web page fixes the problem.
Apparently the search changed from "sensor" to "time-series" several months ago, but the page was still cached.

**Comment by emontgomery-usgs** [comment]
This is very odd.  Using Chrome, I crtl f5 in both the main index page (
cmgdata.usgsportals.net), and still just get 3 entries under sensors,  Then
I tried ctl f5 from the sensors page and refreshed, and still don't see the
time series  module.

On Fri, Feb 5, 2016 at 11:24 AM, Rich Signell <notifications@github.com>
wrote:

> Closed #152 <https://github.com/USGS-CMG/usgs-cmg-portal/issues/152>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/152#event-540859192>.
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
Yep, it's changed back to 
http://cmgdata.usgsportals.net/#module-search?p=proj3857&b=google_hybrid&page=1&tagId=&q=sensor
again.   

It's *supposed* to be
http://cmgdata.usgsportals.net/#module-search?p=proj3857&b=google_hybrid&page=1&tagId=&q=time%2Bseries

@kwilcox, what's going on here?

**Comment by rsignell-usgs** [comment]
@emontgomery-usgs, try going to chrome://settings/clearBrowserData (in chrome) and click on "clear browing data" to clear the checked stuff in the last hour.  Then refresh and see if it's fixed.   It worked for me.

**Comment by rsignell-usgs** [comment]
It turned out the the REAL PROBLEM was tha the title linked to the correct URL (with "time series"), but the image linked to the old URL (with "sensor").  
@emontgomery-usgs , no WONDER we were confused!!!
