### ISSUE TITLE
Parameter Info display depths are wrong 

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#153]
How are the fields populated?  Max Depth is certainly wrong for the example or temperature in HUSDON_SVALLEY, platform 604 (below).  This is a single point observation, so min and max depth should be the same.  

Also, there are 3 depths in the select depth pane, but only 2 things in the parameter info display. In the data, 6043mc-a.nc has z, -73.69000244140625, matching the second line (I guess the filename is the "Discriminant").  6042pt-a.nc has z, -73.94999694824219, which might match the first line, but there's nothing in "Discriminant". The third depth comes from 6041adc-a.nc.  the -73.0217 depth is reasonable for this, but I wonder why it's not displayed in the parameter info.

I suggest populating the "Interval" with the DELTA_T global attribute, if it exists.

![image](https://cloud.githubusercontent.com/assets/1771422/12797609/cf9ff844-ca92-11e5-8f49-f1d5baa763da.png)

**Comment by kwilcox** [comment]
@emontgomery-usgs this is fixed, please confirm and close!

![selection_121](https://cloud.githubusercontent.com/assets/13939/13931425/b1016614-ef79-11e5-8707-288083196113.png)

**Comment by emontgomery-usgs** [comment]
Excellent, thanks!
