### ISSUE TITLE
not all data that is present is displayed

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#154]
@kwilcox @rsignell-usgs 
Again for 939 from WFAL, there are 2 sea_water_temperatures, and only one shows data plotted. (The same is true for pressure at this site.) There were 2 sensors on the platform 1) 9391aqd-cal.nc  and 2) 9392ysi-a.nc, and both have good temperature (pressure) data.  The temperature from the YSI (1.2m depth) is plotted correctly. but the temperature from the aqd (1.2754m) is not.  The velocity data from the aqd is in the portal (see issue 110), so I think the temperature should be too, but when you select the 1.2754 depth, nothing is displayed.  

Might this be associated with the variable names being different?  Both have long_name == sea_water_temperature, but the ysi variable is T_28, and the ADQ is Tx_1211.  Did we at some point request that if a T_28 is present at a similar depth, not to display Tx_1211?  If we did that's good, but in this case, the depth option for the Tx_1211 variable should NOT be displayed.  

Interestingly the profile plot seems to know there are 2 things.  Usually they match, but at some times, a slight difference is displayed.

The plot below shows what the aqd at 1.2754m "should" plot (from the CF version of the file on geoport):
![image](https://cloud.githubusercontent.com/assets/1771422/12849251/9743de92-cbec-11e5-9c32-fffa38790f11.png)

Here's that the portal shows, where the profile of the 2 temperatures is slightly different:
![image](https://cloud.githubusercontent.com/assets/1771422/12849515/f8eaf27e-cbed-11e5-9be6-d682737b6206.png)

**Comment by kwilcox** [comment]
@emontgomery-usgs this is fixed, please confirm and close!

**Comment by emontgomery-usgs** [comment]
Much better, thanks!  Displaying the discriminant as it is now is very helpful.
