### ISSUE TITLE
Depth range in profile plot doesn't match the sensor depth options

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#155]
From the middle of Buzzards Bay, number 859. The 3 depths offered in select depth are between 7.6 & 8.9 meters.  "Z positive up" still seems confused.  The actual z data in the file is negative, appropriate for a z-positive up world when data is under water, but the axis scaling doesn't always get it right.  Maybe this is because there are positive Z bins in 8591wh-a.nc, but they're at 0.4 and 0.9, and don't apply to the temperature data anyhow.  

The first plot displays the data at the correct depths but the axis scales to +, which would be in air.  by the second plot, it seems to be plotting the "top" depth in air at a depth of the wrong sign.

![image](https://cloud.githubusercontent.com/assets/1771422/12849791/795d95be-cbef-11e5-9d54-490d7febb445.png)
![image](https://cloud.githubusercontent.com/assets/1771422/12849810/9854a0a2-cbef-11e5-993e-e8e979e62af3.png)

**Comment by kwilcox** [comment]
Fixed in https://github.com/USGS-CMG/usgs-cmg-portal/commit/d3eeec9c826374cd1c0638c87f2635a6099817b6, waiting for new files before closing

**Comment by kwilcox** [comment]
Should be good to close. Keep in mind that all depths are normalized to positive down in the client. See this for a user setting solution: https://github.com/USGS-CMG/usgs-cmg-portal/issues/171
