### ISSUE TITLE
Questionable measurement data in Barnegat Bay, NJ 

### ISSUE THREAD

**Issue by zdefne-usgs** [USGS-CMG/usgs-cmg-portal#156]
10/28/2012 - 11/01/2012 water surface data at two stations don't seem right. This is during Hurricane Sandy, the time series look like air pressure time series in shape, if anything, rather than water level response... Stations are sss-nj-oce-001bp and sss-nj-oce-005bp 

![croppercapture 64](https://cloud.githubusercontent.com/assets/4505315/12864655/fdb801bc-cc5f-11e5-891e-7a81da3c8924.png)

**Comment by kwilcox** [comment]
@zdefne-usgs This is correct, these are pressure stations. I didn't realize there were two types of "sites" in this dataset (water elevation and air pressure)

http://ga.water.usgs.gov/flood/hurricane/sandy/datafiles/SSS-NJ-MON-001BP.txt

Any idea what the units of pressure are here?  Other stations in this dataset use `millimeters of mercury`, but that would make these measurements extermely low.

**Comment by dnowacki-usgs** [comment]
@kwilcox it's likely pounds per square inch (psi)

**Comment by rsignell-usgs** [comment]
@kwilcox , I'm going to ask the data provider and will report back.

**Comment by rsignell-usgs** [comment]
:star2: for @dnowacki-usgs !!

```
The barometric pressure data collected from that sensor should be in PSI. 

Regards,

~~~~~~~~~~~~~~~~~~~~~~~~~
Michal Niemoczynski

Hydrologic Technician
United States Geological Survey
NJ Water Science Center
3450 Princeton Pike Suite 110
Lawrenceville, NJ 08648

~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by kwilcox** [comment]
@zdefne-usgs all set now. Please take a look and close if its fixed.

**Comment by zdefne-usgs** [comment]
Cannot find the same stations, but USGS Hurricane Sandy Rapid Response Gauges data units seem to make sense. 
SSS-NJ-ATL-005
SSS-NJ-OCE-001
Water level is given as water_surface_height_above_reference_datum and NAVD88, but I cannot find the actual value of the datum (though, you can infer from the figure where it is constant). Is the actual value available somewhere?  Am I missing sth?

**Comment by kwilcox** [comment]
@zdefne-usgs If you click the "Parameter Info" button the vertical datum is shown. I fixed this awhile ago but forgot to update this issue!

![selection_193](https://cloud.githubusercontent.com/assets/13939/17593254/47614fd0-5fb3-11e6-8371-d0a94c246d0e.png)
