### ISSUE TITLE
On home page, there is no query for "models"

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#159]
On the home page
http://cmgdata.usgsportals.net/#
* if you click on "Hurricane Sandy", the URL is
http://cmgdata.usgsportals.net/#module-search?p=proj3857&b=google_hybrid&page=1&tagId=&q=hurricane%2Bsandy
* If you click on "Sensor Data", the URL is (finally): 
http://cmgdata.usgsportals.net/#module-search?p=proj3857&b=google_hybrid&page=1&tagId=&q=time%2Bseries
* If you click on "Models", the URL is
http://cmgdata.usgsportals.net/#module-search?p=proj3857&b=google_hybrid&page=1&tagId=&q=

This means "Models" doesn't query anything specifically, right?  
And indeed, we seem to get all datasets, not just models.

**Comment by rsignell-usgs** [comment]
@kwilcox , this should be an easy one you can delegate, right?

**Comment by kwilcox** [comment]
@rsignell-usgs all set
