### ISSUE TITLE
change unlimited time dimension to fixed in collect.py

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#160]
I think we can speed up access to time series data by not retaining time dimensioned as "unlimited".

**Comment by rsignell-usgs** [comment]
I think @kwilcox does this on the Axiom side, but it wouldn't hurt to do it on our side as well.

**Comment by kwilcox** [comment]
This can be fixed here: https://github.com/axiom-data-science/pyaxiom/blob/cb6046bb3a7796ab0dd3432ae8149fac117cff56/pyaxiom/netcdf/sensors/timeseries.py#L385 by setting it to nc.createDimension("time", times.size)

**Comment by kwilcox** [comment]
Fixed in pyaxiom: https://github.com/axiom-data-science/pyaxiom/blob/master/pyaxiom/netcdf/sensors/timeseries.py#L402
