### ISSUE TITLE
MBAY_LT 5071spd-a_d2.nc has two extra time values

### ISSUE THREAD

**Issue by kwilcox** [USGS-CMG/usgs-cmg-portal#161]
* `5071spd-a_d1.nc`: `time = 49751 ;`
* `5071spd-a_d2.nc`: `time = 49753 ;`
* `5071spd-a_d3.nc`: `time = 49751 ;`

The two values are at the end of the `time` variable:

`886222687` and `886222912`

It's not a big deal, but thought it might have been an error in the raw data.

**Comment by emontgomery-usgs** [comment]
I checked this out, and the _d2 is a tiny bit longer than _d1 and _d3 (which turn out to be identical).  Probably they were trimmed a bit differently in processing, but the data is fine as-is.
