### ISSUE TITLE
Occasional missing data fields for NDBC buoys

### ISSUE THREAD

**Issue by dnowacki-usgs** [USGS-CMG/usgs-cmg-portal#162]
Something is funky with NDBC buoy 44014: VIRGINIA BEACH 64 NM East of Virginia Beach, VA.

The data from this buoy are delivered hourly at 50 minutes past the hour (20:50, for example). These timestamps can be observed on the [NDBC page for this buoy](http://www.ndbc.noaa.gov/station_page.php?station=44014). In the mouseover popup in the portal, data are shown at the :50 mark, as expected:

<img width="431" alt="screen shot 2016-02-11 at 11 47 01" src="https://cloud.githubusercontent.com/assets/13837821/12982957/347aa0fc-d0b5-11e5-916a-1fd68d96c04a.png">

However, the data are incomplete: only significant wave height and dominant period are shown; the other fields are blank.

Continue playing with the mouseover popup and you see data presented at the top of the hour, which is not an actual time stamp for this buoy:

<img width="420" alt="screen shot 2016-02-11 at 11 48 40" src="https://cloud.githubusercontent.com/assets/13837821/12983028/753649b6-d0b5-11e5-8459-2ec78ae0fe1e.png">

At this phantom timestep, many more of the fields have values in them. (Note the absence of dominant period, however!)

This is the only buoy I've found with this issue; others (e.g., 44093: Offshore Wind Energy Area, VA - 210) seem just fine and have all data fields filled at the appropriate times.

**Comment by kwilcox** [comment]
@dnowacki-usgs There are sensor packages set at different reporting intervals for that particular buoy.  On the page http://www.ndbc.noaa.gov/station_page.php?station=44014 you can see (towards the bottom of the page) that the "Detailed Wave Summary" are at the top of each hour.  This is the best way we have come up with displaying variables at a station on different intervals. If we only showed the variables that had values for each timestep you are hovering over, it is nauseating. This way the values for the same parameter always line up and you can easily see how a particular variable is changing.

**Comment by dnowacki-usgs** [comment]
Ah, yes I see, thanks for the insight. My bad for not noticing the additional timestep on the NOAA site. This seems like a reasonable way to handle the issue so I'll close it.
