### ISSUE TITLE
Are USGS thredds modeling catalogs specified at right level?

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#165]
@alexisbeudin and @zdefne-usgs , I just realized that you both specified THREDDS catalogs at a very granular level.   As you can see from the list below, you can specify the catalog one or two directories up, like the `mvco` catalog.  The crawler will then find any `00_dir*.ncml` file in the subdirectories below.   If you specify the catalog this way, you can later create a subdirectory for a new simulation beneath this parent directory without submitting another pull request to change the catalog scan. 
```
THREDDS_SERVERS = {
'mvco': 'http://geoport-dev.whoi.edu/thredds/catalog/usgs/data0/mvco_ce/catalog.html',
'bbleh': 'http://geoport-dev.whoi.edu/thredds/catalog/usgs/data0/bbleh/catalog.html',
'bbleh-sandy': 'http://geoport-dev.whoi.edu/thredds/catalog/clay/usgs/users/zdefne/run076/catalog.html',
'sandy-jcwarner': 'http://geoport-dev.whoi.edu/thredds/catalog/clay/usgs/users/jcwarner/Projects/Sandy/catalog.html',
'chinco-sandy': 'http://geoport-dev.whoi.edu/thredds/catalog/clay/usgs/users/abeudin/chinco/Sandy/ext_dc20_nam/catalog.html'
}
```
Does this make sense to you guys?

**Comment by alexisbeudin** [comment]
ok I get it, thanks @rsignell-usgs !

**Comment by rsignell-usgs** [comment]
Okay, closing this then.
