### ISSUE TITLE
MBAY_LT - 7172sbe-a.nc has bad time values

### ISSUE THREAD

**Issue by kwilcox** [USGS-CMG/usgs-cmg-portal#167]
http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MBAY_LT/7172sbe-a.nc.html

**Comment by kwilcox** [comment]
@emontgomery-usgs -----^

**Comment by emontgomery-usgs** [comment]
[image: Inline image 1]

This is from the CF version on geoport.  It appears to have the expected
times and dates.  Please be more specific about what's wrong.

Thanks! Ellyn

On Fri, Feb 19, 2016 at 3:10 PM, Kyle Wilcox <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs> -----^
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/167#issuecomment-186383754>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
The raw data contains this at the beginning of the `time` variable

```
time[32539]
1, 2, 2, 538968064, 1870135296, 1, 620756992, 62, 1105812521, 7, 1936028265, 842347264, 0, 1, 1, ...
```

This is in the raw data, not CF data.  The raw data will need to be fixed (it is causing downstream issues).

**Comment by emontgomery-usgs** [comment]
OK- I see the 1st 14 points are bad.  I will  get a corrected version back
up there.

Thanks!

On Fri, Feb 19, 2016 at 3:40 PM, Kyle Wilcox <notifications@github.com>
wrote:

> The raw data contains this at the beginning of the time variable
>
> time[32539]
> 1, 2, 2, 538968064, 1870135296, 1, 620756992, 62, 1105812521, 7, 1936028265, 842347264, 0, 1, 1, ...
>
> This is in the raw data, not CF data. The raw data will need to be fixed
> (it is causing downstream issues).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/167#issuecomment-186396732>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by emontgomery-usgs** [comment]
This appears to have been a data corruption issue.  The original file on
stellwagen has reasonable values in the first 15 points.  The file in
geoport's data has been replaced with the original.  Re-running collect.py
on the experiment now.  It's a big one so will take some time.

There's no way to just do an individual file now, is there?  Would be handy
for corrections like this.
Thanks!

On Mon, Feb 22, 2016 at 9:01 AM, Montgomery, Ellyn <emontgomery@usgs.gov>
wrote:

> OK- I see the 1st 14 points are bad.  I will  get a corrected version back
> up there.
>
> Thanks!
>
> On Fri, Feb 19, 2016 at 3:40 PM, Kyle Wilcox <notifications@github.com>
> wrote:
>
>> The raw data contains this at the beginning of the time variable
>>
>> time[32539]
>> 1, 2, 2, 538968064, 1870135296, 1, 620756992, 62, 1105812521, 7, 1936028265, 842347264, 0, 1, 1, ...
>>
>> This is in the raw data, not CF data. The raw data will need to be fixed
>> (it is causing downstream issues).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/167#issuecomment-186396732>
>> .
>>
>
>
>
> --
> Ellyn Montgomery, Oceanographer and Data Manager
> U.S. Geological Survey
> Woods Hole Coastal and Marine Science Center
> 384 Woods Hole Rd., Woods Hole, MA, 02543-1598
> (508) 457-2356
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
You can do individual file with the `-l` flag:

```
 -l [FILES [FILES ...]], --files [FILES [FILES ...]]
                        Specific files to process (optional).
```

Ex:

`python collect.py -p MBAY_LT -l 7172sbe-a.nc -f [input_folder] -o [ouptut_folder]`

**Comment by emontgomery-usgs** [comment]
good to know.  I'll add that to the wiki.

The re-run just finished, and the file in download now matches Data, and
the file in CF-1.6 was correct already, so I'm not going to replace that
one.

On Mon, Feb 22, 2016 at 9:44 AM, Kyle Wilcox <notifications@github.com>
wrote:

> You can do individual file with the -l flag:
>
>  -l [FILES [FILES ...]], --files [FILES [FILES ...]]
>                         Specific files to process (optional).
>
> Ex:
>
> python collect.py -p MBAY_LT -l 7172sbe-a.nc -f [input_folder] -o
> [ouptut_folder]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/167#issuecomment-187211531>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356
