### ISSUE TITLE
access method opendap only 1 dataset?

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#173]
Is there a problem with the algorithm for searching by  `access method = opendap`?  
http://cmgdata.usgsportals.net/#module-search?p=proj3857&b=google_hybrid&page=1&tagId=107&q=

Should be 12 datasets (or more), not 1, right?
![2016-02-27_7-58-38](https://cloud.githubusercontent.com/assets/1872600/13372963/380b693e-dd28-11e5-8caf-eb3ae00c9a1a.png)

**Comment by kwilcox** [comment]
@rsignell-usgs all set, please confirm!

**Comment by rsignell-usgs** [comment]
Yep!
