### ISSUE TITLE
bad points in this air temperature data

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#174]
@emontgomery-usgs , can you check the bad air temperature points here?
![2016-02-27_8-04-29](https://cloud.githubusercontent.com/assets/1872600/13373002/8322f5b2-dd29-11e5-88fc-7db61917a05e.png)

Because we can't rescale the y axis due to https://github.com/USGS-CMG/usgs-cmg-portal/issues/108 not being solved yet, we can't see what the rest of the data looks like.

**Comment by jcwarner-usgs** [comment]
we should be able to rescale the axis to view the data.

**Comment by emontgomery-usgs** [comment]
The most obvious thing about the plot is that the dates for Mooring ID 440
should not be in 2005. If you look here, you can see that data should have
been from 1994: http://stellwagen.er.usgs.gov/mbay_lt-a.html.

Would you please let me know which of the 440* files is causing the problem?

Thanks!

On Sun, Feb 28, 2016 at 3:46 PM, jcwarner-usgs <notifications@github.com>
wrote:

> we should be able to rescale the axis to view the data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/174#issuecomment-189943146>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
When I click "parameter info", I get this.   Is this sufficient?
![2016-02-29_8-43-27](https://cloud.githubusercontent.com/assets/1872600/13396101/c33783fa-dec0-11e5-81b4-7f19b9b5756c.png)

**Comment by emontgomery-usgs** [comment]
Yes, that helped. The data is from 44013*- this is NDBC buoy data that was
published with our observations for convenience.  Probably shouldn't be
included in the portal...  But, it plots OK in ncBrowse, and appears to
have the correct FillValue info.

If we choose to not use it, in the file selection rule there should be a
check to ignore names with more than 4 initial numeric characters, unless
the first character is 9 or 1.

Our data has these names 99110ecn.nc (site 991, instrument 10) and
10023mc.nc (site 1002, instrument 3), but won't have anything starting with
2-8 as the 1st character that has 5 numeric chars. (should have 3 or 4).
In future, there will be file names starting with 1 that have 6 numeric
characters (103611adv, where site is 1035, instrument number 11).

Digging more into why 44013may05.nc shows spikes.

On Mon, Feb 29, 2016 at 8:45 AM, Rich Signell <notifications@github.com>
wrote:

> When I click "parameter info", I get this. Is this sufficient?
> [image: 2016-02-29_8-43-27]
> <https://cloud.githubusercontent.com/assets/1872600/13396101/c33783fa-dec0-11e5-81b4-7f19b9b5756c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/174#issuecomment-190217192>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by emontgomery-usgs** [comment]
Sorry, but I don't find a source of the spikes in 44013may05.nc.  The max
of air temp (AT_21) is 22.1 for both the stellwagen and the CF version.
There are 6 instances of fill value, that are correctly replaced by NaN
with ncread in Matlab.  Given the number of spikes, it looks like for some
reason, the portal is not treating the fill values correctly in this file.
Here's the ncdump output for that variable, and the _FillValue seems
correct.

[image: Inline image 1]

On Mon, Feb 29, 2016 at 9:00 AM, Montgomery, Ellyn <emontgomery@usgs.gov>
wrote:

> Yes, that helped. The data is from 44013*- this is NDBC buoy data that was
> published with our observations for convenience.  Probably shouldn't be
> included in the portal...  But, it plots OK in ncBrowse, and appears to
> have the correct FillValue info.
>
> If we choose to not use it, in the file selection rule there should be a
> check to ignore names with more than 4 initial numeric characters, unless
> the first character is 9 or 1.
>
> Our data has these names 99110ecn.nc (site 991, instrument 10) and
> 10023mc.nc (site 1002, instrument 3), but won't have anything starting
> with 2-8 as the 1st character that has 5 numeric chars. (should have 3 or
> 4).  In future, there will be file names starting with 1 that have 6
> numeric characters (103611adv, where site is 1035, instrument number 11).
>
> Digging more into why 44013may05.nc shows spikes.
>
> On Mon, Feb 29, 2016 at 8:45 AM, Rich Signell <notifications@github.com>
> wrote:
>
>> When I click "parameter info", I get this. Is this sufficient?
>> [image: 2016-02-29_8-43-27]
>> <https://cloud.githubusercontent.com/assets/1872600/13396101/c33783fa-dec0-11e5-81b4-7f19b9b5756c.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/174#issuecomment-190217192>
>> .
>>
>
>
>
> --
> Ellyn Montgomery, Oceanographer and Data Manager
> U.S. Geological Survey
> Woods Hole Coastal and Marine Science Center
> 384 Woods Hole Rd., Woods Hole, MA, 02543-1598
> (508) 457-2356
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
I've removed the NDBC datafiles buoy from the dataset

**Comment by emontgomery-usgs** [comment]
Since Kyle removed the dataset, I'm closing the issue
