### ISSUE TITLE
What are the GIS Service (WFS/ESRI REST) capabilities of the portal?

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#176]
@nganju-usgs reports there is interest in more synergy between the oceanographic portal
http://cmgdata.usgsportals.net/
and the CIDA-developed (aka Office-of-Water-Information-developed) "Coastal Hazards Change Portal"
http://marine.usgs.gov/coastalchangehazardsportal/

One synergistic step would be displaying CHCP GIS layers in the oceanographic portal. 

What are the capabilities of the oceanographic portal in displaying GIS layers. 

If we had ESRI REST or WFS endpoints in our CSW catalog, could the portal consume and display them?

**Comment by rsignell-usgs** [comment]
The WFS endpoints we would be most interested in accessing would come from USGS ScienceBase geoserver endpoints:

An example of accessing one of these WFS endpoints is here:
https://github.com/rsignell-usgs/notebook/blob/master/WFS/WFS_plot_in_Cartopy.ipynb

**Comment by shane-axiom** [comment]
We can definitely do external WMS/WFS...definitely not ESRI REST.

**Comment by zdefne-usgs** [comment]
@shane-axiom Is it possible to conserve the display style (e.g. color scheme, legends?) while bring in the layers from WMS?

**Comment by rsignell-usgs** [comment]
@zdefne-usgs, can you be a little more specific?   Do you mean controlling styling of WMS from the client side instead of selecting a style advertised in the `getCapabilities`?    Or do you mean styling for WFS?   Perhaps stop by my office for a chat about this?

**Comment by zdefne-usgs** [comment]
I have uploaded a .lyr file for styling the existing shapefile Barnegat Bay ESAs at 
https://www.sciencebase.gov/catalog/item/5342c54be4b0aa151574a8dc
We would like the users to see the data layer with the same style on the port (screenshots attached below)
 
![esas](https://cloud.githubusercontent.com/assets/4505315/17179990/fd6ad32c-53e8-11e6-9b7b-3c9ee1ca62b4.png) ![esas_legend](https://cloud.githubusercontent.com/assets/4505315/17180103/499c9e4c-53e9-11e6-9b85-4dec210e0e82.png)

**Comment by rsignell-usgs** [comment]
@kwilcox who is the right guy at Axiom to answer this question?

**Comment by shane-axiom** [comment]
@rsignell-usgs @zdefne-usgs Sorry, missed this reply.

If we're accessing a remote (to us) WMS service and the service is set up with a default style then we'll use that style. If we're provided with GIS data (shapefiles, etc) and expected to host data internally then we'd need to be provided with an SLD as well.

**Comment by rsignell-usgs** [comment]
@zdefne-usgs, okay so it seems like your job is to find out whether the WMS endpoint on your ScienceBase item 
https://www.sciencebase.gov/catalog/item/5342c54be4b0aa151574a8dc
can deliver the styling you want.   Can you contact them to find out?

**Comment by zdefne-usgs** [comment]
I have updated the item to include the styling. We now have the link to the new item:
https://www.sciencebase.gov/catalog/item/57ab7ea1e4b05e859be1ae87
which offers a WMS service at 
https://www.sciencebase.gov/arcgis/services/Catalog/57ab7ea1e4b05e859be1ae87/MapServer/WMSServer?request=GetCapabilities&service=WMS
and a ArcGIS Mapping Service at 
https://www.sciencebase.gov/arcgis/rest/services/Catalog/57ab7ea1e4b05e859be1ae87/MapServer

ScienceBase automatically updated to reflect the changes:
![croppercapture 21](https://cloud.githubusercontent.com/assets/4505315/17568400/9b9baf48-5f11-11e6-9f19-07ba68639b24.png)

I can also add either of them to Terria successfully...

![croppercapture 19](https://cloud.githubusercontent.com/assets/4505315/17568430/b1aff79e-5f11-11e6-9b12-17a4a83a2d42.png)

**Comment by rsignell-usgs** [comment]
@zdefne-usgs , cool!    So @shane-axiom and @kwilcox, how should we handle these in the portal?
We could just add these datasets to our pycsw service, but how would we want to identify that these are GIS layers as opposed to model results?

**Comment by zdefne-usgs** [comment]
@rsignell-usgs ,@kwilcox: Is it possible to support SLD approach for layers that might not support styling (because layers are likely to come from different sources)? 
I have also attached below an SLD file as a second alternative. 

[BB_ESA_WGS84_SLD.zip](https://github.com/USGS-CMG/usgs-cmg-portal/files/413406/BB_ESA_WGS84_SLD.zip)

**Comment by kwilcox** [comment]
@zdefne-usgs We can support the SLD styles if they are implemented in ScienceBase as the default style. The WMS layer will automatically use that style and it will be reflected in the CMG portal. This issue was originally about WFS (vector) layers and I haven't seen a client side vector data SLD styling implementation. Do you have an example?

The URL you posted above is not working for me: https://www.sciencebase.gov/arcgis/services/Catalog/57ab7ea1e4b05e859be1ae87/MapServer/WMSServer?request=GetCapabilities&service=WMS (The requested URL cannot be displayed. If you entered the URL manually please check your spelling and try again.)

**Comment by zdefne-usgs** [comment]
@kwilcox The discussion has moved to a WMS from a WFS. I do not know if there is a special interest in using WFS. After all the layers will be used just for display purposes. No interaction with features required on the client side. 
The url is correct. I don't know why you are having an issue. Could it be a connection problem?

**Comment by rsignell-usgs** [comment]
@kwilcox it appears that we don't need the WFS after all, just the WMS representation will be fine for displaying the GIS layers that we want in the portal .   So do we need to create a new issue for how to differentiate WMS from GIS layers from WMS from Ocean models?

**Comment by zdefne-usgs** [comment]
@kwilcox In case the other link still doesn't work for you, I have another WMS for a GIS layer that you can try. This one shows delineation marsh complex in Edwin B. Forsythe Wildlife Refuge. 
https://www.sciencebase.gov/arcgis/services/Catalog/5798c696e4b0589fa1c728a5/MapServer/WMSServer?request=GetCapabilities&service=WMS

![croppercapture 23](https://cloud.githubusercontent.com/assets/4505315/17984847/1a63c2f4-6ae1-11e6-9ff1-83e29297e492.png)

**Comment by rsignell-usgs** [comment]
@shane-axiom and @kwilcox , we have added a GIS record with a WMS layer to our CMG catalog with "CMG_Portal" as project.  See if you can find it!   The title is "Hurricane Sandy: 2013 NWI Data of Selected USFWS Wildlife Refuges along New Jersey and Long Island, New York."

**Comment by kwilcox** [comment]
We can add this to the catalog/portal system manually and call it done but I'd rather automate the harvesting of Static GIS WMS assets from your catalog so this will be "hands off" in the future.

This is set to be automated... at some point.

**Comment by rsignell-usgs** [comment]
So we will continue to add these GIS layers to our catalog, and you will find them when you search for `CMG_Portal` along with the modeling datasets.   Do you have a way to distinguish them so you can make a list of the GIS datasets on your end?

And once you have this list, you will manually add the GIS layers (with WMS endpoints)  to the portal, until you figure out a way to do this programmatically?

@kwilcox, is that about right?

**Comment by kwilcox** [comment]
Sounds good. We will manually add until its automated.

**Comment by rsignell-usgs** [comment]
So will use some simple logic on our end to divide the `CMG_Portal` records into models and GIS layers?  
In other words, we don't need to modify or add more attributes to distinguish them?

**Comment by kwilcox** [comment]
I think we can get away with assuming that if an entry in your catalog has a WMS endpoint and no DAP endpoint, it should be treated as a static GIS dataset. That sound OK?

**Comment by rsignell-usgs** [comment]
Yep, that logic should work!

**Comment by kwilcox** [comment]
Manually added: http://cmgdata.usgsportals.net/#module-metadata/942d7a82-8992-4972-868e-5538a1c86cb5/dd3e7800-807c-44a4-9936-dfff3e13e654

**Comment by zdefne-usgs** [comment]
Thanks! @kwilcox and @rsignell-usgs 
We need to have an option to zoom to the data layer too Somehow it is missing for this layer...
![image](https://cloud.githubusercontent.com/assets/4505315/18677567/24c892b0-7f27-11e6-970e-920eac7b7f80.png)

**Comment by kwilcox** [comment]
Good catch! That is a side-effect of manually adding the layer... we didn't calculate the bounding box.  @shane-axiom finished some preliminary work on WMS server harvesting a few weeks ago and the ball is now in my court. Once I start it should take me about two days to automate all of the WMS endpoints from your CSW.

**Comment by zdefne-usgs** [comment]
Just wanted to remind that "Zoom to layer" is still missing and the map still zooms to entire U.S. by default.

Also is it easy for Axiom to pull out one of the two layers in a WMS? For example the following WMS has two layers; muMeanTidalRangeEBFNWR and mn_idw_mu.tif:
https://www.sciencebase.gov/arcgis/services/Catalog/580667dbe4b0824b2d1d3e92/MapServer/WMSServer?request=GetCapabilities&service=WMS

**Comment by shane-axiom** [comment]
@zdefne-usgs Currently we just pull in all of the layers offered by the WMS, but we could pretty easily add the ability to blacklist layers.

**Comment by rsignell-usgs** [comment]
closing because we are successfully displaying WMS in the portal
