### ISSUE TITLE
No DAP: USGS Chincoteague Bay Model for Hurricane Sandy

### ISSUE THREAD

**Issue by kwilcox** [USGS-CMG/usgs-cmg-portal#180]
@rsignell-usgs This dataset is no longer available:

http://geoport-dev.whoi.edu/thredds/clay/usgs/users/abeudin/chinco/Sandy/ext_dc20_nam/catalog.html?dataset=clay/usgs/users/abeudin/chinco/Sandy/ext_dc20_nam/00_dir_roms.ncml

**Comment by kwilcox** [comment]
Did its name change? http://cmgdata.usgsportals.net/#module-metadata/75ddbd78-eb67-3a24-a11b-06ea6800ab9e/16c6fe67-f9e0-4295-ab56-58c9e261b3c9

**Comment by rsignell-usgs** [comment]
@alexisbeudin , any insight here?
Did you perhaps remove the `00_dir_roms.ncml` file from this directory? 
http://geoport-dev.whoi.edu/thredds/clay/usgs/users/abeudin/chinco/Sandy/ext_dc20_nam/catalog.html

**Comment by alexisbeudin** [comment]
Yes, I did relocate the file 00_dir_roms.ncml (http://geoport.whoi.edu/thredds/dodsC/clay/usgs/users/abeudin/chinco/Sandy/withbedload/00_dir_roms.ncml) as I have updated my Sandy run (now it has bedload)

@rsignell-usgs should have I done differently?



----- Mail original -----
De: "Rich Signell" <notifications@github.com>
À: "USGS-CMG/usgs-cmg-portal" <usgs-cmg-portal@noreply.github.com>
Cc: "Alexis Beudin" <alexis.beudin@free.fr>
Envoyé: Lundi 21 Mars 2016 16:17:50
Objet: Re: [usgs-cmg-portal] No DAP: USGS Chincoteague Bay Model for Hurricane Sandy (#180)



@alexisbeudin , any insight here? 
Did you perhaps remove the 00_dir_roms.ncml file from this directory? 
http://geoport-dev.whoi.edu/thredds/clay/usgs/users/abeudin/chinco/Sandy/ext_dc20_nam/catalog.html

**Comment by rsignell-usgs** [comment]
@alexisbeudin, it sounds like you *meant* for that run to be dropped, and a new one picked up, so you removed the 00_dir_roms.ncml from the old run and added one to the new run.    If this is correct, you did everything exactly right.

Perhaps @kwilcox needs to harvest our CSW again?

**Comment by rsignell-usgs** [comment]
@kwilcox , the only datasets in the portal should be the ones you discover via the CSW query currently having `CMG_Portal` in the project description.

**Comment by rsignell-usgs** [comment]
There should be 10 models:
```
USGS Barnegat Bay Model for Hurricane Sandy : run076
COAWST Hindcast:Barnegat Bay:ADCIRC tides,Real rivers,Plume,Lowpass Espresso bdry,NAM,new bathy
USGS Chincoteague Bay Model for Hurricane Sandy
USGS Chincoteague Bay Model for EPR
COAWST Forecast System : USGS : US East Coast and Gulf of Mexico (Experimental)
COAWST Hindcast:MVCO/CBlast 2007:ripples with SWAN-40m res
USGS-CMG-COAWST Model: Hurricane Sandy, NYB05 700m Nest
USGS-CMG-COAWST Model: Hurricane Sandy, SHF05 2km Nest
USGS-CMG-COAWST Model: Hurricane Sandy, USE27 6km Nest
ASGS NCFS Sandy Advisory 27
```

**Comment by kwilcox** [comment]
@rsignell-usgs Yes, but the DAP endpoint for the `USGS Chincoteague Bay Model for Hurricane Sandy` is pointing at is the old and 404'd URL. Your CSW needs to be updated, correct?

```
gov.usgs.cmg:USGS_CHINCO_SANDY
  * WWW:LINK - http://geoport-dev.whoi.edu/thredds/dodsC/clay/usgs/users/abeudin/chinco/Sandy/ext_dc20_nam/00_dir_roms.ncml.html
  * WWW:LINK - http://www.ncdc.noaa.gov/oa/wct/wct-jnlp-beta.php?singlefile=http://geoport-dev.whoi.edu/thredds/dodsC/clay/usgs/users/abeudin/chinco/Sandy/ext_dc20_nam/00_dir_roms.ncml
  * OPeNDAP:OPeNDAP - http://geoport-dev.whoi.edu/thredds/dodsC/clay/usgs/users/abeudin/chinco/Sandy/ext_dc20_nam/00_dir_roms.ncml
  * OGC:WMS - http://geoport-dev.whoi.edu/thredds/wms/clay/usgs/users/abeudin/chinco/Sandy/ext_dc20_nam/00_dir_roms.ncml?service=WMS&version=1.3.0&request=GetCapabilities
  * UNIDATA:NCSS - http://geoport-dev.whoi.edu/thredds/ncss/grid/clay/usgs/users/abeudin/chinco/Sandy/ext_dc20_nam/00_dir_roms.ncml/dataset.html
  * file - http://geoport-dev.whoi.edu/thredds/fileServer/clay/usgs/users/abeudin/chinco/Sandy/ext_dc20_nam/00_dir_roms.ncml
```

**Comment by rsignell-usgs** [comment]
@kwilcox, indeed the logical flaw was on my end -- I was not cleaning the ISO records before reharvesting.    Now the job that gets run every hour (at 20 min past the hour) is:
```
(ioos)usgs@gam:/opt/pycsw$ more /opt/pycsw/do_update
#!/bin/bash

WAF_TOPDIR='/usgs/data0/iso/iso_records'
PYCSW_CONFIG='/opt/pycsw/default.cfg'

# delete all the ISO record folders
rm -rf $WAF_TOPDIR/*

# delete all records from DB
#python /opt/pycsw/bin/pycsw-admin.py -c delete_records -f $PYCSW_CONFIG -y
sqlite3 /opt/pycsw/records.db 'delete from records'

# thredds crawler scripts use the custom IOOS Anaconda environment
source deactivate
source activate ioos
python /opt/pycsw/usgs-cmg-portal/catalog_harvest/get_daily_iso.py
python /opt/pycsw/usgs-cmg-portal/catalog_harvest/get_ncml_daily_iso.py

# pycsw uses the custom pycsw Anaconda environment
source deactivate
source activate pycsw

# load all records into DB
python /opt/pycsw/bin/pycsw-admin.py -c load_records -f $PYCSW_CONFIG -p $WAF_TOPDIR -r
```

**Comment by kwilcox** [comment]
OK to close?

**Comment by alexisbeudin** [comment]
yes

----- Mail original -----
De: "Kyle Wilcox" <notifications@github.com>
À: "USGS-CMG/usgs-cmg-portal" <usgs-cmg-portal@noreply.github.com>
Cc: "Alexis Beudin" <alexis.beudin@free.fr>
Envoyé: Mercredi 13 Avril 2016 10:10:57
Objet: Re: [USGS-CMG/usgs-cmg-portal] No DAP: USGS Chincoteague Bay Model for Hurricane Sandy (#180)



OK to close?
