### ISSUE TITLE
New experiment ready for ingest

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#187]
http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/CALCSTWET/catalog.html

Thanks!

**Comment by rsignell-usgs** [comment]
@kwilcox do you need to be alerted when new time series data are ready to be ingested, or do you have something that automatically checks now?

**Comment by emontgomery-usgs** [comment]
ping @kwilcox

**Comment by emontgomery-usgs** [comment]
@kwilcox @rsignell-usgs 

Since I haven't heard to the contrary, I'll keep letting you know when new or updated files are available.
There were slight position errors in some files in MYRTLEBEACH.  I fixed them and re-made the CF version.  Please add MYRTLEBEACH to the list of things that need to go onto the portal. Thanks!

**Comment by kwilcox** [comment]
I'm working with @rsignell-usgs to get the CF-1.6 THREDDS catalog added to the CSW server that powers the CMG portal. Right now it is a separate process that is constantly checking for new CF-1.6 data but that won't work in the long run!

**Comment by emontgomery-usgs** [comment]
@kwilcox  please add CHINCOTEAGUE to the list of experiments awaiting ingest.

**Comment by emontgomery-usgs** [comment]
CLosed-  moved to tickets 198, 199, 200 per RPS request
