### ISSUE TITLE
Color range control not working

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#188]
While making some slides for presentation & demo of the portal tomorrow, I noticed that several controls on layers seem not to be working the way they used to:
http://cmgdata.usgsportals.net/#map?p=proj3857&b=google_hybrid&page=1&tagId=107&q=&lg=d6be53c0-9e4c-419e-8d81-77b463822e44&z=10&ll=39.79358%2C-74.22003

I added temperature from Barnegat Bay run76 to the portal, and wanted to change the range from 0-15 C.  

The first problem was when I changes units from English to metric, nothing happens to the portal display.  Didn't it used to change instantly?   
I worked around this by removing the layer, then adding it again, and then it showed up in metric units. 

But the bigger issue is that I was no longer to set the limits of the color range.   What happened to the controls?   

The `Auto-set for data in view` button isn't working either.   Help!
![2016-04-13_7-22-59](https://cloud.githubusercontent.com/assets/1872600/14491771/d34057b8-0148-11e6-98b4-8bc2bb3dc413.png)

**Comment by kwilcox** [comment]
This seems to be a bug on our side (unheard of!) when converting units. We'll get this fixed asap.

**Comment by kwilcox** [comment]
I take that back, the dataset you host has a typo in the "units" attribute.

`units: degree_Celcius`

Spell **Celsius** correctly and it should fix itself in a few hours.

**Comment by rsignell-usgs** [comment]
@kwilcox , I modified the `NcML` to change the units to `degree_Celsius`, and now the display in metric units looks fine.   But english units are now off:
![2016-04-14_6-13-54](https://cloud.githubusercontent.com/assets/1872600/14530242/1a0ea676-0226-11e6-95e2-f44da8ba039b.jpg)
