### ISSUE TITLE
More functionality found broken this morning...

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#189]
I tried to get the OPeNDAP link for a layer and discovered none of the buttons at the bottom of the icons are working.

http://cmgdata.usgsportals.net/#module-metadata/0d0bc16b-90f0-3976-ae4a-9906a750497e/d6be53c0-9e4c-419e-8d81-77b463822e44

![2016-04-13_7-33-38](https://cloud.githubusercontent.com/assets/1872600/14492303/7387b376-014c-11e6-9f81-07e05cebbf3f.png)

**Comment by kwilcox** [comment]
Those buttons have never been download links, the Download drop down is a bit further down the page and allows you to access the DAP page.

![selection_128](https://cloud.githubusercontent.com/assets/13939/14495376/34346ed8-015d-11e6-951f-3c17f46e645e.png)
