### ISSUE TITLE
Error retrieving data for some variables in oceanographic time-series database

### ISSUE THREAD

**Issue by dnowacki-usgs** [USGS-CMG/usgs-cmg-portal#190]
Potentially related to #137 but this is for mooring data and not model output, AND there is an additional wrinkle (see below):

To reproduce, go to Oceanographic Time-Series Measurement Database. Zoom to Mobile Bay, AL, click on MOBILE_BAY 395 (urn:ioos:sensor:gov.usgs.cmgp:mobile_bay_395), get error "Error retrieving data":

<img width="540" alt="screen shot 2016-04-15 at 09 59 03" src="https://cloud.githubusercontent.com/assets/13837821/14563597/b6e6e7ea-02f0-11e6-9a78-638523d8bd1b.png">

Click over to "Sea Water Pressure" and data is plotted:

<img width="483" alt="screen shot 2016-04-15 at 10 00 59" src="https://cloud.githubusercontent.com/assets/13837821/14563660/f9a1499a-02f0-11e6-83cd-88e359f20feb.png">

This "device" has a funky data description (time? standard deviation? depth?). Click dropdown to select Depth, and you get the same data plotted:

<img width="488" alt="screen shot 2016-04-15 at 10 02 27" src="https://cloud.githubusercontent.com/assets/13837821/14563694/2d268f1e-02f1-11e6-948f-ec525ef5e4a3.png">

Now click back to the original device, and garbage data (or something else than was originally plotted on this screen for the selected device) is plotted:

<img width="436" alt="screen shot 2016-04-15 at 10 03 33" src="https://cloud.githubusercontent.com/assets/13837821/14563723/568047b0-02f1-11e6-97b3-3a3a29adb659.png">

**Comment by emontgomery-usgs** [comment]
Nice find on this Dan.  It appears that the data aggregated in the portal is from two instruments, the TCT file having a structure that is unusual for our other data.  The conversion to CF doesn't know how to deal with the multiple depth dimensions used in this file, but doesn't fail.  Hopefully Kyle will enchance the conversion program to do the right thing in this case.
![image](https://cloud.githubusercontent.com/assets/1771422/14961259/c12a95fc-1066-11e6-987e-72f107778182.png)

**Comment by kwilcox** [comment]
1. Re: `Water Temperature`, please try again, working now.

2. Re: `Sea Water Pressure`, please try again, I can't reproduce the issue you were having.

3. Re: `Cell methods: time: standard deviation, Depth: 3(m)`, this is a CF standard way of representing data that has had a method applied to it (in this case, `standard_deviation` over `time`).  The title that is listed in the `Select device` dropdown is a bit overwhelming and we should look into simplifying that, but it is imporant to retain the `cell_methods` information. Clicking the `Parameter info` link gives even more detail at the exact device you are plotting. 

4. Re: Garbage values, these are the actual values in the source file:

    ```
    psdev = 3.494924e+07, 3.494924e+07, 3.494924e+07, 3.494924e+07, 
        3.494924e+07, 3.494924e+07, 0.02026271, 0.02119996, 0.02154978, 
        0.02105717, 0.01981198, 3.494924e+07, 3.494924e+07, 3.494924e+07, 
        3.494924e+07, 3.494924e+07, 3.494924e+07, 3.494924e+07, 0.01907934, 
        0.01846172, 0.01438317, 0.01769853, 0.01676128, 3.494924e+07, 
        3.494924e+07, 3.494924e+07, 3.494924e+07, 3.494924e+07, 3.494924e+07,
    ...
    ```

**Comment by emontgomery-usgs** [comment]
Way much better.  Temperature, cond and pressure plot fine now.

Unfortunately, in some of the old data, there will be garbage in some variables (as we have already found :>).  I suggest for the near-term, we do some curation of the data, and either check computed things like psd before plotting, or don't plot them at all.  I will fix these problems as we find them, but it may not happen in a timely way.

**Comment by dnowacki-usgs** [comment]
Thanks, looks like the issues that can be easily corrected have been with the recent fixes. Closing.
