### ISSUE TITLE
Why not just one Real-time dataset for US

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#191]
Right now we have West Coast real-time and East Coast real-time that ends at the VA/NC border.  So no southeast US and no gulf of mexico.  Also no Alaska or HI.   

Could we just have just one real-time dataset for all of US?

The USGS CMG program is a nationwide, US Government Program (with sister offices in Woods Hole, MA, Santa Cruz, CA and St. Petersburg, FL). 

![2016-04-15_10-41-41](https://cloud.githubusercontent.com/assets/1872600/14564979/e133e740-02f6-11e6-8782-d27aee5e3bce.jpg)

**Comment by kwilcox** [comment]
Would you like to replace the current layers (East and West) with the national map, or add an additional national map layer?

**Comment by dnowacki-usgs** [comment]
I think a single national map layer to replace the existing east/west segregation (which seems arbitrary, imho) makes the most sense.

**Comment by rsignell-usgs** [comment]
:+1:

**Comment by kwilcox** [comment]
You got it, will update when done

**Comment by kwilcox** [comment]
Can you create a WKT POLYGON of the area you would like to see stations from?

http://arthur-e.github.io/Wicket/sandbox-gmaps3.html

Try this polygon for starters and edit as needed:

POLYGON((-140.44921875 72.08405315425081,-156.796875 72.51162964623458,-166.11328125 69.85097815902499,-170.33203125 65.38057083630746,-168.92578125 58.09529960778157,-161.19140625 55.19768334019968,-155.390625 53.24549522839598,-167.34375 23.433009077420344,-167.51953125 12.415118585006395,-152.9296875 10.34734393012535,-141.85546875 14.636738848907621,-143.0859375 26.303264239389538,-130.60546875 31.83089906339438,-119.8828125 33.165145408240285,-117.0703125 28.178559849396976,-100.1953125 22.299261499741213,-92.63671875 15.82396602717367,-82.79296875 16.161920953785344,-62.2265625 16.667768661240753,-62.2265625 24.87646991083154,-70.3125 30.021543509740027,-63.10546875 40.33817045213394,-59.4140625 47.42065432071321,-63.28125 52.50284765940397,-124.1015625 51.31001339554934,-137.8125 60.60314950746827,-140.2734375 70.97044655781411,-140.44921875 72.08405315425081))

**Comment by kwilcox** [comment]
I went ahead and implemented the above polygon, reopen if you want to change it!

realtime: http://cmgdata.usgsportals.net/#module-metadata/15ea5fb6-fd04-40d1-b1d2-093e139e0b27/bc2d9464-0fb1-4b08-9db8-3b5d3c5fcfd8

historical: http://cmgdata.usgsportals.net/#module-metadata/81c8a39d-6f40-401b-9cec-3b695bdd14fe/26961fc8-8675-4380-b63c-12628832e5ff
