### ISSUE TITLE
bed_thickness is not displayed

### ISSUE THREAD

**Issue by alexisbeudin** [USGS-CMG/usgs-cmg-portal#195]
sediment bed layer thickness (variable bed_thickness in ncml) is not displayed in the portal for Chincoteague Bay during Hurricane Sandy while:

<variable name="bed_thickness">
  <attribute name="grid" type="String" value="grid"/>
  <attribute name="display" type="String" value="True"/>
  <attribute name="content_coverage_type" type="String" value="modelResult"/>
  <attribute name="location" type="String" value="face"/>
</variable>

**Comment by rsignell-usgs** [comment]
@alexisbeudin , can you provide the URL?

**Comment by alexisbeudin** [comment]
@rsignell-usgs http://geoport.whoi.edu/thredds/dodsC/clay/usgs/users/abeudin/chinco/Sandy/master/00_dir_roms.ncml

**Comment by rsignell-usgs** [comment]
Closing this, as application of the latest yaml2ncml will allow bed_elevation and other variables with an `Nbed` dimension to display in ncWMS.
