### ISSUE TITLE
dwave data conversion question in collect.py

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#197]
In the dws-a.nc files, we have wave height and wave period dimensioned as (time, lat, lon), and a variable containing spectra called pspec that is dimensioned as (time, frequency).

Because the name is not of a type that should be ignored, the file is converted, and produces one file containing the timeseries of wave height and period, and one containing the bursts of pressure spectra.

The portal isn't going to know how to handle the spectra properly.  We don't convert other files that contain the various wave spectra, so perhaps we also need to have logic that won't make files that just contain variables of certain names or dimensions?

Here is an example from CHINCOTEAGUE:
 on stellwagen	                         on geoport in CF-1.6	     comments
10271Aaqd-a.nc	                 10271Aaqd-a.nc	           converted correctly
10271Aaqdwvs_diwasp-cal.nc no file	                        should not be converted
10271Aaqdwvsb-cal.nc	         no file	                             "
10273Adws-a.nc	                 10273Adws-a.nc	         just has pspec var
                         	                 10273Adws-a_z1.nc	 has wv_ht, period

Thanks!

**Comment by kwilcox** [comment]
The`pspec` variable will be ignored in the portal because it has no `epic_code` or `standard_name`. Is that enough or would you not even want the CF file to be created?

**Comment by emontgomery-usgs** [comment]
Sounds like the existing logic covers it.  Thanks!  As long as it doesn't show up in the portal and NOT get displayed...
