### ISSUE TITLE
please ingest data from CALCSTWET experiment

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#198]
http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/CALCSTWET/catalog.html

From ticket 187

**Comment by kwilcox** [comment]
@emontgomery-usgs `9831HRaqdb-a.nc` is in a different format than data we have seen. The time variables are dimensioned by `time` and `profile`.

**Comment by emontgomery-usgs** [comment]
@kwilcox, shoot!  it's a burst file that's normally excluded by having 'b-cal' in the name.  It slipped through with a '-a nc" instead.  I will change the name of this one, but maybe it's time to change the exclusion logic to check the dimensions instead of the file name.

Uh oh, I just realized you're still working from DATA, not the CF-1.6 version I make.  Is there any reason I should continue to do the conversion to http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/CALCSTWET/catalog.html, if you're going to re do it?  Note, there is no 9831HRaqdb-a.nc in teh CF-1.6 I made.

**Comment by kwilcox** [comment]
I've been running from `Data` for new datasets just to check for things like this. I usually run from `CF` for already established datasets!

**Comment by emontgomery-usgs** [comment]
Well, I don't ask you to ingest until I've done the CF conversion, so we're duplicating each other's efforts.

**Comment by kwilcox** [comment]
all set

![selection_159](https://cloud.githubusercontent.com/assets/13939/15148551/a9f4343c-1693-11e6-9507-1e98d1031452.png)

**Comment by emontgomery-usgs** [comment]
Perfect!
