### ISSUE TITLE
please re-harvest MYRTLEBEACH experiment to capture updated files 

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#199]
http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/MYRTLEBEACH/catalog.html
From ticket 187

**Comment by kwilcox** [comment]
all set

**Comment by emontgomery-usgs** [comment]
Awesome!  Note the timeslider issue with starting too early and ending too late is solved!  Yippee!
@rsignell-usgs
