### ISSUE TITLE
Please ingest files from CHINCOTEAGUE experiment

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#200]
http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/CHINCOTEAGUE/catalog.html
from ticket 187

**Comment by kwilcox** [comment]
This experiment has quite a few datafiles which seem to be lettered incrementally, for example:

```
10201Aecp-a.nc
10201Becp-a.nc
10201Cecp-a.nc
10201Decp-a.nc
```

```
10211Aalt-a.nc
10211Balt-a.nc
10211Calt-a.nc
```

They appear to be sensor swaps? The time window between each file is only a few days. Should these be combined into a single time-series, or left with the lettered identification?  If they should be combined, we haven't come across this before and I'll need to implement something to recognize types of files like this.

**Comment by emontgomery-usgs** [comment]
it is usually the same sensor deployed sequentially, but in some cases the sensors were changed or removed.  A temporal aggregation would be fine, but it might also be reasonable to keep the granularity, so the actual source file can be identified.

This is similar to RCNWR (in S. Maine, 952-955) http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/RCNWR/catalog.html, but there I had already made temporal aggregations with the _all in the names.  I just checked and the right thing didn't happen there either.  It appears that the portal is trying to plot the "A" ,"B "and "all" as different depths, though the times aren't the same and the depths (nominally) are.
![image](https://cloud.githubusercontent.com/assets/1771422/15082017/9f8377e0-1393-11e6-951b-4b4bbccb6dc7.png)

**Comment by kwilcox** [comment]
It seems to be interpreting the depths correctly (they are all 0.5m). The select box is titled "Select Device", which is how we are distinguishing between the different time-series. If you are OK with A, B, and C being separate "devices", I'll add them now. You can also combine them into an `_all` file and A, B, C, and all will be available in the downdown.

**Comment by emontgomery-usgs** [comment]
Well, they're logically not separate devices, in terms of continuity.  Often to get the temporal resolution we want, a deployment has to get done as N parts, in order to re-battery between the sections.  One set of batteries would not last the entire duration.  I guess we can keep this for now (at least it displays things), but keep improving it on the backburner.  

For RCNWR, I'd rather you display just the *_all.nc files, since that's what we're really wanting to show.

Best for future would be to have some logic that says if a capital letter follows the 4 or 5 digit mooring number, then look for other files to temporally concatenate with it.

**Comment by kwilcox** [comment]
All set

![selection_158](https://cloud.githubusercontent.com/assets/13939/15148498/7e52b5a6-1693-11e6-99be-0086446bae9f.png)

**Comment by emontgomery-usgs** [comment]
Looks good, Thanks!
