### ISSUE TITLE
re-Harvest MONTEREY_CANYON experiment

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#201]
There are 4 corrected files from Feb2016 that will resolve the problem with the time slider ending in 2023, and the early start in 1965

http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/MONTEREY_CAN/catalog.html

**Comment by kwilcox** [comment]
All set

**Comment by emontgomery-usgs** [comment]
Thank you!  This is the one that had the goofy times that messed up the time slider.  Great!
