### ISSUE TITLE
time series measurement part of portal not working

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#203]
@kwilcox - when I checked the portal, it just sits with the whirling circle (in chrome v50x)- never displays site icons-
http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c

**Comment by kwilcox** [comment]
Working for me. Try to hard refresh (press ctrl+f5)?

![selection_154](https://cloud.githubusercontent.com/assets/13939/15118029/63eebd6a-15d8-11e6-877c-1a7dc52a8e86.png)

**Comment by emontgomery-usgs** [comment]
Thanks- that worked.

On Mon, May 9, 2016 at 11:23 AM, Kyle Wilcox <notifications@github.com>
wrote:

> Working for me. Try to hard refresh (press ctrl+f5)?
>
> [image: selection_154]
> <https://cloud.githubusercontent.com/assets/13939/15118029/63eebd6a-15d8-11e6-877c-1a7dc52a8e86.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/203#issuecomment-217896497>
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356
