### ISSUE TITLE
treatment of velocity observations, smoothing and computation of speed from u&v

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#208]
@kwilcox @rsignell-usgs 
There are some issues with what gets displayed for ADCP (multi-depth) velocity observations.
1) the curtain plot isn't accurately representing the data;  Here is the original plot of Northward velocity from http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/HUDSON_SVALLEY/catalog.html?dataset=usgs/data2/emontgomery/stellwagen/CF-1.6/HUDSON_SVALLEY/6041adc-a.nc
![image](https://cloud.githubusercontent.com/assets/1771422/15150647/125a2402-169c-11e6-81ef-7b5478f8ef7a.png)
Note the vertical striations go mostly from top to bottom, and there is missing data in the upper 20 meters in some parts of Jan through March.  The same thing as plotted in the portal doesn't show missing data, something bad happens below 30m and there are no endpoints on the color scale so I can't tell if the amplitudes are similar or elevated (probably due to whatever filtering is going on).

![image](https://cloud.githubusercontent.com/assets/1771422/15150915/2a653aa4-169d-11e6-9694-5feb7b1556f4.png)

2) current speed should never be less than 0, and the horizontal discontinuity at ~30 meters is wrong, but obviously comes from the u & v.  There are no current speed and direction variables in the original file, and I'm not sure we should add computed fields that aren't actually in the original file.
![image](https://cloud.githubusercontent.com/assets/1771422/15150560/b39e05e6-169b-11e6-9f8e-b8da7829cb5f.png)

**Comment by rsignell-usgs** [comment]
@kwilcox , as Ellyn discovered, there are indeed serious problems with this display type.  
http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c

We need to either fix or remove this "curtain plot" capability for Version 1.0. 

![2016-06-10_13-56-20](https://cloud.githubusercontent.com/assets/1872600/15973996/380232d6-2f14-11e6-82bd-1c764b7f572b.jpg)

**Comment by emontgomery-usgs** [comment]
@kwilcox, @rsignell-usgs 

In looking to see if this had been addressed (it hasn't), I found another example of the curtain plot misbehaving from north of Los Angeles.
![portal_bad_avg](https://cloud.githubusercontent.com/assets/1771422/16319322/d2f32d6c-3960-11e6-8779-83bc40562a1e.png)

Maybe curtain plots should be disabled until they represent what's there.

**Comment by rsignell-usgs** [comment]
The issue of the banding described here https://github.com/USGS-CMG/usgs-cmg-portal/issues/208#issuecomment-225253716 has been fixed in the "use-new-charts" version, but that version is still having trouble with the shallow ADCP with missing values at the surface:
![2016-07-19_11-13-15](https://cloud.githubusercontent.com/assets/1872600/16955371/4f39606c-4da2-11e6-9d4f-f8f47b7bea25.png)

It would be easier for you guys to reproduce these if we could search on a particular station (like "956").  Should I raise an issue for that?

**Comment by rsignell-usgs** [comment]
@akbstone

**Comment by kwilcox** [comment]
@rsignell-usgs Would your best guess be that we are not accounting for the fill values correctly? We should see "spikes"?

**Comment by kwilcox** [comment]
Looks like a fillvalue issue, ill touch base with @akbstone

**Comment by akbstone** [comment]
@rsignell-usgs, @emontgomery-usgs, @kwilcox 

Bad  tidal depth plots has been resolved on preview version:

http://cmgdata.usgsportals.net/?use_new_charts=true#map?p=proj3857&b=google_hybrid&page=1&tagId=&q=time+series&tags=&lg=6878f136-b61e-11e4-a8f5-00265529168c&z=13&ll=34.10889%2C-119.07034

![image](https://cloud.githubusercontent.com/assets/1093777/17376726/450c13d8-5963-11e6-81f9-27c3b065c746.png)

**Comment by emontgomery-usgs** [comment]
@akbstone , much improved!  Thanks!

Please scroll up in this thread to my 6/23 post and compare the current display there (the initial form of the data) with what's displayed in the portal.  It appears that there's still data displayed by the curtain plot in the portal where there should be the fill value.

**Comment by zdefne-usgs** [comment]
In addition to @emontgomery-usgs Ellyn's comment: The colorbar values are scrambled. Once you toggle the autoscale off and on they look much better.

**Comment by emontgomery-usgs** [comment]
@kwilcox was trying to check on our platform 956 to see how it looks in the "use_new_charts" version, and all the data from the CALCSTWET experiment isn't on the portal now.  Please investigate.  Thanks

**Comment by emontgomery-usgs** [comment]
I think this issue is resolved in the "use_new_charts=true" interface.  I checked both 956 from CALSCTWET and the original HUDSON_SVALLEY 504, and both look great.  Good job!
