### ISSUE TITLE
add a time-series to existing time-series plot

### ISSUE THREAD

**Issue by nganju-usgs** [USGS-CMG/usgs-cmg-portal#21]
Can we have the capability to add multiple time-series from a data/model location to an existing plot (over the same or overlapping time-period) so it's easier to compare multiple data sites or model locations?

**Comment by kwilcox** [comment]
Preview of functionality that was demoed yesterday, more to come!
![data-compare-flattened](https://cloud.githubusercontent.com/assets/13939/5846275/6e7048c0-a190-11e4-9ec2-5f5cc08c916b.gif)

**Comment by kwilcox** [comment]
Some greater functionality, implementation into the portal is coming soon!

http://www.axiomdatascience.com/maps/beta/graphing.php

**Comment by rsignell-usgs** [comment]
@kwilcox , now that some months have gone by, where are we with this functionality?  
Did it drop off the radar or are there roadblocks?

**Comment by kwilcox** [comment]
@rsignell-usgs we should be able to demo this in mid-September

**Comment by rsignell-usgs** [comment]
@kwilcox, okay.

**Comment by emontgomery-usgs** [comment]
This is done.  Great job!  See https://portal.aoos.org/help/overview.html#data-views
