### ISSUE TITLE
Need missing_value for this dataset

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#213]
@emontgomery-usgs, I clicked on sea surface height on this station and it's apparent that the missing_value should have been set to 0.   Can you fix?

http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c

![2016-06-21_13-49-13](https://cloud.githubusercontent.com/assets/1872600/16240892/3c809fd4-37b9-11e6-9c10-249a8b6c2cf9.jpg)

**Comment by emontgomery-usgs** [comment]
Not sure how an ADCP calculated hght_18.  It has a fill_value of 1e35.  I
suspect the computation inserted 0s when it should have done FIllValues.
Will put on my list.

On Tue, Jun 21, 2016 at 2:05 PM, Rich Signell <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs>, I clicked on sea
> surface height on this station and it's apparent that the missing_value
> should have been set to 0. Can you fix?
>
>
> http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c
>
> [image: 2016-06-21_13-49-13]
> <https://cloud.githubusercontent.com/assets/1872600/16240892/3c809fd4-37b9-11e6-9c10-249a8b6c2cf9.jpg>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/213>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ABsHnuHHo9MuGLdaz-tgV4cOezlvLupKks5qOCf7gaJpZM4I7A_q>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by emontgomery-usgs** [comment]
@kwilcox - the file has been replaced on geoport.  in CF-1.6/MYRTLEBEACH, ready for harvest.

**Comment by emontgomery-usgs** [comment]
@kwilcox, looks like the sea surface height data is still bad in the portal- did you re-harvest?

**Comment by kwilcox** [comment]
Looking good now locally, will update on the next push that includes new experiments

**Comment by emontgomery-usgs** [comment]
@kwilcox , trying to close open tickets, and this one doesn't seem to have been done.  Sea surface Height from 720 still drops to 0 in the portal view when it shouldn't.  The plot of data that's on geoport in the CF area looks correct.  Did you re-harvest and I still have something to fix with this file?  Thanks!

**Comment by rsignell-usgs** [comment]
Confirming here:
![2016-12-28_17-31-01](https://cloud.githubusercontent.com/assets/1872600/21532938/955a5cee-cd23-11e6-84f1-f39ad7689722.jpg)
@kwilcox, filter on `sea_surface_height`, go to myrtle beach region to see for yourself

**Comment by kwilcox** [comment]
This is all set, please close after confirming
![selection_261](https://cloud.githubusercontent.com/assets/13939/25390358/519b42ae-29a1-11e7-897e-c85920561107.png)

**Comment by emontgomery-usgs** [comment]
looks good now.  Thanks!
