### ISSUE TITLE
Why isn't all the data available for 859 displayed

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#219]
@kwilcox @rsignell-usgs @akbstone
In looking into ticket 108, I realized that only the seacat and ADCP data is displayed in the beta version of the portal (use_new_charts=true).  In the CF directory (http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/WFAL/catalog.html) there are 4 files containing data for this site.  There should be pressure data from the adcp (that isn't there even though the currents data from the file is), and there's pressure data in 8592pt that isn't displayed.  Wondering why, when the main version of the portal displays pressure data from both sensors for this site.

There is also  beam attenuation data in two of the files that isn't displayed on either portal version, but I think that's because that's a variable currently on the "don't display" list.

**Comment by rsignell-usgs** [comment]
Seems fixed.
