### ISSUE TITLE
map background image doesn't refresh after zoom

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#224]
@kwilcox 
Today in chrome and Firefox, when I  shift-click to zoom in on the time series data map to zoom in, the map background image is not re-drawn.  The image I get looks like this.
![image](https://cloud.githubusercontent.com/assets/1771422/17594469/7078dd26-5fb7-11e6-9700-b363fb57b463.png)

**Comment by rsignell-usgs** [comment]
I verified the problem on Firefox 47, 48 and Chrome 51.   Problem is therefore probably generic, right?  For me it happens not when I zoom, but as soon as I pan after a zoom.
![2016-08-11_12-40-40](https://cloud.githubusercontent.com/assets/1872600/17596868/5f832256-5fc1-11e6-823c-479978a72c77.jpg)

**Comment by emontgomery-usgs** [comment]
I just was in the portal again for another issue and the background DID refresh for two levels of zooming, but the third round (way in) it didn't refresh.  Is this related to tiling?

**Comment by emontgomery-usgs** [comment]
today it is refreshing the background fine, even at multiple zooms.
Closing issue
