### ISSUE TITLE
automate loading WMS endpoints from CSW

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#229]
We now have a handful of WMS layers in our catalog, and we would like to get the automated loading of WMS endpoints from CSW into the Portal working.  

Luckily, @kwilcox says it should only take a couple of days: https://github.com/USGS-CMG/usgs-cmg-portal/issues/176#issuecomment-248342073
:smiley_cat:

**Comment by kwilcox** [comment]
yup, @shane-axiom made some changed I needed months ago and I just need to get around to harvesting the WMS servers.

**Comment by rsignell-usgs** [comment]
Oh, I forgot one very important thing.  Our CSW endpoint has changed temporarily from 
http://geoport.whoi.edu/csw
to 
http://gamone.whoi.edu/csw

eventually (in a few months, likely) we will change it back.    This is because geoport is a CNAME that currently points to gam.whoi.edu, and gamone.whoi.edu is a machine that will replace gam.whoi.edu, using mostly docker containers.    We are not quite ready to switch the CNAME, but we are ready to start using the pycsw service on gamone.whoi.edu (in fact, the one on gam.whoi.edu=geoport.whoi.edu is no longer working).

**Comment by zdefne-usgs** [comment]
Hi @kwilcox, Is there any chance we can demonstrate these layers on the portal at our project meeting next week? We will have our program manager, regional director and science advisor attending the meeting. It would make good showcase for the direction we are heading.

**Comment by rsignell-usgs** [comment]
@kwilcox , this would be HUGE!
The Wetlands Synthesis Update Meeting is on 3pm wednesday.

**Comment by kwilcox** [comment]
@rsignell-usgs The WMS datasets aren't coming through with the correct reference scheme:

```
<dct:references scheme="WWW:LINK-1.0-http--link">https://www.sciencebase.gov/catalog/item/5798c696e4b0589fa1c728a5</dct:references><dct:references scheme="WWW:LINK-1.0-http--link">https://www.sciencebase.gov/arcgis/rest/services/Catalog/5798c696e4b0589fa1c728a5/MapServer</dct:references><dct:references scheme="OGC:WMS">https://www.sciencebase.gov/arcgis/services/Catalog/5798c696e4b0589fa1c728a5/MapServer/WMSServer?request=GetCapabilities&amp;service=WMS</dct:references><dct:references scheme="WWW:LINK-1.0-http--link">https://www.sciencebase.gov/catalog/file/get/5798c696e4b0589fa1c728a5</dct:references>
```

The schemes will need to be `<dct:references scheme="OGC:WMS">` like they are for the models. Can you update these easily?

**Comment by kwilcox** [comment]
Nevermine, I see a single `OGC:WMS` in there now that I formatted it better...

**Comment by zdefne-usgs** [comment]
@rsignell-usgs I have uploaded two more GIS metadata under gis_usgs_cmg folder. 
@kwilcox Any chance that the magic button to ingest them to the Portal is ready to push? :) Thanks!

**Comment by rsignell-usgs** [comment]
Unfortunately due to unresolved issues with ScienceBase WMS, the automated loading of GIS layers from our CSW catalog is not working yet. 

Is that about right, @kwilcox ?

**Comment by kwilcox** [comment]
Sort of. I'm manually adding them.

* http://cmgdata.usgsportals.net/#module-metadata/326b04bc-a68c-477c-a7fc-558d4cdf1895/097170b1-17f7-4e5a-b1f6-7f9837daa442

More to come...

**Comment by nganju-usgs** [comment]
typo there, "salt marsh" not "salt march"

**Comment by kwilcox** [comment]
Thanks @nganju-usgs, fixing.

Here is another: http://cmgdata.usgsportals.net/#module-metadata/a102697a-cb54-4da6-b4fd-9875061a1696/59a8a01b-9ef1-428b-95bb-75a4862f4efa

The ScienceBase WMS servers are periodically not responding so if you don't get an image try again in a few minutes.

**Comment by kwilcox** [comment]
Update: ScienceBase is still referencing a location that doesn't exist in its WMS GetCapabilities documents: `https://www.sciencebase.gov:443/catalogMaps/schemas/wms/1.1.1/WMS_MS_Capabilities.dtd`. Without the GetCapabilities documents being functional these ScienceBase datasets won't be able to be updated/added over CSW and will have to be manually added.
