### ISSUE TITLE
Icons have gone missing on home page!

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#235]
There used to be pictures under Hurricane Sandy, Model Output, Sensor Data:
![2016-12-15_11-39-21](https://cloud.githubusercontent.com/assets/1872600/21232868/2ad0f7e2-c2bb-11e6-80c3-e6537426a752.jpg)

The problem is that the image URLs do not return images, for example the 1st one is:
http://cmgdata.usgsportals.net/#module-search?p=proj3857&b=google_hybrid&page=1&tagId=&q=hurricane+sandy&tags=

**Comment by kwilcox** [comment]
fixed
