### ISSUE TITLE
can we make the "use_new_charts=true" version the default?

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#238]
@kwilcox @rsignell-usgs, this version of the portal is MUCH better for time-series data.  If it doesn't have major problems elsewhere, could you make this the view the default?
Thanks!

**Comment by rsignell-usgs** [comment]
:+1:

**Comment by rsignell-usgs** [comment]
In other words, we would like 
http://cmgdata.usgsportals.net
to give us the same results as:
http://cmgdata.usgsportals.net/?use_new_charts=true

and what is currently 
http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c

would show us
http://cmgdata.usgsportals.net/?use_new_charts=true#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c

**Comment by rsignell-usgs** [comment]
@nganju-usgs was just in my office again asking when we were going to be able to release version 1.0 of the portal.     

This would close the [last remaining issue](#108) for our 1.0 release milestone, which is 11 months overdue:
https://github.com/USGS-CMG/usgs-cmg-portal/milestone/1
![2017-01-19_10-56-51](https://cloud.githubusercontent.com/assets/1872600/22114304/fe344602-de36-11e6-9887-6febfc94dfbf.png)

**Comment by kwilcox** [comment]
@rsignell-usgs this is now the default!
