### ISSUE TITLE
shouldn't cdm_data_type be the same as featureType?

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#239]
@kwilcox, I was trying to load some of our CF-1.6 data into ERDDAP, and ERDDAP complained that `cdm_data_type` had an invalid value of "Station":
Ihttp://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/ECOHAB_I/4151sc-a.cdf.html

Can we just make sure that `cdm_data_type` has the same value as `featureType`, (for example, in this case "timeSeries")

**Comment by kwilcox** [comment]
Ugh. This attribute is testing my patience! I think we would be better off deleting it entirely. For now you could update it in the THREDDD catalog.xml or the ERDDAP datasets.xml.

There must have been a reason I set it to "Station"... Do they work in ToolsUI without it? Does the dataset work in ERDDAP without the attribute?

**Comment by rsignell-usgs** [comment]
Okay, it turns out that to get ERDDAP to work with our CF-1.6 converted datasets, we need to specify `cdm_data_type=TimeSeries` (for TimeSeries data).  

But that's not all.  

We also need to specify additional  attributes described here:
https://coastwatch.pfeg.noaa.gov/erddap/download/setupDatasetsXml.html
depending on the value of `cdm_data_type`.   

For example, for if we specify
`cdm_data_type=TimeSeries` 
we also need to specify 
`cdm_timeseries_variables`
which in my case was:
```
        <att name="cdm_data_type">TimeSeries</att>
        <att name="cdm_timeseries_variables">latitude,longitude,time,altitude,feature_type_instance</att>
```

From Bob's "working with datasets.xml" page above:

> The CDM is still evolving and may change again. ERDDAP complies with the Discrete Sampling Geometries (external link) chapter of the CF 1.6 (external link) metadata conventions (previously called the CF Point Observation Conventions).
> Either the dataset's global sourceAttributes or its global <addAttributes> MUST include the cdm_data_type attribute. A few dataset types (like EDDTableFromObis) will set this automatically.
> For EDDGrid datasets, the cdm_data_type options are Grid (the default and by far the most common type for EDDGrid datasets), MovingGrid, Other, Point, Profile, RadialSweep, TimeSeries, TimeSeriesProfile, Swath, Trajectory, and TrajectoryProfile. Currently, EDDGrid does not require that any related metadata be specified, nor does it check that the data matches the cdm_data_type. That will probably change in the near future.
> EDDTable uses cdm_data_type in a rigorous way. If a dataset doesn't comply with the cdm_data_type's requirements, the dataset will fail to load and will generate an error message. (That's a good thing, in the sense that the error message will tell you what is wrong so that you can fix it.)
> For all of these datasets, in the Conventions and Metadata_Conventions global attributes, please refer to CF-1.6 (not CF-1.0, 1.1, 1.2, 1.3, 1.4, or 1.5), since CF-1.6 is the first version to include the changes related to Discrete Sampling Geometry (DSG) conventions.
> 
> For EDDTable datasets, the cdm_data_type options (and related requirements) are
> 
> Point - for a dataset with unrelated points.
> As with all cdm_data_types other than Other, Point datasets MUST have longitude, latitude, and time variables.
> Profile - for data from multiple depths at one or more longitude,latitude locations.
> The dataset MUST include the globalAttribute cdm_profile_variables, where the value is a comma-separated list of the variables which have the information about each profile. Thus, for a given profile, the values of these variables will be constant.
> One of the variables MUST have the variable attribute cf_role=profile_id to identify the variable that uniquely identifies the profiles. If no other variable is suitable, consider using the time variable.
> TimeSeries - for data from a set of stations with fixed longitude,latitude(,altitude).
> The dataset MUST include the globalAttribute cdm_timeseries_variables, where the value is a comma-separated list of the variables which have the information about each station. Thus, for a given station, the values of these variables will be constant.
> One of the variables MUST have the variable attribute cf_role=timeseries_id to identify the variable that uniquely identifies the stations.
> It is okay if the longitude and latitude vary slightly over time. If the longitude and latitude don't vary, include them in the cdm_timeseries_variables. If they do vary, don't include them in the cdm_timeseries_variables.
> TimeSeriesProfile - for profiles from a set of stations.
> The dataset MUST include the globalAttribute cdm_timeseries_variables, where the value is a comma-separated list of the variables which have the information about each station. Thus, for a given station, the values of these variables will be constant.
> The dataset MUST include the globalAttribute cdm_profile_variables, where the value is a comma-separated list of the variables which have the information about each profile. Thus, for a given profile, the values of these variables will be constant.
> One of the variables MUST have the variable attribute cf_role=timeseries_id to identify the variable that uniquely identifies the stations.
> One of the variables MUST have the variable attribute cf_role=profile_id to identify the variable that uniquely identifies the profiles. (A given profile_id only has to be unique for a given timeseries_id.) If no other variable is suitable, consider using the time variable.
> Trajectory - for data from a set of longitude,latitude(,altitude) paths called trajectories.
> The dataset MUST include the globalAttribute cdm_trajectory_variables, where the value is a comma-separated list of the variables which have the information about each trajectory. Thus, for a given trajectory, the values of these variables will be constant.
> One of the variables MUST have the attribute cf_role=trajectory_id to identify the variable that uniquely identifies the trajectories.
> TrajectoryProfile - for profiles taken along trajectories.
> The dataset MUST include the globalAttribute cdm_trajectory_variables, where the value is a comma-separated list of the variables which have the information about each trajectory. Thus, for a given trajectory, the values of these variables will be constant.
> The dataset MUST include the globalAttribute cdm_profile_variables, where the value is a comma-separated list of the variables which have the information about each profile. Thus, for a given profile, the values of these variables will be constant.
> One of the variables MUST have the variable attribute cf_role=trajectory_id to identify the variable that uniquely identifies the trajectories.
> One of the variables MUST have the variable attribute cf_role=profile_id to identify the variable that uniquely identifies the profiles. (A given profile_id only has to be unique for a given trajectory_id.) If no other variable is suitable, consider using the time variable.
> Other - has no requirements. Use it if the dataset doesn't fit one of the other options.
> Related notes:
> All EDDTable datasets with a cdm_data_type other than "Other" MUST have longitude, latitude, and time variables.
> Datasets with profiles MUST have an altitude variable, a depth variable, or an cdm_altitude_proxy variable.
> If you can't make a dataset comply with all of the requirements for the ideal cdm_data_type, use "Point" (which has few requirements) or "Other" (which has no requirements) instead.
> This information is used by ERDDAP in various ways, for example, when making .ncCF files (.nc files which comply with the Contiguous Ragged Array Representations associated with the dataset's cdm_data_type, as defined in the newly ratified Discrete Sampling Geometries (external link) chapter of the CF 1.6 (external link) metadata conventions, which were previously named "CF Point Observation Conventions").
> Hint: Usually, a good starting point for subsetVariables is the combined values of the cdm_..._variables. For example, for TimeSeriesProfile, start with the cdm_timeseries_variables plus the cdm_profile_variables.
> 

(
