### ISSUE TITLE
model time series (virtualsensor.axds.co/getDataValues) broken at least for some datasets

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#243]
@zdefne-usgs  reported this to me that @nganju-usgs found that the "click on a model and get a time series" functionality is broken.

This is the screen we get - progress is stuck at "29":

![2017-02-22_15-20-37](https://cloud.githubusercontent.com/assets/1872600/23230653/ce9e2182-f912-11e6-8838-0ef9f1e1ba06.png)

the portal is trying to access:
https://virtualsensor.axds.co/getDataValues?method=GetSensorObservationsJSON&layer_uuid=310a1a8c-3658-4175-beb5-f41e31f82b58&lat=38.19386021138157&lon=-75.09999430538137&version=2&min_time_res=7200&start_time=1350259200&end_time=1352937600

which is not working.

**Comment by zdefne-usgs** [comment]
I diagnosed two different types:  #244

**Comment by kwilcox** [comment]
Closing in favor of https://github.com/USGS-CMG/usgs-cmg-portal/issues/244
