### ISSUE TITLE
Regenerate all CF files

### ISSUE THREAD

**Issue by kwilcox** [USGS-CMG/usgs-cmg-portal#247]
I've fixed a bunch of bugs that solve a bunch of outstanding issues:

* https://github.com/USGS-CMG/usgs-cmg-portal/issues/237
* https://github.com/USGS-CMG/usgs-cmg-portal/issues/213
* https://github.com/USGS-CMG/usgs-cmg-portal/issues/170
* https://github.com/USGS-CMG/usgs-cmg-portal/issues/241
* https://github.com/USGS-CMG/usgs-cmg-portal/issues/205

All of the CF files in http://geoport.whoi.edu/thredds/catalog/usgs/data2/emontgomery/stellwagen/CF-1.6/catalog.html should be regenerated again using an updated conda 3.5 environment!

**Comment by emontgomery-usgs** [comment]
@kwilcox, I thought you didn't use what I generated, and didn't actually get files from http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/ to ingest into the portal- am I mis-informed?  I will certainly re-run the conversion on all, if it doesn't duplicate your process.

**Comment by rsignell-usgs** [comment]
@emontgomery-usgs I have upgraded the CONVERT-WH conda environment on geoport.  Let me know if it works or has issues...

**Comment by kwilcox** [comment]
@emontgomery-usgs correct, I process from the Data folder still, but long term we want to have everything processing on your side and run through the CSW server. I should only be picking up that a file was updated on your end and making the changes on our end automatically.

**Comment by emontgomery-usgs** [comment]
Good to know.  In any case, the overnight run didn't crash, so all new files in CF-1.6.  Previous version moved to CF-1.6-pre0417, in case we find something toxic and need to revert.

**Comment by kwilcox** [comment]
They look good, I'll give them a go right now. 

Just curious, what did you use to generate the files? I put a helper script `generate.sh` into the repo that will generate a `run_cfexps.sh` file that includes all experiments. The previous script was getting out of date as new projects were added and this should solve that. Please note that the `run_cfexps.sh` file is no longer in the repo and you need to run `bash generate.sh` to create it before you want to generate the files!

**Comment by rsignell-usgs** [comment]
@emontgomery-usgs  please upgrade our [instructions on the wiki](https://github.com/USGS-CMG/usgs-cmg-portal/wiki/Procedure-to-update-time-series-data-from-CMG) to reflect these changes

**Comment by emontgomery-usgs** [comment]
Actually, Kyle already implemented a do-all feature in collect.py that's already in the wiki doc.  To re-download and convert all, I simply did what's in the 2nd grey box here : https://github.com/USGS-CMG/usgs-cmg-portal/wiki/collect.py-usage-hints-for-converting-time-series-observation-data.

So I did not use any of the scripts.  They're still useful for when you need to re-do a certain subset of experiments.

**Comment by kwilcox** [comment]
Great! Just making sure you understood why the `run_cfexps.sh` file was no longer there.
