### ISSUE TITLE
Develop CF convention for staggered grids

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#25]
idea:   what if we just added an attribute like: `[0 0 -1 0] `  for v variable, `[0 0 0 -1]` for u variable, with the knowledge that `[0 0 0 0]` is the center of the grid cell.    The user would need to specify the offsets for all dimensions, unlike the `coordinates` attribute that doesn't force the user to specify all the coordinates -- just those that can't be figured out some other way.    The beauty of this approach is that we don't need to specify the dimension order.    The user just specifies the correct offsets, no matter what the order.

**Comment by ocefpaf** [comment]
The link below has the "Deltares proposal for Staggered Grid data model (SGRID)" I am adding it here to keep track of things.

https://publicwiki.deltares.nl/display/NETCDF/Deltares+proposal+for+Staggered+Grid+data+model+(SGRID)

**Comment by ocefpaf** [comment]
> We should test it first in an ipython notebook.

http://nbviewer.ipython.org/gist/ocefpaf/78d409bdc6ea879b5dfd

@rsignell-usgs I am not sure if this is what you had in mind.  The proposed concept is tested only on ROMS staggered grid format (and it is probably wrong!) but it is a start...

**Comment by ocefpaf** [comment]
Two things to consider:

- The `sgrid` attribute alone, when reading a certain variable,  does not help to get that particular variable in a common grid.  We still need to know how the other variables are positioned (e.g.: if we know u we need v), and the shape of the "centered grid" for the averaging.  That makes the implementation of an automatic "common grid load" a little cumbersome.  Maybe this operation should always happen "offline."   (I am coming from iris, where each variable is loaded as an individual cube, maybe this is straight forward with another tool.)

- The `sgrid` attribute is an appealing concept.  But we can derive it using the variables dimensions.  By deriving it we avoid overloading the CF-conventions and remove the extra burden on data providers.

Here is an updated notebook to test that idea (using iris now):

http://nbviewer.ipython.org/gist/ocefpaf/bf67ba15efc5a8bbb4c0

**Comment by rsignell-usgs** [comment]
@ocefpaf,   if  u,v components are specified, or if `standard_name` is defined for the velocity components, the SGRID attributes will allow us to extract velocity data rotated and centered to grid cell centers in an unambiguous way.    I imagine us creating a routine like
```
ucr,vcr,lon,lat = kuvslice(url,uv=('u','v'),klevel=klevel,time=time)
```
where inputs `u` and `v` are velocity components and `ucr` and `vcr` are grid-centered, rotated velocities.  

I think that this requires:
* something like the `sgrid` attribute to specify the index notation relative to grid cell center.  We can derive this if we know it's ROMS, but not in general.  
* we need a `standard_name` for *grid_directed* u and v velocity components, so that we know we have to rotate. 
* We can't assume an `angle` variable, but that can be calculated based on the lon/lat locations of the u and v points.

**Comment by ocefpaf** [comment]
Having something like `kuvslice` is what I meant by "offiline."  IMHO `iris.load_cubes` should not do that automagically for the user.  (I had my head way too deep in iris lately :weary:)

> - something like the sgrid attribute to specify the index notation relative to grid cell center. We can derive this if we know it's ROMS, but not in general.

OK.  I am reading Bert's proposal now.  (And I need more staggered grids model data to play with.)

> - we need a standard_name for grid_directed u and v velocity components, so that we know we have to rotate.

Yes, scanning the file for `angle` variables is not a good logic to apply rotation automatically.  But I am not sure if a new standard name or something akin to "formula_terms" is the way to go?  Does that makes sense?

> - we can't assume an angle variable, but that can be calculated based on the lon/lat locations of the u and v points.

Aha, that is the missing piece I did not realize.  Thanks!  Working on that (to create a prototype for `kuvslice`), stay tuned...

**Comment by rsignell-usgs** [comment]
@ocefpaf, I know you have a lot of balls in the air right now, but did you have any further thoughts on this?    I was just gchatting with @brianmckenna and he was wondering whether we should start trying to build a `pysgrid` library around the [`SGRID` conventions draft](http://bit.ly/sgrid_cf) that @hrajagers created.

**Comment by ocefpaf** [comment]
No, sorry...  This got buried by my priority list at the moment.

> I was just gchatting with @brianmckenna and he was wondering whether we should start trying to build a pysgrid library around the SGRID conventions draft that @hrajagers created.

Sounds awesome!

**Comment by rsignell-usgs** [comment]
Rob @hetland, know anyone who might want to help with a `pysgrid` library that would support ROMS, Delft3D and other staggered grid models using Bert Jager's [`SGRID` conventions draft](http://bit.ly/sgrid_cf)?

**Comment by hetland** [comment]
What would the library entail? I guess what you mean is a way to read in such grids in a generic way. I think this would be useful, and I would help. The key would be to create an API that is intuitive and useful. The coding should then be relatively straightforward.

**Comment by rustychris** [comment]
Did anything come of this?  I'm starting to deal with some Delft data, and curious what the options are for representation and plotting.

**Comment by ocefpaf** [comment]
@ayan-usgs is developing the [pysgrid](https://github.com/sgrid/pysgrid) library and [here](http://nbviewer.ipython.org/github/sgrid/pysgrid/blob/master/pysgrid/notebook_examples/hudson_shelf_valley.ipynb) is a ROMS example.  We would love to see another example for Delft :wink:

**Comment by ayan-usgs** [comment]
@rustychris,

I have several other balls I'm trying to juggle right now, but I would be happy to help out with dealing with your Delft data. I would also be interested in any suggestions you may have regarding improvements to the [pysgrid](https://github.com/sgrid/pysgrid) or to the proposed sgrid conventions afterwards.

**Comment by rsignell-usgs** [comment]
We have some Delft3D data on THREDDS here:
http://comt.sura.org/thredds/catalog/comt_2_full/pr_inundation_tropical/NRL_Delft3D/Hurricane_Ike_2D_preliminary_run_1_without_waves/catalog.html?dataset=comt_2_full/pr_inundation_tropical/NRL_Delft3D/Hurricane_Ike_2D_preliminary_run_1_without_waves/00_dir.ncml
but it doesn't have the SGRID convention stuff in there yet.

Here's the [NcML file](http://comt.sura.org/thredds/fileServer/comt_2_full/pr_inundation_tropical/NRL_Delft3D/Hurricane_Ike_2D_preliminary_run_1_without_waves/00_dir.ncml) we used for the Delft3D data.

**Comment by hrajagers** [comment]
Rob told me that I should use GitHub more, so here I am checking what's going on. Do you still want Delft3D data on THREDDS that includes SGRID convention stuff? If yes, please let me know and I can help to create it.

**Comment by rsignell-usgs** [comment]
Oh, so you listen to @hetland but not me, eh?  Good to know!  :smile_cat: 

But seriously, yes, we would love to have an example of delft3d in SGRID format to experiment with, to make sure it works okay with @ayan-usgs's [pysgrid](https://github.com/sgrid/pysgrid) and [sci-wms](https://github.com/asascience-open/sci-wms), which you may have some interest in?

**Comment by ayan-usgs** [comment]
Yep, I'm still interested in seeing an example of delft3d in SGRID.

Thanks!

**Comment by hetland** [comment]
I'm glad my corrosion worked out. I'm interested to see this work too.

On Wednesday, September 23, 2015, ayan-usgs <notifications@github.com>
wrote:

> Yep, I'm still interested in seeing an example of delft3d in SGRID.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/25#issuecomment-142637893>
> .
>


-- 
Prof. Rob Hetland
Texas A&M Univ.  –  Dept. of Oceanography
http://pong.tamu.edu/~rob

**Comment by rsignell-usgs** [comment]
Closing this issue in favor of https://github.com/sgrid/pysgrid/issues/17.
