### ISSUE TITLE
The sandy triple nest simulations are missing from the portal

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#253]
The portal is looking for sandy data here and failing:
http://geoport-dev.whoi.edu/thredds/dodsC/clay/usgs/users/jcwarner/Projects/Sandy/triple_nest/00_dir_NYB05.ncml

**Comment by kwilcox** [comment]
Has your CSW updated?

**Comment by rsignell-usgs** [comment]
@kwilcox, yes, we secured the CSW endpoint, so it now has a `https:` prefix:
https://gamone.whoi.edu/csw  (instead of http://gamone.whoi.edu/csw)

The portal should pick up the 3 triple-nest sandy simulations shown in cell `[6]` here:
https://gist.github.com/anonymous/20745cbd847e62d19c382a053f98e25f

**Comment by tomkralidis** [comment]
@rsignell-usgs aside, you will want to update your pycsw config (`server.url`) to point to the https endpoint.

**Comment by rsignell-usgs** [comment]
@zdefne-usgs, I needed to modify the `.yaml` files you provided slightly.    You had: 
```
regExp=".ocean_NYB07_his_0-9]{4}\.nc$"
```
but we needed
```
regExp="*.ocean_NYB07_his_[0-9]{4}\.nc$"
```
We need the leading "*" because regular expression matches the full path name. 
And I'm guessing the missing left bracket was just a typo.

**Comment by rsignell-usgs** [comment]
@tomkralidis, good catch!  
Okay:  `default.cfg` starts off thusly now:
```
[server]
home=.
url=https://gamone.whoi.edu/csw
mimetype=application/xml; charset=UTF-8
encoding=UTF-8
language=en-US
maxrecords=10
profiles=apiso
```

**Comment by tomkralidis** [comment]
Yup. Not sure if your server needs to be rebooted/updated.

**Comment by kwilcox** [comment]
This was the "pycsw only returns 10 records no matter what you set maxrecords to" bug. It is fixed and the models automatically got added to the portal.

**Comment by tomkralidis** [comment]
@kwilcox this is by design and configurable to allow the pycsw admin to prevent requests asking for the whole catalogue. We implemented this for the use case of CSWs with millions of records. 

@rsignell-usgs in pycsw configuration what is server.maxrecords set to?
