### ISSUE TITLE
automatic harvesting of new data doesn't seem to be working.

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#258]
There are 2 new experiments on the THREDDS server that haven't been ingested.
 http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/catalog.html, WFAL_17, and SANDWICH2017.

Should I have done anything to kick off the ingest to the portal?
Thanks!

**Comment by emontgomery-usgs** [comment]
@kwilcox, @rsignell-usgs 
What is the current process for initiating ingest into the portal?

These two new datasets are at the sites of existing data, so will probably cause some new issues with getting data from overlapping placemarks.

**Comment by kwilcox** [comment]
@emontgomery-usgs I'll take a look this week at the new experiments and get them in the portal. I still have to "click a button" to sync your THREDDS server. Rich and I have to work on getting the ISO records from the experiment folders into the CSW.

**Comment by rsignell-usgs** [comment]
@kwilcox, it's no problem to ingest the CF-1.6 time series datasets into our pycsw server.   Should I go ahead and do that?  I've just been ingesting the model output datasets so far.

**Comment by emontgomery-usgs** [comment]
@rsignell-usgs @kwilcox 
Should something have happened with ingest of the new datasets yet?  I still don't see them in the display.

**Comment by rsignell-usgs** [comment]
@kwilcox https://github.com/USGS-CMG/usgs-cmg-portal/issues/258#issuecomment-330059977

Q: how many Axiom employees does it take to push a button?   :tongue:

**Comment by kwilcox** [comment]
Found the button and pressed it, all set.

**Comment by rsignell-usgs** [comment]
A: just one, but it takes 2.5 months. 👅 

But in the Center, there was much rejoicing!

![2017-10-29_10-54-22](https://user-images.githubusercontent.com/1872600/32144996-02d0c9fc-bc98-11e7-9961-9882081374e3.png)
