### ISSUE TITLE
ingest USGS Sandy storm tide Mapper Data 

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#26]
We want the USGS rapid response "storm tide" data into NetCDF files and into the portal.

If you drill in on the USGS sandy mapper
http://54.243.149.253/home/webmap/viewer.html?webmap=c07fae08c20c4117bdb8e92e3239837e
to a one of the red squares, you get a web page, with actual data  contained in text files.
The web pages are here:
http://ga.water.usgs.gov/flood/hurricane/sandy/sites/
![10-10-2014 11-03-37 am](https://cloud.githubusercontent.com/assets/1872600/4594348/b0d04efc-508e-11e4-8bc7-baeb2ccc9f3a.png)
![10-10-2014 11-02-57 am](https://cloud.githubusercontent.com/assets/1872600/4594349/b6413eb4-508e-11e4-94db-67ab9c9c9d0b.png)
![10-10-2014 11-03-21 am](https://cloud.githubusercontent.com/assets/1872600/4594351/bb44e21c-508e-11e4-9214-9982245e63a0.png)

**Comment by rsignell-usgs** [comment]
Ron Busciolano from USGS pointed out that the Sandy height are way off, but not by the ratio of m/ft, so not a strict units thing.    Check out the Long Beach station on long island here:
http://cmgdata.usgsportals.net/#map?lg=24546364-b61e-11e4-a8f4-00265529168c&p=proj3857&b=google_hybrid, 
but it's a problem at all stations (they are all way too high). 

![2016-04-14_16-01-47](https://cloud.githubusercontent.com/assets/1872600/14541934/68ba1a38-025a-11e6-9f81-ea601adf5fac.png)

Spot check the USGS Sandy Mapper at http://sandy.wim.usgs.gov/home/webmap/viewer.html?webmap=c07fae08c20c4117bdb8e92e3239837e

**Comment by kwilcox** [comment]
Sandy mapper link not working for me

**Comment by rsignell-usgs** [comment]
Googling "sandy mapper usgs" turns up:
http://stn.wim.usgs.gov/sandy/

**Comment by kwilcox** [comment]
![selection_194](https://cloud.githubusercontent.com/assets/13939/17667873/c6d4b42c-62d4-11e6-8897-6e20cb4bcad3.png)

Fixed in https://github.com/USGS-CMG/usgs-cmg-portal/commit/dcf71fc70d47deade61930956b30708388f69894
