### ISSUE TITLE
new model run "run076ns" in catalog not being displayed in portal

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#260]
@kwilcox , @zdefne-usgs added a new model run, which is showing up in our catalog, as evidenced by this notebook:
http://nbviewer.jupyter.org/gist/rsignell-usgs/fb900abb8edbcb1cd7fa781beed21e4e

If you see cell [4], it lists:

```title:USGS Barnegat Bay Model for non-Sandy conditions: run076ns
identifier:gov.usgs.cmg:USGS_BBLEH_SANDY_076NS
modified:2017-08-21
{'scheme': 'OPeNDAP:OPeNDAP',
 'url': 'http://geoport-dev.whoi.edu/thredds/dodsC/clay/usgs/users/zdefne/run076ns/00_dir_roms.ncml'}
 ```

But we don't see this on the Portal.   Why?

**Comment by kwilcox** [comment]
Mostly everything went as planned: http://cmgdata.usgsportals.net/#module-metadata/a3d4d540-f0f1-4099-a23a-beef8f1ae04c/cb810138-b81a-4fe6-8244-0e8dd9f01818

The only thing that didn't work was the re-index of the search/catalog so it wasn't discoverable. Fixing now.

**Comment by akbstone** [comment]
Re-indexed: http://cmgdata.usgsportals.net/#module-search?page=1&tagId=&q=barnegat%2520bay%2520model&tags=&types=module%2Csensor_station%2Cproject

**Comment by zdefne-usgs** [comment]
Thank you @kwilcox and @rsignell-usgs! Is this a one time fix or will the portal pickup the future model additions automatically?
