### ISSUE TITLE
Temporal Coverage may disagree with graphs in station metadata view

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#265]
First, the station search feature is a great enhancement!  However we have some cases where it needs some more help deciding what to display.

The time series data has several programs (Chincoteague, Barnegat 2014, RCNNWR) where there are sequential chunks of data from different times at the same location.  Usually these are denoted in the filenames displayed in the "select device" pull-down with 'a', 'b', 'c' following the first digits.  In the plot below, it chose to display data from the first temporal chunk, and correctly displays data from fall 2014 in the graph.  But the Temporal Coverage in the (red box) is from the last temporal chunk and shows spring 2015.  The Temporal Coverage field does not update, regardless of which time chunk is displayed in each of the graphs.

One solution would be to update the temporal coverage whenever a new device is selected.  I think it would be kinder to the user, if when there are more than one temporal chunk is available, the Temporal Coverage field displays the total duration, in this case August 2014-April 2015.

![image](https://user-images.githubusercontent.com/1771422/33381034-dd93ad4c-d4ea-11e7-8f79-c57166910c28.png)

An added enhancement would be to temporally aggregate the graphs, but that's a bigger project ;>

**Comment by kwilcox** [comment]
@akbstone Is this still issue? Does the temporal coverage span all devices on a station or assume all devices have the same extent?

**Comment by akbstone** [comment]
@emontgomery-usgs @kwilcox 

This is fixed
https://cmgdata.usgsportals.net/#metadata/64152/station
