### ISSUE TITLE
Add 5 min introductory video

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#273]
The main page specifies a 5 min video introduction.  I need to make one.

**Comment by rsignell-usgs** [comment]
Okay, 5 min video is here: https://www.youtube.com/watch?v=SwXysu9z3yI

@lucmehl (or other Axiom folk), can you please modify the link on the main page?

**Comment by lucmehl** [comment]
The tutorial url has been updated.
