### ISSUE TITLE
Need reharvest of SANDWICH2016 data

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#274]
@kwilcox , can you please reharvest the `SANDWICH2016` time series data?

@emontgomery-usgs has updated some datasets like
 http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/SANDWICH2016/10601hwlb-a.nc.html

**Comment by kwilcox** [comment]
Importing it now

**Comment by kwilcox** [comment]
These are updating and should finish shortly.
