### ISSUE TITLE
Catalog can't find turbidity

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#28]
If I search the catalog for "turbidity", I get nothing.   Why?

**Comment by emontgomery-usgs** [comment]
@rsignell-usgs, @kwilcox - I think we have the right solution to implement for turbitity variables.

We collect water clarity data in a variety of variables.  Our variables "Turb" (maybe occasionally Turbidity)  should be mapped to "sea_water_turbidity" (examples in BARNEGAT).

Our ATTN_55 varriables should be mapped to "volume_beam_attenuation_coefficient_of_radiative_flux_in_sea_water" variables we  (examples in BUZZ_BAY- names may have *ATT* in them.

We also have NEP* variables that are similar, but don't have the expected units, so we should probably ignore these for now.

**Comment by kwilcox** [comment]
Closing in favor of the more generic https://github.com/USGS-CMG/usgs-cmg-portal/issues/107
