### ISSUE TITLE
Long variable names cause bad display of variable list

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#281]
Some of our variable names are very long, and the way the "more" window works, you only see the end of the longest string.  If it could be changed to favor the start of all the strings, it would enable use.
Here's an example:
![image](https://user-images.githubusercontent.com/1771422/38097624-db4e6c72-3343-11e8-935d-9ac14d478f05.png)
The station plot for this data is here: https://cmgdata.usgsportals.net/#metadata/64154/station

**Comment by kwilcox** [comment]
@akbstone Can you add an ellipsis to long names here with the full name on hover?

**Comment by akbstone** [comment]
@kwilcox - the new interface places these variables in a select dropdown. Still not pretty, but doesn't have the same issue.

![image](https://user-images.githubusercontent.com/1093777/55817264-a15cee00-5aa0-11e9-8e3a-f18afa7720d7.png)
