### ISSUE TITLE
CDOM isn't displayed on Chincoteague 1020

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#282]
@kwilcox , Initially on https://cmgdata.usgsportals.net/#metadata/64154/station, the water temperature and CDOM variables don't plot, the rotating circle goes and goes.  The behavior is the same for the other station (I know about) with CDOM https://cmgdata.usgsportals.net/#metadata/64152/station.

This site has 23 files associated with the location (platform 1020); there were 6 sensors at slightly different elevations, and each has more than 1 time chunk with 'A','B','C', or 'D' indicating position in the temporal sequence. The portal correctly changes the time range when the a,b,c,d version is selected in the pull-down.  related to #265, #209, it would be neat to have the portal recognize these as concatenatable, and show the concatenated view (or at least have the time range show the complete data coverage). I thought for temperature, the issue may be with too many sources, but I think there was only one sensor measuring CDOM, so maybe that's not it.  

More perplexing, I reloaded the page, and on the refreshed station page water temperature plots fine, but still no CDOM.  Similarly, and related to #280, none of the curtain plots for currents was displayed.  Then I clicked again, and 2 worked as expected, and the one for "east" got a strange looking result.  After reloading the page, all 3 displayed reasonable looking content.

**Comment by kwilcox** [comment]
The CDOM variable is now showing up (there were a few more stations it was missing from as well). It was the length of the variable name that was throwing off a few things on our end.

A concatenated data view is possible in the next portal version. You can as @rsignell-usgs for a demo!
