### ISSUE TITLE
latest collect.py can't find cf_units

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#286]
@rsignell-usgs 

collect.py isn't running on silt: I did this and get problems importing Unit...
![image](https://user-images.githubusercontent.com/1771422/42113167-568ce014-7bb8-11e8-8aac-ec147a246d95.png)

I'm fairly sure the convert-wh environment is right.  What do you suggest I do? thanks!

**Comment by emontgomery-usgs** [comment]
doing this in the CONVERT-WH env fixed the problem:
 conda install -c conda-forge -c axiom-data-science --file requirements.txt

**Comment by rsignell-usgs** [comment]
@emontgomery-usgs nice work!
