### ISSUE TITLE
Removing USGS banner and branding

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#296]
After a long struggle to publish the portal as a USGS web site it looks like the problems are insurmountable in the near future:

* We can't have USGS branding on a non usgs.gov site
* We can't redirect usgs.gov to a non USGS computer.
* USGS is moving toward Drupal for all web pages

So @kwilcox and @akbstone, to be in compliant with USGS policay, please remove the USGS banner, replace with an Axiom banner, and change the title to "Oceanographic Model and Data Portal for USGS Coastal and Marine Geology Program Data".

**Comment by kwilcox** [comment]
Got my name wrong, just seeing this now

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rsignell-usgs** [comment]
@kwilcox ugh, sorry.  Too bad!  Glad you guys are on the case.

**Comment by akbstone** [comment]
@rsignell-usgs @kwilcox - If this looks ok, we can make it the live portal:

https://dev.axiomdatascience.com/?portal_id=35

![image](https://user-images.githubusercontent.com/1093777/52500757-3750c700-2b8b-11e9-8435-5a0b0438877a.png)

**Comment by rsignell-usgs** [comment]
@akbstone , I think it looks fine, but checking with the PI Neil Ganju and I'll get back to you.

**Comment by rsignell-usgs** [comment]
I checked with PI and got the green light, so yes, let’s make it live

**Comment by rsignell-usgs** [comment]
done, so closing.
