### ISSUE TITLE
Consume USGS CMG pyCSW server for service endpoints

### ISSUE THREAD

**Issue by kwilcox** [USGS-CMG/usgs-cmg-portal#41]
The pycsw service is now publicly exposed at 
http://geoport.whoi.edu/csw?service=CSW&version=2.0.2&request=GetCapabilities

Here's an example of querying it using owslib:
http://nbviewer.ipython.org/gist/rsignell-usgs/58f80172a77b8182843f/usgs_pycsw.ipynb

**Comment by rsignell-usgs** [comment]
This notebook illustrates requesting CMG_Portal endpoints using a csw query:
http://nbviewer.ipython.org/github/rsignell-usgs/notebook/blob/master/CSW/usgs_pycsw.ipynb
python code here:
https://github.com/rsignell-usgs/notebook/blob/master/CSW/usgs_pycsw.py

Currently there are two datasets available, and both have WMS and OPeNDAP endpoints enabled: COAWST, and https://github.com/ESIPFed/cf-dataset-curator/issues/5

**Comment by rsignell-usgs** [comment]
@kwilcox , I don't see either of these on the [CMG Portal](http://www.axiomdatascience.com/maps/cmg/#module-search?p=proj3857&b=google_hybrid&page=&tagId=&q=).

Can we enable for demo tomorrow?

**Comment by rsignell-usgs** [comment]
@kwilcox, there are 3 datasets that should be coming in when you search our CSW. 

http://nbviewer.ipython.org/gist/rsignell-usgs/58f80172a77b8182843f/usgs_pycsw.ipynb

I don't see the Barnegat Bay model dataset in the portal.   

Can you please enable automated reading and insertion of datasets from our CSW service?

**Comment by kwilcox** [comment]
This is complete.  The CSW harvest is running every 3 hours and pulling in datasets tagged with CMG_Portal.  Closing this is favor of a new issue if problems arise and also how we will identify which variables top show in portal.

**Comment by rsignell-usgs** [comment]
nice work Kyle!

On Thu, Apr 23, 2015 at 2:01 PM, Kyle Wilcox <notifications@github.com>
wrote:

> Closed #41 <https://github.com/USGS-CMG/usgs-cmg-portal/issues/41>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/41#event-288568676>.
>



-- 
Dr. Richard P. Signell   (508) 457-2229
USGS, 384 Woods Hole Rd.
Woods Hole, MA 02543-1598
