### ISSUE TITLE
T_20 misinterpreted as air_temperature instead of sea_water_temperature?

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#46]
For the station 3021 (in Buzzards Bay), the e Epic variable `T_20` 
http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/BUZZ_BAY/3021-A.cdf.html
is getting misinterpreted as `air_temperature` -- it should be `sea_water_temperature`.   If `T_20` in our files is used for both air and water temperature, perhaps the sensor height could be used for logic?  In other words, it's `sea_water_temperature` if the sensor height is below MSL.
![4-2-2015 2-06-03 pm](https://cloud.githubusercontent.com/assets/1872600/6971705/6c725916-d94c-11e4-87a1-4360d35d8a45.png)

**Comment by kwilcox** [comment]
The original variable has the epic code of 20, which I mapped to air_temperature via https://github.com/axiom-data-science/epic2cf/blob/master/epic2cf/data.py

Can you replace the epic_code in the original file with the correct epic code (if it is wrong)?

**Comment by rsignell-usgs** [comment]
ftp://ftp.epic.noaa.gov/epic/epic.key
`T_20` is temperature, which we use for ocean.
`T_21` is air temperature

**Comment by kwilcox** [comment]
Fixed via https://github.com/USGS-CMG/usgs-cmg-portal/commit/d352c16bdf028f96bd36c9b20dd61cc87e45ff27. This is the best we can do for these generic cases... please let me know if you identify any others!

**Comment by emontgomery-usgs** [comment]
Great!  We installed and tested on the BUZZ_BAY experiment and the  standard name was correct.
