### ISSUE TITLE
Problem downloading USGS CMG time series data via ERDDAP link

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#48]
Is ERDDAP working for the USGS CMG data?    I clicked on Buzzards Bay buoy `3021-a` and selected `Northward Sea Water Velocity` and clicked the `ERDDAP` link.  I got this [ERDDAP page](http://erddap.axiomalaska.com/erddap/tabledap/sensor_service.html?time,value,station,parameter,unit,depth&time%3E=1985-11-07T13:26:15&station=%22urn:ioos:station:gov.usgs.cmgp:3021-A%22&parameter=%22Northward%20Sea%20Water%20Velocity%22&unit=%22undefined%22&.draw=lines&.color=0x000000)

  I then selected the `.ncCFMA` output type and generated this URL:

```
http://erddap.axiomalaska.com/erddap/tabledap/sensor_service.ncCFMA?time,depth,station,parameter,unit,value&time%3E=1985-11-07T13:26:15Z&station=%22urn:ioos:station:gov.usgs.cmgp:3021-A%22&parameter=%22Northward%20Sea%20Water%20Velocity%22&unit=%22undefined%22
```

When I submit this URL, I get: 

```
HTTP Status 500 - Your query produced no matching results. (There are no matching stations.)

type Status report

message Your query produced no matching results. (There are no matching stations.)

description The server encountered an internal error (Your query produced no matching results. (There are no matching stations.)) that prevented it from fulfilling this request.
```

**Comment by kwilcox** [comment]
If you uncheck the "unit" checkbox it works, will investigate.

**Comment by rsignell-usgs** [comment]
I just tried using the ERDDAP link again for the USGS data:
http://erddap.axiomdatascience.com/erddap/tabledap/sensor_service.html?time%2Cvalue%2Cstation%2Cparameter%2Cunit%2Cdepth%26time%3E%3D1983-09-07T12%3A58%3A07%26station%3D%22urn%3Aioos%3Astation%3Agov.usgs.cmgp%3ASAB_SED_272%22%26parameter%3D%22Eastward%20Sea%20Water%20Velocity%22%26unit%3D%22undefined%22%26.draw%3Dlines%26.color%3D0x000000
and it doesn't work 
I tried removing the units (which I notice are "undefined"), and that doesn't work either:
http://erddap.axiomdatascience.com/erddap/tabledap/sensor_service.htmlTable?time,depth,station,parameter,value&time%3E=1983-09-07T12:58:07Z&station=%22urn:ioos:station:gov.usgs.cmgp:SAB_SED_272%22&parameter=%22Eastward%20Sea%20Water%20Velocity%22&unit=%22undefined%22
HTTP Status 500 - Your query produced no matching results. (There are no matching stations.)

**Comment by kwilcox** [comment]
We are transitioning to a better ERDDAP interface (one dataset per station) in the coming months. Stay tuned!

**Comment by kwilcox** [comment]
This has been live for awhile, see https://github.com/USGS-CMG/usgs-cmg-portal/issues/245
