### ISSUE TITLE
Extend archive data for specific stations

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#49]
It seems that there is only about a week of NDBC data on the portal.  
![4-2-2015 5-41-33 pm](https://cloud.githubusercontent.com/assets/1872600/6974315/b1bb7e72-d95f-11e4-8d7a-d3cb3c4438bc.png)

Is this true of all the near-realtime sensors?  

Is there just too much realtime sensor data to keep it all for all time?

**Comment by kwilcox** [comment]
The real-time layer will have up to a week of data, the rest is in the historical layer.  The real-time stuff comes from a cache so we can generate the hexbins quicky.

**Comment by rsignell-usgs** [comment]
I guess the historical data started about when the portal got activated, right? 
Most of the dates seem to start in July 2014.

**Comment by rsignell-usgs** [comment]
@kwilcox, closed with no comment?
Was this a "fixed", "will not fix" or something else?

**Comment by kwilcox** [comment]
This was moved here: https://github.com/USGS-CMG/usgs-cmg-portal/issues/96
