### ISSUE TITLE
Enable CORS on geoport.whoi.edu

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#50]
@kwilcox chatted me:  "the portal autoscale won't work until you have CORS enabled on your server.  That allows the portal to request JSON from the geoport ncWMS server" 
Instructions at: http://enable-cors.org/server.html

**Comment by rsignell-usgs** [comment]
From the information at http://enable-cors.org/server_tomcat.html, it looks like we need to first upgrade the thredds-dev tomcat `/usr/local/usgs-dev/tomcat-thredds` from tomcat 7.0.29 to at least 7.0.41 and then add these lines to the `conf/web.xml` file:
```
<filter>
  <filter-name>CorsFilter</filter-name>
  <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
</filter>
<filter-mapping>
  <filter-name>CorsFilter</filter-name>
  <url-pattern>/*</url-pattern>
</filter-mapping>
``

**Comment by rsignell-usgs** [comment]
@gregpike, would you be able to enable CORS on geoport's tomcat and tomcat-dev?
```
/usr/local/usgs/tomcat-thredds
/usr/local/usgs-dev/tomcat-thredds
```

**Comment by gregpike** [comment]
I'll try to get this done this afternoon.  I'll let you know when it's ready for testing.

**Comment by shane-axiom** [comment]
It's also possible to enable CORS in your front end web server without touching Tomcat:

http://enable-cors.org/server_apache.html
http://enable-cors.org/server_nginx.html

**Comment by rsignell-usgs** [comment]
@shane-axiom , this would be a better (higher-level) solution, right?

**Comment by shane-axiom** [comment]
Yeah, it's a lot cleaner/easier to enable on the web server in my experience.

**Comment by gregpike** [comment]
Sorry for the delay on this; CORS is enabled now.

**Comment by rsignell-usgs** [comment]
@gregpike , did you enable it on tomcat or on apache, or?

**Comment by gregpike** [comment]
Enabled in Apache.

**Comment by kwilcox** [comment]
@gregpike @rsignell-usgs This does not seem to be working.  Are you only enabling certain domains?

[Not working (your server)](http://client.cors-api.appspot.com/client#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Fgeoport-dev.whoi.edu%2Fthredds%2Fwms%2Fcoawst_4%2Fuse%2Ffmrc%2Fcoawst_4_use_best.ncd%3FLAYERS%3Dsandfrac_02%26STYLES%3Dboxfill%252Frainbow%26FORMAT%3Dimage%252Fpng%26TRANSPARENT%3Dtrue%26COLORSCALERANGE%3D0%2C1%26ELEVATION%3D-1%26TIME%3D2015-04-01T00%253A00%253A00Z%26SERVICE%3DWMS%26VERSION%3D1.1.1%26REQUEST%3DGetMap%26SRS%3DEPSG%253A3857%26BBOX%3D-8766409.89875%2C2504688.5425%2C-7514065.6275%2C3757032.81375%26WIDTH%3D256%26HEIGHT%3D256&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote)

[Working (our server)] (http://client.cors-api.appspot.com/client#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Fpdx3.axiomalaska.com%2FncWMS%2Fwms%3FLAYERS%3DFALMOUTH%252Fsalt%26STYLES%3Dboxfill%252Frainbow%26FORMAT%3Dimage%252Fpng%26TRANSPARENT%3Dtrue%26COLORSCALERANGE%3D27.02%2C34.39%26ELEVATION%3D-0.05%26TIME%3D2010-09-08T16%253A46%253A30Z%26SERVICE%3DWMS%26VERSION%3D1.1.1%26REQUEST%3DGetMap%26SRS%3DEPSG%253A3857%26BBOX%3D-7866287.4537891%2C5099878.5264771%2C-7863841.4688843%2C5102324.5113818%26WIDTH%3D256%26HEIGHT%3D256&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote)

**Comment by rsignell-usgs** [comment]
@gregpike , we need this working on geoport.whoi.edu as well as geoport-dev.whoi.edu

**Comment by gregpike** [comment]
Enabled on dev.  Let me know if you have any problems.

**Comment by kwilcox** [comment]
Verified working, can now autoscale datasets: http://axiomdatascience.com/maps/cmg/#map?lg=9bbb30d1-0cdd-477d-9f04-454dd86c635f&p=proj3857&b=google_hybrid

**Comment by rsignell-usgs** [comment]
And working in the Cesium-driven Australian National Map now also (this also required CORS).  Woo hoo!

![4-10-2015 3-16-20 pm](https://cloud.githubusercontent.com/assets/1872600/7095038/be07590e-df94-11e4-9c66-228dfce8b473.jpg)
