### ISSUE TITLE
Dealing with sensors of multiple heights + ADV/PCADP data not in CF version

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#52]
1) I don't see any ADV or PCADP files converted to CF

2)Typically our ADV and PCADP files have auxiliary sensors that aren't at the same height as the head.  If you look at the sensor_depth attribute in each variable this becomes clear.

The solution used to deal with pressure and temperature data from an ADCP head using the sensor_depth variable with the "surface_altitude" won't work successfully in this case.  An example ADV file is here: http://stellwagen.er.usgs.gov/thredds/dodsC/TSdata/DIAMONDSHOALS/8545advs-cal.nc.html- P_4023, Nep* and Sed* were measured at different depths than the rest.

Would making an auxiliary variable like depth_trans for the trans data that's at a different height work.? An example of this scheme is at http://thredds.aodn.org.au/thredds/dodsC/IMOS/ABOS/SOTS/Pulse/IMOS_ABOS-SOTS_20130507T080000Z_PULSE_FV01_PULSE-10-2013_END-20131013T210000Z_C-20140603T061703Z.nc.html

**Comment by kwilcox** [comment]
@emontgomery-usgs Regarding the ADV and PCADP files, I am only processing files with the naming convention matching:  http://regexr.com/3aoqu

Should I change it to this (captures 'cal'): http://regexr.com/3aor1

If those links don't work for you let me know!

**Comment by emontgomery-usgs** [comment]
@kwilcox , cool examples!  The second is better, but initially, I think you may want to avoid the b-cals, and only use the s-cal files.  The b-cal name indicates burst files, and their timebase is not even, and they tend to be quite large.

**Comment by kwilcox** [comment]
What about the `p-cal` files like `8572p-cal.nc` and `8542p-cal.nc`?

**Comment by emontgomery-usgs** [comment]
Ha!  I was thinking of making these a new issue because they're wave data.

Maybe ignore for now?

Rich and I would need to decide which CF standard names are appropriate for the variables in these files, and some of the variables have extra dimensions to represent spectra, possibly causing other problems (not timeSeries or timeSeriesProfile).  I don't think we fully know how to represent these yet.  Also, 8572p-cal is also incorrectly named- should be 8572whp-cal.nc.  Collected by a a wh adcp, but is waves, not currents.

**Comment by kwilcox** [comment]
@emontgomery-usgs Sounds good, here is the new selection I'll be using.  Please let me know if it is missing anything: http://regexr.com/3aosb

**Comment by emontgomery-usgs** [comment]
@kwilcox- 
You've got the condition for ADV and PCADP treating the s-cal and ignoring the b-cal perfect.

These below are things we may want to address:
These should only be ignored if there's a -a file of the same root  already done.
3051ATT-2A1H.cdf
3961ox-a1h.nc

9303sgWvs-p are waves and should not get picked up until the rest of those are done.
However, 9303sgWvs-tide or FI14/10022sgs-cal.nc (our naming style has evolved and I haven't done a blanket change yet) could be processed as simple timeSeries.

I have no Idea the differences between these- which experiment please?  There's probably good data in there, I just don't know what kind.
4731a-a.cdf
4731b-a.cdf
4731v-a.cdf

For all the ones with ###A-Z*, they're all sequential chunks of data from the same sensor- would be best to temporally aggregate these if we could before publishing

I believe psd is pressure std. deviation.  Is there a CF name for this?  If not we could skip all those files.

What experiment are these from?  I suspect there's good data, but the names aren't descriptive enough to get picked up.
4981.cdf
4982.cdf
4983.cdf
4991.cdf

**Comment by kwilcox** [comment]
All of  4731*, 4981.cdf, 4982.cdf, 4983.cdf, and 4911.cdf are in http://geoport.whoi.edu/thredds/catalog/usgs/data2/emontgomery/stellwagen/Data/MONTEREY_BAY/catalog.html

**Comment by emontgomery-usgs** [comment]
Thanks- Boy some of the older data is convoluted, and didn't conform completely to our current naming scheme (ha!).   For MONTEREY_BAY/4731 a,b,v, the A file has temperature data corresponding to the current data in the 'v' file.  The 'b' part has more temperature data from after barnacles caused the rotor to stop measuring speed.  Not sure why the 'a' temp data is not in the same file as the velocity data- but that's what's there. I think our mapping would already pick up the east, north, temp variables the same as u_1205, v_1206 and T_28, right?

Seems like if the names have no characters following the numbers, we should try to treat them, and would expect them to have east, north, temp, if nothing else that maps into CF names.

**Comment by emontgomery-usgs** [comment]
@kwilcox - contrary to what I said yesterday, we have a user very interested in the contents of the files with psd in the name, so please include them in the ones converted.  Thanks!

**Comment by emontgomery-usgs** [comment]
@kwilcox From conversation with @rsignell-usgs, we should probably NOT include ADV and PCADP in the crawl rules now.  Please remove them when you get a chance.

When we implement the PCADP and ADV types, we'll need to strip auxiliary sensors out to separate files to handle measurements made at altitudes other than height or surface_altitude.  Typically the pressure and turbidity measurements are each made a different height from where the "primary" (velocity) measurement is made.  The method for this would be to compare the sensor_depth attribute in each variable.  Most will match the primary (U_1205), and the ones that don't can be move to another file. 

Thanks!

**Comment by kwilcox** [comment]
This is covered in #48
