### ISSUE TITLE
Two way coupled ocn-wav Hurricane Sandy simulation with 3 level nesting

### ISSUE THREAD

**Issue by jcwarner-usgs** [USGS-CMG/usgs-cmg-portal#53]
Rich-
I placed history files for a 2-way coupled (roms+swan) with grid refinement (3 grids each) Hurricane Sandy simulation at:
clay:/usgs/users/jcwarner/Projects/Sandy/triple_nest

suggested blurb
"Two way coupled ocn-wav Hurricane Sandy simulation with 3 level nesting"

thanks,
john

**Comment by rsignell-usgs** [comment]
Cool.   We'll get this going.   I'm going to work with @tarankalra to get a python script going that will generate valid aggregation NcML for ROMS/COAWST files and we'll try it out on these.

**Comment by rsignell-usgs** [comment]
We used https://github.com/USGS-CMG/yaml2ncml on this and it is working. 
![7-28-2015 9-39-10 am](https://cloud.githubusercontent.com/assets/1872600/8932818/6c8d1356-350d-11e5-8a1f-d7097bf50302.jpg)
