### ISSUE TITLE
Create Python tool to generate NcML for ROMS/COAWST file collections

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#58]
A common use case is that a contributor to the `CMG_Portal` will drop a bunch of ROMS or COAWST files into a subdirectory and want to serve these a CF-standardized, aggregated dataset that can be viewed in the portal. 

One approach would be to just have a NcML template that folks could just customize for specific runs.  The disadvantage to this approach is that the number and type of variables change from run to run, and this would require editing variable specific metadata that could instead by autogenerated.  Another disadvantage is that  NcML errors could result in an invalid dataset that would not show up on THREDDS. 

Instead, we would like to use an approach where the users edits a simple input  [YAML](http://en.wikipedia.org/wiki/YAML) text file,  then runs a python script which generates the NcML.    

We will follow the [ACDD-1.3 Attribute Conventions](http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery_1-3) for metadata, the [CF-1.6 Conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html) for gridded data, and the [SGRID 0.1 Conventions](http://bit.ly/sgrid_cf) to specify the data on staggered grid.  

Sample [input YAML file](https://github.com/USGS-CMG/usgs-cmg-portal/blob/master/model_data/coawst_agg.yaml) for a MVCO COAWST simulation.

Sample [output NcML file](https://github.com/ESIPFed/cf-dataset-curator/blob/master/datasets/mvco_roms/00_dir_roms.ncml) for a MVCO COAWST simulation. We want the python script to generate something like this.

**Comment by rsignell-usgs** [comment]
@tarankalra, here's  example python code to read the YAML file using pyyaml.   You can do `conda install pyyaml` if you don't already have it. 

http://nbviewer.ipython.org/github/USGS-CMG/usgs-cmg-portal/blob/master/model_data/read_yaml.ipynb

You will notice by looking at the sample [output NcML file](https://github.com/ESIPFed/cf-dataset-curator/blob/master/datasets/mvco_roms/00_dir_roms.ncml) that there is a lot of repeated, constant metadata for each variable.   

But there are some differences:
* data at `rho` points (temp, salt, zeta, h, etc) need to be assigned `face` values
* data at 'u' points need to be assigned 'edge1' values
* data at 'v' points need to be assigned 'edge2' values.

In addition, we need to have a mapping between COAWST variable names and CF standard names.  You can pull some from that output example, but some others we may need to still to determine from looking at the [CF Standard Name list](http://cfconventions.org/Data/cf-standard-names/27/build/cf-standard-name-table.html)

**Comment by rsignell-usgs** [comment]
@tarankalra, a few tips:

* [an example of an Ipython notebook that reads the YAML file]((http://nbviewer.ipython.org/github/USGS-CMG/usgs-cmg-portal/blob/master/model_data/read_yaml.ipynb) using pyyaml.  You can do `conda install pyyaml` to install it. 

*  The [`pyncml` package](http://nbviewer.ipython.org/github/USGS-CMG/usgs-cmg-portal/blob/master/model_data/read_yaml.ipynb) will likely be useful.   You can do `conda install pyncml` as long as you've set up your conda environment set up to have the ioos channel.  See the [IOOS python environment wiki](https://github.com/ioos/conda-recipes/wiki) for more info.

**Comment by tarankalra** [comment]
Got it.

**Comment by tarankalra** [comment]
Have 3 if conditions: 

 If(include  = all) then 
  Dont go to exclude
 If(include  = none) then 
       Use user defines "include" only
       Dont go to exclude 
If(exclude ) then 
       Include everything but excluded items

**Comment by rsignell-usgs** [comment]
@tarankalra , sounds good!

**Comment by rsignell-usgs** [comment]
@tarankalra, I only found one bad link above, the one to the pyncml package, now fixed.   Any other problems here?

**Comment by tarankalra** [comment]
It looks good. Pyncml is working on my workstation.

**Comment by tarankalra** [comment]
@rsignell-usgs It seems that the link for SGRID 0.1 Conventions is down

**Comment by rsignell-usgs** [comment]
@tarankalra, grrr.... I had a bit of dyslexia there.   The SGRID conventions are at: http://bit.ly/sgrid_cf

**Comment by rsignell-usgs** [comment]
This code is still under development at https://github.com/USGS-CMG/yaml2ncml, but is working, so closing here.
