### ISSUE TITLE
Provide mechanism for new USGS datasets to automatically appear in the catalog

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#6]
We need to provide a mechanism for data providers to get new datasets (model runs or observations) into the portal without intervention from Axiom.

**Comment by kwilcox** [comment]
CMG will run a CSW containing the DAP/WMS endpoints we need.  We will scan periodically for updates.

**Comment by rsignell-usgs** [comment]
Okay, we can do that.   Would we use a special keyword to indicate that these results are for the CMG-Portal?

**Comment by kwilcox** [comment]
That would work

**Comment by rsignell-usgs** [comment]
Here's a proposed method to get new Woods Hole modeling datasets into the portal without human intervention (other than the model provider adding an attribute to their NcML):

* Modeler adds the global attibute `project='CMG_Portal` to their `roms_agg.ncml` file.  This is a recommended attribute on the [ESIP Attribute Conventions for Dataset Discovery (ACDD) Page](http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery), and maps into the ISO project keyword.
* On a schedule (every hour?), the [get_iso.py python script](https://github.com/rsignell-usgs/usgs-cmg-portal/blob/master/pycsw_cmg/get_iso.py) crawls specified thredds catalogs, reads the ISO XMLs into memory, checks for the presence of the project keyword `CMG_Portal`, which should looks like this:
```
</gmd:pointOfContact>
<gmd:descriptiveKeywords>
<gmd:MD_Keywords>
<gmd:keyword>
<gco:CharacterString>CMG_Portal</gco:CharacterString>
</gmd:keyword>
<gmd:type>
<gmd:MD_KeywordTypeCode codeList="http://www.ngdc.noaa.gov/metadata/published/xsd/schema/resources/Codelist/gmxCodelists.xml#MD_KeywordTypeCode" codeListValue="project">project</gmd:MD_KeywordTypeCode>
</gmd:type>
<gmd:thesaurusName gco:nilReason="unknown"/>
</gmd:MD_Keywords>
</gmd:descriptiveKeywords>
```
* If found, the script generates a WMS endpoint in SciWMS using the REST API, and also modifies the ISO to contain the SciWMS endpoint.   It then writes the modified ISO to disk.
* On a schedule, the ISO data is loaded into the pycsw instance at http://pycsw.geoport.whoi.edu where it is available for query via CSW.
* On a schedule, Axiom queries our pycsw instance for datasets with the `CSW_Portal` keyword and adds them to the portal.

@ayan-usgs and @kwilcox , what do you guys think?

**Comment by kwilcox** [comment]
:+1:

**Comment by rsignell-usgs** [comment]
Okay, it's a plan!

**Comment by emontgomery-usgs** [comment]
So what's the status of this?  There's a new experiment on stellwagen that need converting to  CF-1.6.
Fire Island 2014 (FI14).  Thanks!

**Comment by shane-axiom** [comment]
This is mostly finished. One large remaining hurdle is figuring out which variables from these datasets we want to display. We can support both tagging (via attributes) a subset of variables to include and a subset of variables to exclude; if there are no include attributes on any variables, all variables with at least x, y, and t dimensions will be included.

Does that sound reasonable? It feels wrong to embed presentation (portal specific) information in the datasets, but that somehow has to be included in either the NetCDF (accessed via OPeNDAP) or the CSW response.

**Comment by emontgomery-usgs** [comment]
Also Hatteras09 (NEARSHORE) has missed being translated so far, so there are 2 to do.

**Comment by rsignell-usgs** [comment]
@kwilcox can correct, but I think this issue was intended to automate the inclusion of *model* datasets into the catalog.   

For the observational stuff,  I believe axiom is just grabbing everything in the CF-1.6 folder:
http://geoport.whoi.edu/thredds/catalog/usgs/data2/emontgomery/stellwagen/CF-1.6/catalog.html

So @emontgomery-usgs, if Fire Island and Hatteras files are in fact in this directory:
http://geoport.whoi.edu/thredds/catalog/usgs/data2/emontgomery/stellwagen/Data/catalog.html
then just run the python script which generates the CF-1.6 files and they should show up here:
http://geoport.whoi.edu/thredds/catalog/usgs/data2/emontgomery/stellwagen/CF-1.6/catalog.html
and Axiom can pick them up.

**Comment by kwilcox** [comment]
@emontgomery-usgs @rsignell-usgs Rich is correct, you can just run the python script to generate the CG1.6 files and we will pick them up automatically.  Be sure to edit the CSV Metadata file if it is a new project https://github.com/USGS-CMG/usgs-cmg-portal/tree/master/woods_hole_obs_data#csv-metadata-file

**Comment by shane-axiom** [comment]
Any comment on the include/exclude variable via attribute proposal?

> One large remaining hurdle is figuring out which variables from these datasets we want to display. We can support both tagging (via attributes) a subset of variables to include and a subset of variables to exclude; if there are no include attributes on any variables, all variables with at least x, y, and t dimensions will be included.

Maybe a `display` true/false string variable attribute?

**Comment by kwilcox** [comment]
@rsignell-usgs poke

**Comment by zdefne-usgs** [comment]
Selecting/removing variables with include/exclude in the yaml file did not work for me.

**Comment by rsignell-usgs** [comment]
@zdefne-usgs, I see that the existing logic in [yaml2ncml](https://github.com/USGS-CMG/yaml2ncml/blob/master/yaml2ncml/yaml2ncml.py) is incorrect.   It was supposed to remove variables from dataset via NcML, but it ends up just removing the SGRID information.  

Instead of fixing this to work as originally intended, I'll modify yaml2ncml to add `display=True` or `display=False` to each variable.

**Comment by kwilcox** [comment]
@rsignell-usgs sounds good, I will add those attributes to the CSW harvester and new models will be auto-added once deployed (next week... i'm off today).

**Comment by rsignell-usgs** [comment]
@zdefne-usgs , okay, I made the mods to yaml2ncml and regenerated the NcML, and the display attributes look good:
http://geoport-dev.whoi.edu/thredds/dodsC/clay/usgs/users/zdefne/run076/his/00_dir_roms_display.ncml.html

**Comment by zdefne-usgs** [comment]
Great, Thank you Rich!

Looks like all of the selected variables but ubar, vbar and bed layer thickness are displayed. Bed thickness does not  have a standard name attribute, which could be the reason. But in that case it is a ROMS output issue rather than the yaml code or the portal. I couldn't find out why ubar, vbar wouldn't plot. Maybe because they are not on rho coordinates?

**Comment by kwilcox** [comment]
I had not deployed the changes yet, the list that was showing up was defined by me all willy-nilly!  The yaml defined list is up there now.

`bed_thickness` is not working because it is not being advertised by your WMS server: http://geoport-dev.whoi.edu/thredds/wms/clay/usgs/users/zdefne/run076/his/00_dir_roms_display.ncml?request=GetCapabilities&service=WMS

http://geoport-dev.whoi.edu/thredds/wms/clay/usgs/users/zdefne/run076/his/00_dir_roms_display.ncml?SERVICE=WMS&REQUEST=GetMap&LAYERS=bed_thickness&VERSION=1.1.1&FORMAT=image/png&STYLES=boxfill/rainbow&SRS=EPSG:3857&BBOX=-8286327.3465104215,4785524.378305403,-8237944.9952729605,4886457.803609362&WIDTH=240&HEIGHT=500&COLORSCALERANGE=1.53,2.461

**Comment by rsignell-usgs** [comment]
closing this in favor of #158
