### ISSUE TITLE
Include NDBC station numbers in short title

### ISSUE THREAD

**Issue by bbutman-usgs** [USGS-CMG/usgs-cmg-portal#61]
current header on map mouse-over shows a title.  for example, header for 44013 appears as:
```
National Data Buoy Center
Boston 16 NM east of Boston, MA 
```
![4-10-2015 7-38-33 am](https://cloud.githubusercontent.com/assets/1872600/7086995/b9580754-df54-11e4-816e-fd21e73ce580.png)

This text appears to be obtained from NDBC header (see http://www.ndbc.noaa.gov/station_page.php?station=44013).

I suggest leaving the station number, which means something to those who work w/ these data.  so would be:
```
National Data Buoy Center
Station 44013 - BOSTON 16 NM East of Boston, MA
```
This requires stripping the  (LLNR 420) from the current header.

**Comment by rsignell-usgs** [comment]
:+1:

**Comment by kwilcox** [comment]
@bbutman-usgs @rsignell-usgs How does this look?

`Central Green Bay, WI` -> `(45014) Central Green Bay, WI`
`NEWPORT - 210NM West of Coos Bay, OR` -> `(46407) NEWPORT - 210NM West of Coos Bay, OR`
`St Joseph, MI` -> `(20CM4) St Joseph, MI`
etc, etc, etc.

**Comment by rsignell-usgs** [comment]
@kwilcox , yep, that would be good.

**Comment by kwilcox** [comment]
![selection_064](https://cloud.githubusercontent.com/assets/13939/9395538/0da5cce0-475d-11e5-9a2f-b5a3f9c72215.png)

**Comment by rsignell-usgs** [comment]
@kwilcox, nice!
