### ISSUE TITLE
How does the map browser handle multiple files at a single point?

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#62]
@rsignell-usgs Most of our data  are multiple files at a single point (each file on a tripod or mooring will have s file).

Example: The Hurricane Irene Buzzards Bay data doesn't all show up on the map view in the portal.  There were 3 instruments on the platform- only the seacat shows up, no adcp, no ysi. The data is at http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/HURRIRENE_BB/catalog.html

**Comment by kwilcox** [comment]
@emontgomery-usgs is it safe to assume that all files from the same mooring/deployment (914 in this case) will always be at the same exact location?  I can combine them into one dot on the map if this is the case.

**Comment by emontgomery-usgs** [comment]
Yes.  all files with same first 3 (or 4 if > 1000) will be at the same x,y
position.  Z will be different.


On Wed, Jul 22, 2015 at 12:57 PM, Kyle Wilcox <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs> is it safe to
> assume that all files from the same mooring/deployment (914 in this case)
> will always be at the same exact location? I can combine them into one dot
> on the map if this is the case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/62#issuecomment-123791427>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
Great, I'll make that change on this next go-round!

**Comment by kwilcox** [comment]
Closing in favor of https://github.com/USGS-CMG/usgs-cmg-portal/issues/148
