### ISSUE TITLE
z dimension in ADCP data doesn't contain depths

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#63]
@rsignell-usgs The plot below shows how ncBrowse displays u_1205, and the z coordinate doesn't contain the actual measurement depths.  On stellwagen, we have:
Dataset 
    Float32 depth[depth = 33];
 TSdata/HURRIRENE_BB/9141wh-a.nc;
---------------------------------------------
depth[33]
14.398672, 13.898672, 13.398672, 12.898672, 12.398672, 11.898672, 11.398672, 10.898672, 10.398672, 9.898672, 9.398672, 8.898672, 8.398672, 7.8986726, 7.3986726, 6.8986726, 6.3986726, 5.8986726, 5.3986726, 4.8986726, 4.3986726, 3.8986726, 3.3986726, 2.8986726, 2.3986726, 1.8986725, 1.3986725, 0.89867246, 0.39867246, -0.10132754, -0.60132754, -1.1013275, -1.6013275

I'm not sure if this is a problem with ncBrowse not interpreting CF well, or whether there's a problem in assigning the depth variable to 'z'.

![image](https://cloud.githubusercontent.com/assets/1771422/7123544/d462e156-e1f0-11e4-97e2-e4205b722c72.png)

In matlab, I tried to load and pcolor(time, depth, u_1205) and found there's no more depth variable in the CF version, and that z only conttains 0-32.  I think we want the z coordinate to be what used to be in depth.  What am I missing?  Thanks!

**Comment by rsignell-usgs** [comment]
The `height` vertical coordinate values look okay on the file I converted:
http://geoport-dev.whoi.edu/thredds/dodsC/usgs/data2/rsignell/data/usgs-cmg-portal/woods_hole_obs_data/test_issue_51_output/HURRIRENE_BB/9141wh-a.nc.ascii?height[0:1:32]

So I'm wondering whether ncBrowse recognizes `positive=down`?   

@kwilcox, since we are creating these, let's use `positive=up` and flip the values, okay?
That way we will work with more (deficient) clients.

**Comment by kwilcox** [comment]
@emontgomery-usgs Can you test this file that uses positive: 'up' with your program: https://www.dropbox.com/s/97yftsc4dipzqov/9141wh-a.nc?dl=0

**Comment by emontgomery-usgs** [comment]
I tried it and the z values are still 0 to 32.  Only difference is that the
30 is on the opposite side of the plot than in the one I generated.

On Mon, Apr 13, 2015 at 4:58 PM, Kyle Wilcox <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs> Can you test this
> file that uses positive: 'up' with your program:
> https://www.dropbox.com/s/97yftsc4dipzqov/9141wh-a.nc?dl=0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/63#issuecomment-92496152>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
The problem is that ncBrowse doesn't understand CF conventions.   It understands COARDS conventions.  So since the dimension is "z", it's looking for a variable called "z" and when it doesn't find it, just uses indices from 0 to 32 because it doesn't know what else to do.

**Comment by emontgomery-usgs** [comment]
So, if  we rename the height variable 'z', then we'd be able to have CF-compliance, **AND** still be able to use ncBrowse to view the data.  Is there a down-side to this?

**Comment by emontgomery-usgs** [comment]
FYI, NASA's Panoply viewer doesn't interpret the height-as-z correctly either (and it's supposed to be CF compliant.  It looks like it's using the Z, but in a grid-centered way instead of a grid-edge way.

I also tried NOAA's climate and weather viewer, and it does timeSeries data fine, but doesn't know how to deal with timeSeriesProfiles.

I wonder if our adcp data has the y axis displayed correctly in any of the CF-1.6 viewers?
![image](https://cloud.githubusercontent.com/assets/1771422/7204074/6ca467e2-e4ed-11e4-945a-9dfb7733dc63.png)

**Comment by emontgomery-usgs** [comment]
FYI-
The most recent version of Panoply has the bug fixed, and it can work with the 'z' coordinate as currently implemented in our adcp files.

I have a slight preference for calling 'height' 'z' to maintain backwards COARDS compatibility.

**Comment by rsignell-usgs** [comment]
Yes, let's rename the `height` variable to `z`.

**Comment by emontgomery-usgs** [comment]
{thumbs-up icon here}
