### ISSUE TITLE
surface_altitude gone missing?

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#65]
@kwilcox , @emontgomery-usgs and I thought we had `surface_altitude` attribute set for time-series data within ADCP type datasets like
http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/HURRIRENE_BB/9141wh-a.nc.html
but when we look at temperature `Tx_1211` we don't find the attribute. 

This is necessary to specify the height of this time series measurement according to CF. 
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#Example%20H.2.3.2

Did this go missing, or did we never have this in the conversion?

The data to specify this height is in `sensor_depth`

**Comment by kwilcox** [comment]
the `sensor_depth` variable is doing this... does it need to be named `surface_altitude` (that would be crazy).

**Comment by rsignell-usgs** [comment]
Right now, according to CF 1.6, it's  "surface_altitude". 

From:
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/cf-conventions.html#idm43165448416

"It is recommended that there should be station variables with standard_name attributes "platform_name", "surface_altitude" and “platform_id” when applicable. "

  But clearly it should be "platform_altitude"!!!

I can ask if we deprecate "surface_altitude" in CF 1.7, in favor of "platform_altitude"

But if we want things to truly be cf 1.6 compliant, we need to change to "surface_altitude"

**Comment by kwilcox** [comment]
These datasets do have a variable with the `standard_name` attribute equal to `surface_altitude`.  I called that variable `sensor_depth`.

**Comment by rsignell-usgs** [comment]
Jeez.   You are right.   I need to go home and check my horoscope.  I must be having a 2 star day. :crying_cat_face:
