### ISSUE TITLE
names for PAR data- need to deal with in air and underwater

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#69]
We currently use downwelling_photosynthetic_photon_flux_in_sea_water for PAR_905.  Shouldn't it be downwelling_photosynthetic_**radiative**_flux_in_sea_water ?

Also, most of our PAR measurements are made in water, but the Onset weather station (*hlm*) also measures PAR, but in air, using the same variable name.  Can we add the case that if file name contains 'hlm', the PAR standard name is "surface_downwelling_photosynthetic_radiative_flux_in_air", and everything else gets "downwelling_photosynthetic_radiative_flux_in_sea_water"?

Thanks!

**Comment by kwilcox** [comment]
@emontgomery-usgs Can you send me a dataset name that uses PAR_905 in each way so I can test?

**Comment by emontgomery-usgs** [comment]
HI-
This PAR_905 is from an atmospheric sensor
http://stellwagen.er.usgs.gov/thredds/dodsC/TSdata/RCNWR/9521Ahlm-a.nc.html

This one is subaqueous
http://stellwagen.er.usgs.gov/thredds/dodsC/TSdata/BARNEGAT/9631ecp-a.nc.html

Things that occur to me to differentiate:
filename (if has m for met)
Is the measurement depth positive or negative (depending on z positive=
up/down)
presence of other met variables in file (T_21. WD_410, WS_401)

Good luck!

On Wed, May 13, 2015 at 12:32 PM, Kyle Wilcox <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs> Can you send me a
> dataset name that uses PAR_905 in each way so I can test?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/69#issuecomment-101738724>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356
