### ISSUE TITLE
Run pycsw in more robust way

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#70]
@tomkralidis, we want to use Anaconda python, and we have a custom env that has all the pycsw dependencies.   We've been starting pycsw as 
```
source activate ioos
cd /opt/pycsw
python csw.wsgi
```
Is there a more robust way?
-Rich

Rich: from my experience deploying using Apache and mod_wsgi is the preferred
option; running like the example in [1] simply runs pycsw through Python's
built in HTTP server [2] and is meant for dev/testing/getting up and running
with no effort.  The pycsw unit tests also use this approach.

..Tom

[1] https://github.com/USGS-CMG/usgs-cmg-portal/wiki/Starting-pycsw-on-geoport
[2] https://github.com/geopython/pycsw/blob/master/csw.wsgi#L125

**Comment by rsignell-usgs** [comment]
@tomkralidis On this page http://docs.pycsw.org/en/latest/installation.html#running-on-wsgi you state:
"mod_wsgi supports only the version of python it was compiled with. If the target server already supports WSGI applications, pycsw will need to use the same python version."

By python version, do you mean simply Python 2 or Python 3?

**Comment by rsignell-usgs** [comment]
Considering that we want to use Anaconda python, and reading up on the issues with apache here:
http://serverfault.com/questions/550463/apache-pointing-to-the-wrong-version-of-python-on-ubuntu-how-do-i-change#comment637150_550479
I'm thinking that it would be better to go with `Nginx/Gunicorn/Supervisord` instead of Apache, as described nicely here:
http://birdhouse.readthedocs.org/en/latest/installation.html#nginx-gunicorn-and-supervisor

Also, this is what sci-wms is using on geoport, another important component of the CMG portal, so we know that `Nginx/Gunicorn/Supervisord` is already working on geoport.

**Comment by rsignell-usgs** [comment]
Can we just use this?  https://pypi.python.org/pypi/birdhousebuilder.recipe.pycsw

**Comment by tomkralidis** [comment]
Rich: Python 2 currently.

**Comment by tomkralidis** [comment]
Rich: looks like this is definitely an option. Not sure which version of pycsw it builds/uses (maybe @cehbrecht has some insight).

**Comment by rsignell-usgs** [comment]
I did a screen share with @kwilcox this morning and he got pycsw  running on `nginx/gunicorn/supervisord`.

The good news is that it's running, should be more stable and start on reboot.

The bad news is that he was moving too fast for me to understand, and so we don't have any documentation of what exactly he had to do.     It wasn't simple.

**Comment by rsignell-usgs** [comment]
I know that this was part of it:
https://github.com/bird-house/birdhousebuilder.recipe.pycsw/pull/1/files

**Comment by rsignell-usgs** [comment]
Okay, I've documented as much as I understand here: https://github.com/USGS-CMG/usgs-cmg-portal/wiki/Installing-pycsw-with-nginx,gunicorn,supervisor
Hoping that @kwilcox can review and correct any errors or omissions.

@tomkralidis, I'm giving you a heads up here in case you want to adapt/expand for more general use by the pycsw community.

**Comment by tomkralidis** [comment]
Thanks @rsignell-usgs will do.
