### ISSUE TITLE
Add ability to specify behavior for data outside specified color range

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#71]
What should we do with values that are outside the specified color range?  

NcWMS sets them to black:
![5-6-2015 3-49-31 pm](https://cloud.githubusercontent.com/assets/1872600/7502547/c387d89c-f40a-11e4-8fbe-d1c21ffc61b5.png)

But as the above image illustrates, black is not always what is most useful for the user. 

In many cases, transparent would be more valuable.   This would allow land and bathymetry to "show through" in the range of colors that are not of interest to the user. So I would argue that transparent would be a better choice than black.    

Transparency could be accomplished simply in sci-wms by using masked arrays http://stackoverflow.com/a/22672080

The worst choice would be to just extend the max color above and the min color below.   This is **very** misleading.

Ideally the user/client would allow specification of this behavior.   

I've asked this on https://github.com/sci-wms/sci-wms/issues/33 as it's both a ncWMS and a SciWMS issue.

**Comment by kwilcox** [comment]
@rsignell-usgs is this OK to close? sci-wms defaults to transparent

**Comment by rsignell-usgs** [comment]
@kwilcox, yes, I guess so.  It would be nice to ahve ABOVEMAXCOLOR and BELOWMINCOLOR, as in the [ncWMS extensions](http://www.resc.rdg.ac.uk/trac/ncWMS/wiki/WmsExtensions), but I think that's handled in a different ticket.
