### ISSUE TITLE
non-axiom access point for portal

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#73]
Could we have a CMG model data and time series portal endpoint at
http://cmgdata.usgsportals.net
so we don't have to expose:
http://www.axiomdatascience.com/maps/cmg/#module-search?p=proj3857&b=google_hybrid&q=&tagId=&page=

@shane-axiom, I understand you did this for 
http://cmgvideo.usgsportals.net/

**Comment by shane-axiom** [comment]
Oops, this has actually been done since last week, I just forgot to send out the notification. The old URLs at http://www.axiomdatascience.com/maps/cmg redirect to the new URL.

**Comment by kwilcox** [comment]
:clap:

**Comment by rsignell-usgs** [comment]
fantastic!
