### ISSUE TITLE
Finalize the variable attributes for defining sanity and vizualization values

### ISSUE THREAD

**Issue by kwilcox** [USGS-CMG/usgs-cmg-portal#75]
On each variable, `valid_min` and `valid_max` should/can be used to define sanity values for a variable (the user should not be able to edit the values below or above these limits).  We need to defined two additional attributes to define what the default scale should be.  `viz_min` and `viz_max`?

**Comment by kwilcox** [comment]
After talking this out with @rsignell-usgs we agreed that it will be difficult to get this provided for every variable and that we needed sane default values.  I've started calculating min/max from a random subset of a variables data when it first gets added to the portal.  This should provide a sane baseline that we can revisit on a case by case basis.

**Comment by rsignell-usgs** [comment]
Awesome.  Thanks Kyle!
