### ISSUE TITLE
Station metadata about time window and actual data window differ in some case

### ISSUE THREAD

**Issue by bbutman-usgs** [USGS-CMG/usgs-cmg-portal#76]
Buoys operated by University of Maine (A01, B01, E01, I01, M01 and N01) and  others in the Gulf of Maine are not reporting current info (for example water temperature).  Last data 16 June.  Data are available at NERACOOS, so seems stations are working; update issue?

**Comment by rsignell-usgs** [comment]
@bbutman-usgs, interesting.    Indeed the lack of a colored dot with value and the ending time on the metadata from several days before would seem to indicate that the data is not there, but if you click on the point, in fact the data *is* there.     

So indeed some type of metadata issue.   @kwilcox, thoughts?
![6-29-2015 2-22-12 pm](https://cloud.githubusercontent.com/assets/1872600/8415258/84735434-1e6b-11e5-8844-83033e8ac359.jpg)

**Comment by lance-axiom** [comment]
This is fixed now in the live site.
