### ISSUE TITLE
'Turbidity' does not capture historical beam attentuation or transmission data

### ISSUE THREAD

**Issue by bbutman-usgs** [USGS-CMG/usgs-cmg-portal#77]
Historical data, select 'tubidity', WHCMSC, none of transmissometer data show up.

![portal_turbidity](https://cloud.githubusercontent.com/assets/11786524/8415430/ad68b8d8-1e6c-11e5-8d2d-22a2bbd482af.PNG)

**Comment by rsignell-usgs** [comment]
@bbutman-usgs, actually, although the East Coast Historical Sensor Catalog has "USGS Woods Hole Coastal and Marine Science Center" as one of the "Sources", our WHCMSC Historical Time Series data is in the catalog called "USGS CMG Woods Hole Observations".    

Yes, I find this confusing also.

And to make matters worse, although you can select "Volume Beam Attenuation Coefficient..." in the list of "Sensors", I couldn't find any point to click on that didn't say "Error retrieving data" as a result.

![6-29-2015 2-52-08 pm](https://cloud.githubusercontent.com/assets/1872600/8416986/76188ea2-1e77-11e5-937f-445f28b06646.jpg)

**Comment by kwilcox** [comment]
@rsignell-usgs Should "USGS CMG Woods Hole Obsevations" be removed in favor of grouping everything under "USGS Woods Hole Coastal and Marine Science Center"?

**Comment by kwilcox** [comment]
@rsignell-usgs pinging my question above

**Comment by rsignell-usgs** [comment]
Yes!  This will make things much less confusing for users.

**Comment by bbutman-usgs** [comment]
Making one category as proposed is good (not clear why not the same previously).  I would call it the 'U.S. Geological Survey Oceanographic Time-Series Data' (not woods hole center); thats the official name of the database.  when i enter the 'historical page' displayed on the opening screen, sorting by Woods Hole does not exist in the drop down; WH data should be included as part of the 'historical' data (maybe i don't understand definition of historical).  also, there are no observations shown south of cape hatteras.  this portal should cover entire east coast. if it is going to serve all USGS oceanographic data, should cover GoMexico and west coast.  this needs discussion.

**Comment by rsignell-usgs** [comment]
@kwilcox , indeed the USGS Coastal and Marine Program is a national program, with offices in Woods Hole, St. Petersburg FL, and Santa Cruz, CA.    Our mission is national.    Could the realtime sensors and historical sensors be expanded to the Nation instead of just New England?

**Comment by kwilcox** [comment]
@emontgomery-usgs and I had an email discussion regarding this, backscatter intensity and beam attenuation data will be included in the "Turbidity" category on the next obs database refresh.

**Comment by kwilcox** [comment]
@rsignell-usgs OK to close?

**Comment by rsignell-usgs** [comment]
Yep, thanks.
