### ISSUE TITLE
Experiment BW2011 fails in collect.py

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#80]
Yesterday i started a complete re-run of the CF-1.6 conversion.  It downloaded everything successfully and translated the files from several experiments.  Everything was good until it got here.
INFO Translating /usgs/data2/emontgomery/stellwagen/usgs-cmg-portal/woods_hole_obs_data/download/9031ysi-a.nc into CF1.6 format: /usgs/data2/emontgomery/stellwagen/CF-1.6new/BW2011/9031ysi-a.nc

9031ysi-a.nc is in download, and one in CF-1.6new.  The CF version ncdumps fine.  Thinking it might have been a system problem, I tried executing this command this morning:
 python collect.py -p BW2011 --folder download -o ../../CF-1.6new
2015-07-02 09:50:52 gam root[4805] DEBUG Could not find CF mapping for EPIC code 624
2015-07-02 09:50:52 gam root[4805] DEBUG Could not find CF mapping for EPIC code 624
2015-07-02 09:50:52 gam root[4805] DEBUG Could not find CF mapping for EPIC code 500
2015-07-02 09:50:52 gam root[4805] DEBUG Could not find CF mapping for EPIC code 502
2015-07-02 09:50:52 gam root[4805] INFO Translating download/9031ysi-a.nc into CF1.6 format: /usgs/data2/emontgomery/stellwagen/CF-1.6new/BW2011/9031ysi-a.nc
Segmentation fault (core dumped)

I removed the file in CF-1.6new, re-ran the command and got the same result.

Then tried it with --download, and it re-downloaded, and still failed with the segmentation fault.

I wonder what is toxic about 9031ysi-a.nc?

**Comment by kwilcox** [comment]
I can process this file locally on my computer, @rsignell-usgs, can you test with your Anaconda setup?

**Comment by emontgomery-usgs** [comment]
Before doing another "run all" with collect.py, we tried to skip BW2011 by moving it's entry in the .csv file to the end, but the run of collect.py failed in the same place (after re-cloning from Master in my area).  The order of translation is clearly not the order in the .csv file.  When situations like this happen, is there a way to avoid known problem areas?  At this point, 5 experiments got processed, and there are ~ 50 more that would need to be done 1 by 1, if we can't skip the problem file.

**Comment by kwilcox** [comment]
You can remove BW2011 from the CSV file

**Comment by emontgomery-usgs** [comment]
Is there the equivalent of commenting a line out instead of deleting it
completely?  I'd like to comment out the ones already done too, so it
doesn't try to re-do them.  This time around I'd point to the folder where
the downloaded files are...

On Thu, Jul 2, 2015 at 12:16 PM, Kyle Wilcox <notifications@github.com>
wrote:

> You can remove BW2011 from the CSV file
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/80#issuecomment-118082142>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
@emontgomery-usgs You can now prefix a row with a `#` to ignore it when running `collect.py`.  I've also updated the README with this functionality!

**Comment by emontgomery-usgs** [comment]
@kwilcox Thank you!  That will really help in cases where things don't go perfectly.

**Comment by emontgomery-usgs** [comment]
I wasn't using the right wget command, so was getting unusual files in the
directory from which collect.py works.  I've fixed that, and the files
ncdump fine, and have the id=attribute once they've been downloaded, but I
still get core dumps. when trying to translate.

FYI- over the weekend, all but two of the other experiments re-ran.  I've
already corrected what was wrong with one, and am re-getting the data for
the other, so progress is being made.

On Thu, Jul 2, 2015 at 11:02 AM, Kyle Wilcox <notifications@github.com>
wrote:

> I can process this file locally on my computer, @rsignell-usgs
> <https://github.com/rsignell-usgs>, can you test with your Anaconda setup?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/80#issuecomment-118060384>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
@emontgomery-usgs , good to hear!   Fingers crossed that you can squash the last bugs!

**Comment by kwilcox** [comment]
@emontgomery-usgs Can you send me a `BW2011` file that is failing after downloading? I will compare it to the file I get after downloading.

**Comment by emontgomery-usgs** [comment]
Will do.  Bug stomping boots on.

On Mon, Jul 6, 2015 at 10:43 AM, Kyle Wilcox <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs> Can you send me a
> BW2011 file that is failing after downloading? I will compare it to the
> file I get after downloading.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/80#issuecomment-118876455>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by emontgomery-usgs** [comment]
So what does this mean?
$ python collect.py -p FI14 --download -o ../../CF-1.6new
2015-07-06 10:55:03 gam thredds_crawler[750] INFO Crawling:
http://geoport.whoi.edu/thredds/catalog/usgs/data2/emontgomery/stellwagen/Data/FI14/catalog.xml
2015-07-06 10:55:03 gam root[750] INFO Found 0 datasets in FI14!
2015-07-06 10:55:03 gam root[750] INFO Found 0 TOTAL datasets!

I'm guessing the TDS hasn't figured out that there are files in
stellwagen/Data/FI14?  They were just re-obtained from stellwagen.  I
waited about 5 mins and tried again and still get no datasets.  Do I need
to re-hup something?

On Mon, Jul 6, 2015 at 10:53 AM, Montgomery, Ellyn <emontgomery@usgs.gov>
wrote:

> Will do.  Bug stomping boots on.
>
> On Mon, Jul 6, 2015 at 10:43 AM, Kyle Wilcox <notifications@github.com>
> wrote:
>
>> @emontgomery-usgs <https://github.com/emontgomery-usgs> Can you send me
>> a BW2011 file that is failing after downloading? I will compare it to
>> the file I get after downloading.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/80#issuecomment-118876455>
>> .
>>
>
>
>
> --
> Ellyn Montgomery, Oceanographer and Data Manager
> U.S. Geological Survey
> Woods Hole Coastal and Marine Science Center
> 384 Woods Hole Rd., Woods Hole, MA, 02543-1598
> (508) 457-2356
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
There are no datasets in the folder: http://geoport.whoi.edu/thredds/catalog/usgs/data2/emontgomery/stellwagen/Data/FI14/catalog.html

You may need to restart THREDDS?

**Comment by emontgomery-usgs** [comment]
There are files in the directory.  I don't think I have permission to
restart TDS on geoport, and probably shouldn't try.  It's supposed to
autoharvest, isn't it?

On Mon, Jul 6, 2015 at 11:14 AM, Kyle Wilcox <notifications@github.com>
wrote:

> There are no datasets in the folder:
> http://geoport.whoi.edu/thredds/catalog/usgs/data2/emontgomery/stellwagen/Data/FI14/catalog.html
>
> You may need to restart THREDDS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/80#issuecomment-118886772>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
@emontgomery-usgs, If the TDS can't see it, it's a permissions issue.   The data has to be readable by the TDS process, which is owned by `usgs:usgs`.   I did:
```
cd /usgs/data2/emontgomery/stellwagen/Data/
sudo chmod 755 FI14
```
and now it can be seen on the TDS

**Comment by emontgomery-usgs** [comment]
Konk! (sound or hand against forehead).  Thanks!

 @rsignell-usgs.  Aren't you supposed to be on vacation?  Put the computer
down!

On Mon, Jul 6, 2015 at 1:49 PM, Rich Signell <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs>, If the TDS can't
> see it, it's a permissions issue. The data has to be readable by the TDS
> process, which is owned by usgs:usgs. I did:
>
> cd /usgs/data2/emontgomery/stellwagen/Data/
> sudo chmod 755 FI14
>
> and now it can be seen on the TDS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/80#issuecomment-118937432>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
I'm actually working in Boston, and tomorrow heading for SciPy in Austin for the week.   Trying to get my presentation ready for Friday.   ;-)

**Comment by emontgomery-usgs** [comment]
OK, as long as you're not working while ostensibly vacationing.  I'll see
how the FI14 data behaves now that the TDS sees it.

Have fun with SciPy!

On Mon, Jul 6, 2015 at 2:28 PM, Rich Signell <notifications@github.com>
wrote:

> I'm actually working in Boston, and tomorrow heading for SciPy in Austin
> for the week. Trying to get my presentation ready for Friday. ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/80#issuecomment-118948195>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by emontgomery-usgs** [comment]
Since everything except BW2011 is done, I renamed the original CF-1.6
directory to CF-1.6_preJul2015, and moved the new one to CF-1.6.  So the
portal should be getting the most recent run now.

On Mon, Jul 6, 2015 at 2:33 PM, Montgomery, Ellyn <emontgomery@usgs.gov>
wrote:

> OK, as long as you're not working while ostensibly vacationing.  I'll see
> how the FI14 data behaves now that the TDS sees it.
>
> Have fun with SciPy!
>
> On Mon, Jul 6, 2015 at 2:28 PM, Rich Signell <notifications@github.com>
> wrote:
>
>> I'm actually working in Boston, and tomorrow heading for SciPy in Austin
>> for the week. Trying to get my presentation ready for Friday. ;-)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/80#issuecomment-118948195>
>> .
>>
>
>
>
> --
> Ellyn Montgomery, Oceanographer and Data Manager
> U.S. Geological Survey
> Woods Hole Coastal and Marine Science Center
> 384 Woods Hole Rd., Woods Hole, MA, 02543-1598
> (508) 457-2356
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
@emontgomery-usgs  Has the issue with `BW2011` been resolved?

**Comment by emontgomery-usgs** [comment]
no. I haven't tried it since it failed for me but worked for you.

On Tue, Jul 21, 2015 at 10:45 AM, Kyle Wilcox <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs> Has the issue
> with BW2011 been resolved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/80#issuecomment-123350426>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by emontgomery-usgs** [comment]
I just tried re-running BW2011, after removing all the files from that
experiment and it still fails.  All the files from the experiment are
copied successfully, but the first file it tries to translate fails with
this message: Translating download/9031ysi-a.nc into CF1.6 format:
/usgs/data2/emontgomery/stellwagen/CF-1.6new/BW2011/9031ysi-a.nc
Segmentation fault (core dumped)

sorry!

On Tue, Jul 21, 2015 at 12:36 PM, Montgomery, Ellyn <emontgomery@usgs.gov>
wrote:

> no. I haven't tried it since it failed for me but worked for you.
>
> On Tue, Jul 21, 2015 at 10:45 AM, Kyle Wilcox <notifications@github.com>
> wrote:
>
>> @emontgomery-usgs <https://github.com/emontgomery-usgs> Has the issue
>> with BW2011 been resolved?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/80#issuecomment-123350426>
>> .
>>
>
>
>
> --
> Ellyn Montgomery, Oceanographer and Data Manager
> U.S. Geological Survey
> Woods Hole Coastal and Marine Science Center
> 384 Woods Hole Rd., Woods Hole, MA, 02543-1598
> (508) 457-2356
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
I tried creating a new custom conda environment on another linux 64 machine (the IOOS comt machine) and it seg faulted.

I then tried installing everything from PIP instead of conda and it also seg faulted.

@kwilcox are you trying this on linux?

**Comment by rsignell-usgs** [comment]
Here's what my pip-installed version has:
```
(convert)[testbed@testbed2 ~]$ conda list
# packages in environment at /home/testbed/anaconda/envs/convert:
#
coloredlogs               1.0.1                     <pip>
epic2cf                   0.0.4                     <pip>
humanfriendly             1.32                      <pip>
lxml                      3.4.4                     <pip>
netcdf4                   1.1.8                     <pip>
numpy                     1.9.2                     <pip>
openssl                   1.0.1k                        1    http://repo.continuum.io/pkgs/free/linux-64/openssl-1.0.1k-1.tar.bz2
pandas                    0.16.2                    <pip>
pip                       7.1.0                    py27_0    defaults
pyaxiom                   0.0.12                    <pip>
python                    2.7.10                        0    defaults
python-dateutil           2.4.2                     <pip>
pytz                      2015.4                    <pip>
readline                  6.2                           2    <unknown>
requests                  2.7.0                     <pip>
setuptools                18.0.1                   py27_0    defaults
six                       1.9.0                     <pip>
sqlite                    3.8.4.1                       1    defaults
system                    5.8                           2    defaults
thredds-crawler           1.0.0                     <pip>
tk                        8.5.18                        0    http://repo.continuum.io/pkgs/free/linux-64/tk-8.5.18-0.tar.bz2
zlib                      1.2.8                         0    http://repo.continuum.io/pkgs/free/linux-64/zlib-1.2.8-0.tar.bz2
```

**Comment by rsignell-usgs** [comment]
@kwilcox , was there a fix for this?

**Comment by kwilcox** [comment]
@rsignell-usgs aye, I added a workaround for the bug in netcdf4-python, which has since been fixed

**Comment by rsignell-usgs** [comment]
Does this mean we are finally ready to create our CF-1.6 data?   
Do we just need to update pyaxiom, collect.py and rerun?
