### ISSUE TITLE
Problem with collect.py and a very large file, or 2 collect.py run simultaneously

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#81]
I had this command running in one window:  
python collect.py -p BARNEGAT --folder download -o ../../CF-1.6new
It was running happily until I got this message:

INFO Translating download/9777solot-a.nc into CF1.6 format: /usgs/data2/emontgomery/stellwagen/CF-1.6new/BARNEGAT/9777solot-a.nc
DEBUG Could not find CF mapping for EPIC code 624.0
DEBUG Could not find CF mapping for EPIC code 624.0
DEBUG Could not find CF mapping for EPIC code 500.0
DEBUG Could not find CF mapping for EPIC code 502.0
ERROR Error. Skipping download/9781dw-a.nc.
Traceback (most recent call last):
  File "collect.py", line 457, in main
    normalize_vectors(temp_file)
  File "collect.py", line 315, in normalize_vectors
    nc = netCDF4.Dataset(netcdf_file, 'a')
  File "netCDF4/_netCDF4.pyx", line 1547, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:9551)
RuntimeError: No such file or directory
Traceback (most recent call last):
  File "collect.py", line 659, in <module>
    main(args.output, args.folder, args.download, projects, os.path.realpath(args.csv_metadata_file), files)
  File "collect.py", line 617, in main
    os.remove(temp_file)
OSError: [Errno 2] No such file or directory: '/usgs/data2/emontgomery/stellwagen/usgs-cmg-portal/woods_hole_obs_data/temp/9781dw-a.nc'

This error just happened to coincide with me launching another collect.py on a different experiment in a different window.  Maybe coincidence?  I haven't tried running 2 at the same time, so don't know if there are any conflicting resources.

The *dw* files are all big.  In CF-1.6new/BARNEGAT, there are several *dw* files that processed correctly at ~2GB each, but the one that failed is closer to 5GB.  Might this be the problem?

**Comment by kwilcox** [comment]
It was not designed to run more than one instance at a time, I will fix shortly!

**Comment by emontgomery-usgs** [comment]
sorry to use an unexpected workflow.

On Thu, Jul 2, 2015 at 10:29 AM, Kyle Wilcox <notifications@github.com>
wrote:

> It was not designed to run more than one instance at a time, I will fix
> shortly!
>
> —
> Reply to this email directly or view it on GitHub.
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
Fixed via https://github.com/USGS-CMG/usgs-cmg-portal/commit/e31022b4706d1f7f9b2d78da96b53ee5ec2dfd70
