### ISSUE TITLE
SGrid demo for Friday

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#84]
It would be really nice if we could do an SGRID demo that I could show in my SciPy talk at 2PM on Friday. 

Basically I'd love to show a figure of bottom velocity vectors in the Hudson Shelf Valley from a ROMS Sandy simulation, like in this ipython notebook
http://nbviewer.ipython.org/gist/rsignell-usgs/a85e68a71933910a171a

But of course I'd like to do this using `sci-wms` and the new `sgrid` convention support in `sci-wms`. 

Do you think we could do it?

We would need to:
- [x] make sure the dataset shows up in the portal
- [x] make sure the dataset is SGRID compliant (it should be)
- [x] install the latest sci-wms somewhere
- [x] see if we can select the bottom layer and show vectors

@kwilcox, do you think this is possible or impossible for Friday?

The first priority is still just getting sci-wms to a releasable state before Friday.  
But this would be proof that SGRID support is working in that version.

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

If I recall correctly, I think we had discussed that `standard_name` would be required to "play" with sci-wms. I just tried the Hudson Shelf Valley dataset and sci-wms vomited when I failed to find variables by `standard_name`.

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

Pysgrid however, will happily give you an `sgrid` object from the dataset.

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

If you need to be able to easily access the child grids as discussed at https://github.com/sgrid/pysgrid/issues/50 before releasing, then I would need to add some methods to `pysgrid` to make that a more facile process. I can work on that while at the conference, but I wouldn't say that those additions could be confidently added in by Friday.

At present, `pysgrid` doesn't carry around the lat/lon data for the child grids. It does however carry information on where it can be found... for example one could do `sg.u.coordinates` or `sg.u.dimensions`.

**Comment by rsignell-usgs** [comment]
@ayan-usgs, I added the `standard_name='time'`, so we could try again?

**Comment by ayan-usgs** [comment]
I'm not sure that the `standard_name` addition to `ocean_time` made it through? The dataset at http://geoport.whoi.edu/thredds/dodsC/clay/usgs/users/jcwarner/Projects/Sandy/triple_nest/00_dir_NYB05.ncml is still showing:

```
    double ocean_time(ocean_time=201);
      :long_name = "time since initialization";
      :units = "seconds since 1858-11-17 00:00:00";
      :calendar = "gregorian";
      :field = "time, scalar, series";
```

**Comment by rsignell-usgs** [comment]
@ayan-usgs , yeah, I have to figure out what is going on there.  It apparently isn't using the up-to-date yaml2ncml.   I'll check it out.

**Comment by rsignell-usgs** [comment]
@ayan-usgs, this is finally fixed.   I see `standard_name='time'` in there now, looking at:
http://geoport.whoi.edu/thredds/dodsC/clay/usgs/users/jcwarner/Projects/Sandy/triple_nest/00_dir_NYB05.ncml.html
