### ISSUE TITLE
Is the new CF-1.6 data accessed correctly?

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#85]
@kwilcox Is the portal accessing the updated CF-1.6 data correctly?  For the datasets I tried to access, the viewer pane reported "error retrieving the data".

Related question- for the Icon in the middle of Buzzards Bay, only the seacat data is shown.  How would I view the ADCP and YSI data from that platform?  
Thanks!
![image](https://cloud.githubusercontent.com/assets/1771422/8621896/3600b3c6-26f6-11e5-95f0-c572065fc435.png)

**Comment by kwilcox** [comment]
@emontgomery-usgs I haven't updated the CF-1.6 data in months!  It;s downloading right now and I'll post back when it is up in the portal.

**Comment by emontgomery-usgs** [comment]
Please explain the data pathway.  There's no auto harvest when new data is
available on geoport?  Somehow I thought the portal accessed the TDS on
geoport directly, no additional transformations needed...

thanks!

On Tue, Jul 21, 2015 at 11:28 AM, Kyle Wilcox <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs> I haven't updated
> the CF-1.6 data in months! It;s downloading right now and I'll post back
> when it is up in the portal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/85#issuecomment-123370373>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
@kwilcox , is this new data now up in the portal?

**Comment by kwilcox** [comment]
@rsignell-usgs @emontgomery-usgs waiting on a few answers before adding the new data, namely:

https://github.com/USGS-CMG/usgs-cmg-portal/issues/77
