### ISSUE TITLE
modify thredds crawler script to inject sci-wms endpoints into ISO metadata

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#89]
We currently crawl thredds catalogs [using python scripts](https://github.com/USGS-CMG/usgs-cmg-portal/tree/master/catalog_harvest) that extract ISO metadata using the ncISO service.   For SGRID and UGRID data, we want to modify the ISO metadata endpoints for WMS, replacing the WMS endpoints coming from THREDDS/ncISO with sci-wms endpoints.

We need to modify the python scripts so that they perform these steps for each new dataset:

1. Create a sci-wms endpoint using the REST interface for sci-wms, returning a dataset id. 

2. Return the layers that are associated with that dataset.

3. Allow the possibility that the python script can set the min/max values, obtained by reading `vmin` and `vmax` variable attributes (if they exist).

4. Write the sci-wms WMS endpoint into the ISO metadata, replacing the ncISO WMS endpoint.

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

I assume the requirement specified in #37 to check for a project with text equal to `CMG_Portal` still applies. Can you confirm?

**Comment by rsignell-usgs** [comment]
Yes, that is correct.     Please try modifying a copy of this script for starters:
https://github.com/USGS-CMG/usgs-cmg-portal/blob/master/catalog_harvest/get_ncml_daily_iso.py

**Comment by rsignell-usgs** [comment]
Fixed in #93, so closing.
