### ISSUE TITLE
COAWST Sandy Model output not displaying properly in portal

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#90]
I tried to look at salinity from one of the Sandy models this morning and got no image:
http://cmgdata.usgsportals.net/#map?p=proj3857&b=google_hybrid&page=1&tagId=&q=sandy&lg=2749d3cf-f4d1-404e-83ad-3563e3917644&z=10&ll=40.69502%2C-73.01740

I thought maybe our WMS service was down, but checked Godiva2 and it was super speedy.  Screen grabs from CMG_Portal and Godiva2 below:
![7-28-2015 8-43-01 am](https://cloud.githubusercontent.com/assets/1872600/8931734/661b03e0-3506-11e5-9bc2-84cdbcb7ed16.jpg)
![7-28-2015 8-44-00 am](https://cloud.githubusercontent.com/assets/1872600/8931736/68d353c6-3506-11e5-9b8f-6c28fdfd04a5.png)

**Comment by kwilcox** [comment]
The CSW server we harvest from don't use the WMS server you screenshot above.  I you have `geoport-dev.who.edu/...`.  You'll need to bring `geoport-dev` back up or change the information in your CSW server.

**Comment by rsignell-usgs** [comment]
@kwilcox , ah, okay.   That explains it.    geoport-dev was indeed down since yesterday with a memory error: 
```
********************************************************************************
* Plumbr has detected an OutOfMemoryError thrown by the JVM.                   *
* See https://portal.plumbr.eu to find more info.                              *
********************************************************************************
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000009ffe, pid=4037, tid=140691427198720
#
# JRE version: 7.0_11-b21
# Java VM: Java HotSpot(TM) 64-Bit Server VM (23.6-b04 mixed mode linux-amd64 compressed oops)
#
```
After relaunching thredds-dev, things are okay:
![7-28-2015 9-29-45 am](https://cloud.githubusercontent.com/assets/1872600/8932513/a865f994-350b-11e5-86ee-0b69a69f0ce8.jpg)
