### ISSUE TITLE
NOAA charts as background layer doesn't seem to be working

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#91]
NOAA charts as background layer doesn't seem to be working:
http://cmgdata.usgsportals.net/#map?p=proj3857&b=noaa_charts&lg=8ccf971e-565c-11e4-9915-00265529168c&z=5&ll=42.98998%2C-68.12109
![image 1](https://cloud.githubusercontent.com/assets/1872600/8942056/78915ef8-3541-11e5-8849-eb908ba19dd6.png)

**Comment by shane-axiom** [comment]
@akbstone

**Comment by akbstone** [comment]
I've removed NOAA Charts and Topo base layer options until we can find a provider that covers the east coast. Current provider GINA covers west coast.

**Comment by akbstone** [comment]
![image](https://cloud.githubusercontent.com/assets/1093777/8944461/4ba7b25c-352d-11e5-9f9f-7842b8273981.png)

**Comment by akbstone** [comment]
![image](https://cloud.githubusercontent.com/assets/1093777/8944484/5ea31ae0-352d-11e5-80b3-3c997f961445.png)
