### ISSUE TITLE
 USGS sensor data is responding "error getting data from server"

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#92]
When I demoed the server to Neil today, all the historical sensor data from USGS was returning "error retrieving data".   Click any sensor on:  http://cmgdata.usgsportals.net/#map?p=proj3857&b=google_hybrid&lg=8ccf971e-565c-11e4-9915-00265529168c&z=9&ll=41.57580%2C-70.42822

![7-28-2015 4-52-09 pm](https://cloud.githubusercontent.com/assets/1872600/8943468/12d6e5f8-3549-11e5-8105-50a44d4ac411.jpg)

**Comment by kwilcox** [comment]
I've removed the old data from the portal a since it was incorrect in many ways (depths reversed, incorrect unit conversions, etc.). The new data should be coming online shortly (this week).

**Comment by rsignell-usgs** [comment]
Does the new data coming online on the portal depend on us running the conversion script here?

**Comment by kwilcox** [comment]
@rsignell-usgs yup, the data needs to be available on your THREDDS server
