### ISSUE TITLE
COAWST forecast is showing up twice

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#97]
For some reason, today the COAWST forecast dataset is showing up twice:
![8-26-2015 4-24-09 pm](https://cloud.githubusercontent.com/assets/1872600/9505196/02641fec-4c0f-11e5-9f99-fda6ad4928de.jpg)

but it seems that the problem is not with our pycsw service, as it only lists that dataset once:
http://nbviewer.ipython.org/gist/rsignell-usgs/0fc4f5cd1f85ec411458

**Comment by shane-axiom** [comment]
Fixed, this was an artifact of an older harvest method.
