### ISSUE TITLE
Significant Wave Height is not showing up in COAWST forecast

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#98]
@kwilcox, For some reason the COAWST forecast significant wave height (Hwave) is not one of the available variables in the portal.   
http://cmgdata.usgsportals.net/#module-metadata/8320fd2b-7b09-38c5-9743-91722f17ea53/5895ada7-ca87-436b-b58a-e65062d6b4ac

I confirmed that I can access and display it with the sci-wms simple map client, although it was broken until Andrew released sci-wms 1.1.1 earlier today.     

Does something need to get reharvested for Hwave to show up?

Or do we need more metadata for this variable or something on our end?

Trying to understand the workflow and issues here...

**Comment by kwilcox** [comment]
Without a standardized way to know what variables should be included in the portal, its always going to be difficult. We talked about an attribute to say "yes put this in the portal", but I think we agreed that not many data provides will provide that.  Right now I set a default list for each model (hardcoded) in the CSW harvest.  `Hwave` wasn't in the initial list we agreed upon. I'll add it.

**Comment by kwilcox** [comment]
I rescanned the CSW and its now available: http://cmgdata.usgsportals.net/#module-metadata/8320fd2b-7b09-38c5-9743-91722f17ea53/efcabc2e-eeb3-47b2-8b68-c7cbacf666a2

**Comment by rsignell-usgs** [comment]
It shows up, but I can't get an image.

**Comment by kwilcox** [comment]
Let discuss in https://github.com/USGS-CMG/usgs-cmg-portal/issues/99 (same issue)
